### ISSUE TITLE
Can't build XGBoost multithread on MAC

### ISSUE THREAD

**Issue by amro-pydev** [dmlc/xgboost#677] opened 2015-12-07 16:44 UTC
Hi,

I was trying to build XGBoost on my MAC as the one on pip wasn't the latest.

I followed the instructions mentioned for building on OS X to make sure it supports MultiThreading. Unfortunately, it failed and gave me the following error:
construction vtable for std::__1::basic_iostream<char, std::__1::char_traits<char> >-in-std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in gbm.o
ld: symbol(s) not found for architecture x86_64

on the other hand it went through building the Single threaded build with no issues. I really need to to have the multithread support as I'm using XGBoost with large data.

Thanks in advance.
-Amr

**Comment by amro-pydev** [comment] 2015-12-07 16:47
Here is my version for g++:
g++ (Homebrew gcc 5.3.0 --without-multilib) 5.3.0

**Comment by amro-pydev** [comment] 2015-12-07 16:58
Fixed the issue, it seems that if the link to the file name is g++ it sees it as g++ 4.9 but if the file name is g++-5 and gcc-5 it works as if it's gcc 5.x.x.

I changed the file link names from g++ to g++-5 and from gcc to gcc-5.

**Comment by amro-pydev** [comment] 2015-12-07 17:04
Now stuck with another issue:
make pythonpack
#make clean
cd subtree/rabit;make clean;cd ..
rm -f ./allreduce_base.o ./allreduce_robust.o ./engine.o ./engine_empty.o ./engine_mock.o ./rabit_wrapper.o ./engine_base.o ./engine_mpi.o lib/librabit.a lib/librabit_mpi.a lib/librabit_empty.a lib/librabit_mock.a lib/librabit_base.a  wrapper/librabit_wrapper.so wrapper/librabit_wrapper_mock.so wrapper/librabit_wrapper_mpi.so *~ src/*~ include/*~ include/*/*~ wrapper/*~
rm -rf xgboost-deploy xgboost*.tar.gz
#pip install pypandoc and also brew/apt-get install pandoc
python python-package/conv_rst.py
Traceback (most recent call last):
  File "python-package/conv_rst.py", line 6, in <module>
    read_md = convert('python-package/README.md', 'rst')
  File "anaconda/lib/python2.7/site-packages/pypandoc/__init__.py", line 50, in convert
    outputfile=outputfile, filters=filters)
  File "anaconda/lib/python2.7/site-packages/pypandoc/__init__.py", line 68, in _convert
    raise RuntimeError('Missing format!')
RuntimeError: Missing format!
make[1]: *** [pythonpack] Error 1
make: *** [pythonbuild] Error 2

Installed pandoc:
pip install pypandoc
Collecting pypandoc
  Downloading pypandoc-1.1.2-cp27-none-macosx_10_5_x86_64.whl (29.2MB)
    100% |████████████████████████████████| 29.2MB 7.3kB/s 
Requirement already satisfied (use --upgrade to upgrade): setuptools in /anaconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg (from pypandoc)
Installing collected packages: pypandoc
Successfully installed pypandoc-1.1.2

**Comment by amro-pydev** [comment] 2015-12-07 17:05
Is there is a way to ignore building documentation for python package? I don't want the documentation.

**Comment by amro-pydev** [comment] 2015-12-07 17:07
Used python setup.py install inside the python package folder and worked like charm.

-Amro

**Comment by amro-pydev** [comment] 2015-12-08 03:04
When I tried to run it I got the following error:

ERROR: Failure: OSError (dlopen(/Users/atork/Sources/xgboost-master/python-package/xgboost/../../wrapper/libxgboostwrapper.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/5/libgomp.1.dylib
  Referenced from: /Users/atork/Sources/xgboost-master/wrapper/libxgboostwrapper.so
  Reason: image not found)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/atork/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/atork/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/atork/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/atork/Sources/xgboost-master/python-package/xgboost/__init__.py", line 11, in <module>
    from .core import DMatrix, Booster
  File "/Users/atork/Sources/xgboost-master/python-package/xgboost/core.py", line 83, in <module>
    _LIB = _load_lib()
  File "/Users/atork/Sources/xgboost-master/python-package/xgboost/core.py", line 77, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/Users/atork/anaconda/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/Users/atork/anaconda/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/atork/Sources/xgboost-master/python-package/xgboost/../../wrapper/libxgboostwrapper.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/5/libgomp.1.dylib
  Referenced from: /Users/atork/Sources/xgboost-master/wrapper/libxgboostwrapper.so
  Reason: image not found

----------------------------------------------------------------------

I followed the steps mentiond for MacOSX.

Note that homebrew install gcc in different location other than the default including it's libraries.

**Comment by phunterlau** [comment] 2015-12-08 04:24
@amro-pydev `pythonpack` process is for building pip installation package for pip maintainer, and it is not for general users. Please just use `make` for building all necessary packages and `python setup.py install`

**Comment by amro-pydev** [comment] 2015-12-08 05:37
HI Hongliang,

That's exactly what I did. The compilation went smoothly, but the error came up when I tried to run my script. It can't find the shared library installed by brew.

I'm not sure if there is a good solution for that.

-Amro

**Comment by phunterlau** [comment] 2015-12-08 05:56
@amro-pydev have you tried brew unlink your old gcc, and reinstall and link gcc-5 /g++-5 ? It is a brew installation problem.

**Comment by amro-pydev** [comment] 2015-12-08 06:17
Hi Hongliang,

Thanks for your response. I don't know how to unlink my old gcc?

-Amr

**Comment by phunterlau** [comment] 2015-12-08 06:35
@amro-pydev em, something like `brew unlink gcc-49`? Some google search may help on this tech detail.

**Comment by amro-pydev** [comment] 2015-12-09 08:51
Hi Hongliang,

Tried and failed to build it on Mac OS X. But I successfully installed it from the PIP using the updated version that you have uploaded yesterday.

Thanks,
-Amr

**Comment by phunterlau** [comment] 2015-12-09 16:26
@amro-pydev Good to know the pip installation works for you. Since the problem is somewhere in your gcc configuration and it is no longer a problem for you, I think we can close this issue. By the way, I will provide pre-compiled wheels for pip in future, so no more worries about compiling in major operating systems.

**Closed by phunterlau** 2015-12-09 16:26 UTC

**Comment by tgb417** [comment] 2016-12-27 01:14
I'm having a very similar problem trying to get python xgboots working.

However, I'm seeing this issue in Dec 2016, on Mac OS 10.11.6

I have an error ending in
OSError: dlopen(/Users/brown/anaconda/lib/python2.7/site-packages/xgboost/./lib/libxgboost.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/5/libgomp.1.dylib
  Referenced from: /Users/brown/anaconda/lib/python2.7/site-packages/xgboost/./lib/libxgboost.so
  Reason: image not found

When I look for the directory /usr/local/opt/gcc/lib/gcc/5 it does not exist I have a directory
  /usr/local/opt/gcc/lib/gcc/6 with what appears to be the correct file libgomp.1.dylib.  

Not clear how I point my python code toward this new directory.

Tried to install the library under anaconda, with the pip install xgboost command.

Thoughts...

**Comment by gmanolache** [comment] 2018-07-23 16:22
+1

**Comment by tgb417** [comment] 2018-07-30 13:03
@gmanolache I did eventually get this installed.  However it has been more than a year and 1/2 ago.  I do not remember ALL the details that were needed to get this done.  However, I do remember working on this for several days on and off.

Anaconda seems to have recompiled versions for both Python and R.  If I was trying to do this today.  I’d likely do this through a package manager.  Other environments like Dataiku’s DSS seem to provide precompileed versions that work  ok.  This is likely good enough unless you need something from a more recent version.

Hope that helps.

**Comment by hcho3** [comment] 2018-07-30 13:12
Here are the steps I use to compile XGBoost on my Macbook Pro:

1. Install GCC 7 with Homebrew: `brew install gcc@7`
2. Compile XGBoost using CMake:
```
mkdir build
cd build
cmake .. -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7
make -j4
```
