### ISSUE TITLE
assert part.status == 'finished'  AssertionError

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#6364] opened 2020-11-10 07:56 UTC
See for setup details: #6232

Trying out mulitnode xgboost with dask, hitting this problem right away.  I have no errors with dask setup and dashboard looks good, but hitting this:

```
2020-11-09 23:50:03,150 C: 20% D:76.5GB  M:88.0GB  NODE:LOCAL1      13813  DATA   |   File "/data/jon/h2oai.fullcondatest3/h2oaicore/models.py", line 7076, in dask_fit
2020-11-09 23:50:03,151 C: 20% D:76.5GB  M:88.0GB  NODE:LOCAL1      13813  DATA   |     func(X, y, **kwargs_dask)
2020-11-09 23:50:03,151 C: 20% D:76.5GB  M:88.0GB  NODE:LOCAL1      13813  DATA   |   File "/home/jon/minicondadai/lib/python3.6/site-packages/xgboost/dask.py", line 1080, in fit
2020-11-09 23:50:03,152 C: 20% D:76.5GB  M:88.0GB  NODE:LOCAL1      13813  DATA   |     eval_set, sample_weight_eval_set, verbose)
2020-11-09 23:50:03,152 C: 20% D:76.5GB  M:88.0GB  NODE:LOCAL1      13813  DATA   |   File "/home/jon/minicondadai/lib/python3.6/site-packages/distributed/client.py", line 824, in sync
2020-11-09 23:50:03,152 C: 20% D:76.5GB  M:88.0GB  NODE:LOCAL1      13813  DATA   |     self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
2020-11-09 23:50:03,153 C: 20% D:76.5GB  M:88.0GB  NODE:LOCAL1      13813  DATA   |   File "/home/jon/minicondadai/lib/python3.6/site-packages/distributed/utils.py", line 339, in sync
2020-11-09 23:50:03,153 C: 20% D:76.5GB  M:88.0GB  NODE:LOCAL1      13813  DATA   |     raise exc.with_traceback(tb)
2020-11-09 23:50:03,154 C: 20% D:76.5GB  M:88.0GB  NODE:LOCAL1      13813  DATA   |   File "/home/jon/minicondadai/lib/python3.6/site-packages/distributed/utils.py", line 323, in f
2020-11-09 23:50:03,154 C: 20% D:76.5GB  M:88.0GB  NODE:LOCAL1      13813  DATA   |     result[0] = yield future
2020-11-09 23:50:03,154 C: 20% D:76.5GB  M:88.0GB  NODE:LOCAL1      13813  DATA   |   File "/home/jon/minicondadai/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
2020-11-09 23:50:03,155 C: 20% D:76.5GB  M:88.0GB  NODE:LOCAL1      13813  DATA   |     value = future.result()
2020-11-09 23:50:03,155 C: 20% D:76.5GB  M:88.0GB  NODE:LOCAL1      13813  DATA   |   File "/home/jon/minicondadai/lib/python3.6/site-packages/xgboost/dask.py", line 1046, in _fit_async
2020-11-09 23:50:03,156 C: 20% D:76.5GB  M:88.0GB  NODE:LOCAL1      13813  DATA   |     missing=self.missing)
2020-11-09 23:50:03,156 C: 20% D:76.5GB  M:88.0GB  NODE:LOCAL1      13813  DATA   |   File "/home/jon/minicondadai/lib/python3.6/site-packages/xgboost/dask.py", line 286, in map_local_data
2020-11-09 23:50:03,157 C: 20% D:76.5GB  M:88.0GB  NODE:LOCAL1      13813  DATA   |     assert part.status == 'finished'
2020-11-09 23:50:03,157 C: 20% D:76.5GB  M:88.0GB  NODE:LOCAL1      13813  DATA   | AssertionError
```

What does this mean? @teju85 

I'm running same kind of example as here: https://github.com/dmlc/xgboost/issues/6280

but this time I'm not using the local cuda client, and instead I'm using the CLI for dask-cuda-worker.

Here's cluster from dask dashboard, all healthy:

![image](https://user-images.githubusercontent.com/2249614/98645610-16c91a00-22e7-11eb-9b85-9eefb0dcb66e.png)

Nothing in logs shows any problems with dask, just xgboost fails.

Perhaps there is some limitation I'm hitting?

E.g. Only thing "odd" is I'm using 3 2-GPU nodes and 1 1-GPU node together in a single dask cluster.  dask doesn't care, but maybe xgboost cannot handle?

I'm just guessing, but would be good to understand reason for that xgboost error.

**Comment by trivialfis** [comment] 2020-11-10 20:28
> E.g. Only thing "odd" is I'm using 3 2-GPU nodes and 1 1-GPU node together in a single dask cluster. dask doesn't care, but maybe xgboost cannot handle?

The assertion is just checking all computation prior to xgboost is done.

**Comment by trivialfis** [comment] 2020-11-30 14:16
I think this is an issue in early pipeline.  Can you try to persist and wait for the data before constructing DaskDMatrix?

**Comment by trivialfis** [comment] 2020-12-15 18:13
I'm closing this for now.  Feel free to reopen when there's a reproducible example.  So far I believe it's due to early pipeline error as the status xgboost's checking is the status of data partition.  No computation in xgboost is performed yet at this stage.  Lazy evaluation can delay the early error into xgboost DMatrix.

**Closed by trivialfis** 2020-12-15 18:13 UTC
Labels: dask
