### ISSUE TITLE
Training behaviour difference between v1.1.0 and v1.3.1

### ISSUE THREAD

**Issue by fordicus** [dmlc/xgboost#6552] opened 2020-12-25 07:31 UTC
Merry Christmas, all.

I am suffering from a different behaviour between an old version and 
the newest version of XGBoost. Here are some information.

* 1.3.1 ( pip install xgboost                  ) the newest one
* 1.1.0 ( pip install -Iv xgboost==1.1.0 ) the old one that I used
Ubuntu 18.04.4 LTS
CUDA   11.1.74
QUADRO RTX 8000 48GB

Data file (7.49 GB) can be downloaded from (mega cloud)
https://mega.nz/file/irQXCSbA#rfl53ewh88k_pBsVLw_fA5hC6mz91Vi9yRUrMqEMYno

or it also can be found at (google drive)
https://drive.google.com/file/d/14RCv2COi6rw7JWDkYp9825z7zSHY1ogQ/view?usp=sharing

The issue with the old version was not being able to dump the trained model
while the training itself progresses very nicely.
( https://discuss.xgboost.ai/t/serialisation-of-large-models/1897/2 )

As I am aware that there have been a lot of effort to improve the dump process,
I had to try the newest version. But using the newst version, the issue is that
I cannot see the same training behaviour as the old one. Simply put,
it seems it takes a way longer time in order to see the rounds proceed.
I only terminated with a keyboard interruption.

For 30 minutes, there is no one-single progress of a round using v1.3.1.
Using v1.1.0 and waiting for 30 minutes, the prints at terminal read

[0]  convergence-merror:0.10068
[1]  convergence-merror:0.10052
[2]  convergence-merror:0.09998
[3]  convergence-merror:0.09930
[4]  convergence-merror:0.09852
[5]  convergence-merror:0.09773
[6]  convergence-merror:0.09690
[7]  convergence-merror:0.09608
[8]  convergence-merror:0.09524
[9]  convergence-merror:0.09439
[10] convergence-merror:0.09355
[11] convergence-merror:0.09268
[12] convergence-merror:0.09182
[13] convergence-merror:0.09097
[14] convergence-merror:0.09013
[15] convergence-merror:0.08930
[16] convergence-merror:0.08855
[17] convergence-merror:0.08781
[18] convergence-merror:0.08708
[19] convergence-merror:0.08636
[20] convergence-merror:0.08557
[21] convergence-merror:0.08477

Note that reinstalling the old version after removing the newest recovers 
the previous good training procedure.

Since which code I use matters, I also put the code at the end of this.
You can give an input argument to tell how many rounds it trains when running the script.
But the path for the data that I mentioned above is hard-coded with its path.
I wish I could hear some advice.

Besides, I also want to study why this is happening from my side.
Could anyone let me know how to download the "full code" of v1.1.0
which I could install with ( pip install -Iv xgboost==1.1.0 )?

I want to study the routines and learn by myself about the implementation.
Since I am testing in Ubuntu, I am supposed to study and build the full code of 
the old version in Ubuntu. I am not very good at Github and I do not know how to
download the full code to build of an old release. 

Thanks a lot in advance.

Comment: I copied the code from Sublime Text. 
Some spaces look irregular here, though.
They would look better in a text editor hopefully.

```python
#-----------------------------------------------------------------------------------------
# modules
#-----------------------------------------------------------------------------------------
from   sklearn.metrics import accuracy_score # convenient accuracy measure
import xgboost         as     xgb            # XGBoost software package
import h5py                                  # deal with .mat data files
import sys                                   # deal with command arguments
import gc; gc.enable();                      # garbage memory collection 


#-------------------------------------------------------------------------------
# functions
#-------------------------------------------------------------------------------
def serialise_model(__pne__, __model__):
    __model__.save_model(__pne__); gc.collect()

def deserialise_model(__pne__):
    __model__ = xgb.Booster(); xgb.Booster.load_model(__model__, __pne__)
    return __model__

def load_mat(__pne__):  # load .mat data and return xgboost.DMatrix
    print('load_mat(%s): Commence.' % __pne__, flush = 1)
    Mat = h5py.File(__pne__)
    X__ = (Mat.get('X')[()]).transpose();
    y__ = (Mat.get('y')[()]).transpose().flatten(); del Mat;
    Xy_ = xgb.DMatrix(data = X__, label = y__)
    __shape__ = X__.shape
    print('load_mat(): DMatrix ready. X__.shape = ', end = '', flush = 1)
    print(__shape__, flush = 1)
    del X__; gc.collect();
    return Xy_, y__, __shape__;

def set_model_params(__max_depth__, __num_class__): 
    xgb_params = {
        'process_type':               'default',        # \in {default, update} for the continuation of a tree.
        'tree_method':                'gpu_hist',
        'booster':                    'gbtree',
        'grow_policy':                'lossguide',      # lossguide: split at nodes with highest loss change.
        'num_parallel_tree':          1,                # number of trees in boosted random forest.
        'min_split_loss':             0,                # 0: split whenver it improves.
        'learning_rate':              1.0,              # 1: no decay. weight on previous trees.
        'max_depth':                  __max_depth__,    # \in [0, Inf], 0 accepted if (hist | lossguided). cf. memory (!)
        'max_leaves':                 0,
        'reg_lambda':                 0.0,              # L2-regularisation
        'reg_alpha':                  0.0,              # L1-regularisation
        'num_class':                  __num_class__,
        'objective':                  'multi:softmax',
        'eval_metric':                'merror',
        'predictor':                  'gpu_predictor',
        'verbosity':                  1,
        'validate_parameters':        0,
        'single_precision_histogram': 0,                # gpu_hist can fail with single precision
        'deterministic_histogram':    0                 # default 1: rounds losing accuracy
    }

    return xgb_params


#-----------------------------------------------------------------------------------------
# data
#-----------------------------------------------------------------------------------------
data_pne         = '/workspace/temp/data.mat'
my_model_path    = '/workspace/temp/'
num_classes      = 3
my_max_depth     = 21 # 21
print('from: %s' % (data_pne))
print('to:   %s' % (my_model_path))


#-----------------------------------------------------------------------------------------
# user parameters
#-----------------------------------------------------------------------------------------
if len(sys.argv) != 2: 
    print('Give number of rounds');
    exit()

dump_model    = 1
my_print_freq = 1
xgb_params    = set_model_params(my_max_depth, num_classes)


#-----------------------------------------------------------------------------------------
# ----------------------------------------------------- using xgboost-core
#-----------------------------------------------------------------------------------------
Xy, y, shape  = load_mat(data_pne)
progress      = dict()
my_num_rounds = int(sys.argv[1])
my_model_pne  = '%s/%03d.json' % (my_model_path, my_num_rounds)

try:
    M0 = deserialise_model(my_model_pne)
    print('Existing model detected.\n')

except:
    M0 = None; print('Model will be newly trained.\n')
    M0 = xgb.train(xgb_params, Xy, my_num_rounds, [(Xy, 'convergence')], 
        evals_result = progress,
        verbose_eval = my_print_freq,
        xgb_model    = M0)

## report result
y0  = np.ubyte(M0.predict(Xy))
ACC = accuracy_score(y0, np.ubyte(y))
print('\nAccuracy = %6.2f%%' % (ACC * 100.0) )

## secure memory as much as possible
del Xy; del y; gc.collect()

## saving the trained model
if dump_model == 1:
    print('Dumping model M0: ', end = '', flush = 1);
    try:
        serialise_model(my_model_pne, M0)
    except:
        print('serialisation failure.')
```

**Comment by trivialfis** [comment] 2020-12-25 07:44
I will be back from holiday at 27, will take a look then.  Thanks for raising the issue.

**Comment by fordicus** [comment] 2020-12-28 14:23
> 
> 
> I will be back from holiday at 27, will take a look then. Thanks for raising the issue.

Hi. I tried to download the code for v1.1.0 by typing in Windows command
    git clone --branch v1.1.0 https://github.com/dmlc/xgboost.git 
.
But the folder \dmlc-core\ is empty while I believe all the important
routines must be in there. 

Could you help me to look into the code of version 1.1.0?
Thanks a lot.

**Comment by hcho3** [comment] 2020-12-28 21:06
@fordicus You should run `git submodule update --init --recursive`.

**Comment by fordicus** [comment] 2020-12-29 03:28
> 
> 
> @fordicus You should run `git submodule update --init --recursive`.

Thanks a lot. 

I have successfully complied visual studio solution file inside dmlc-core.
Could you give me some basic introduction how I can read, follow and understand
this dmlc-core in order to understand the internal behaviour of v1.1.0 XGBoost?

As mentioned, the goal is to understand the core and try to compare
what is the matter causing the different behaviour of the training compared to v1.3.0.
Unfortunately for my data and setting, only v1.1.0 works for training
(code and data provided above).

The source code that I am currently looking at is following.
>path: ..\dmlc-core\windows\dmlc.sln
build: Debug, x64
files loded:
 base.h
 basic_row_iter.h
 cached_input_split.h
 data.cc
 data.h
 disk_row_iter.h
 filesys.h
 input_split-base.cc
 input_split-base.h
 io.cc
 io.h
 libsvm_parse.h
 line_split.cc
 line_split.h
 local_filesys.cc
 local_filesys.h
 logging.h
 omp.h
 parser.h
 recordio.cc
 recordio.h
 recordio_split.cc
 orw_block.h
 single_file_split.h
 strtonum.h
 threadediter.h
 timer.h
 uri_spec.h
.

**Comment by trivialfis** [comment] 2020-12-29 15:43
We have document on how to  build xgboost from source.

**Comment by trivialfis** [comment] 2020-12-29 15:53
Let me see if I can download the dataset without installing the desktop app ...

**Comment by fordicus** [comment] 2020-12-29 17:09
> Let me see if I can download the dataset without installing the desktop app ...

I have a very slow internet speed here. I am re-synchronising from another pc using that cloud storage. Once I fully download the data there, I will try to find a better source to share the data which would not require downloading and installing an application.

**Comment by trivialfis** [comment] 2020-12-29 18:38
No worries.  I just got chromium  MEGA seems to be using an old file system API.

**Comment by trivialfis** [comment] 2020-12-29 19:23
@RAMitchell @hcho3 @ShvetsKS I haven't run the training yet, but I think the `ParallelGroupBuilder` is consuming way too much memory.  My system has 64GB memory and it the dmatrix construction eats swap file ...

**Comment by hcho3** [comment] 2020-12-29 19:24
@trivialfis Is it the case for the latest version of XGBoost?

An issue that might be related: https://discuss.xgboost.ai/t/help-understanding-memory-spike-when-creating-dmatrix/2046?u=hcho3

**Comment by trivialfis** [comment] 2020-12-29 19:25
Yup.  I can't get the test running on my local machine.  I think that's also where the slow down comes in.

**Comment by trivialfis** [comment] 2020-12-29 19:25
I can try some remote machines, but I think we should focus on optimizing/removing this linear scan struct instead.

**Comment by ShvetsKS** [comment] 2020-12-30 07:07
> @RAMitchell @hcho3 @ShvetsKS I haven't run the training yet, but I think the `ParallelGroupBuilder` is consuming way too much memory. My system has 64GB memory and the dmatrix construction eats swap file ...

It would be good to check if provided `nthread=1` DMatrix parameter helps as currently there are memory overheads in `ParallelGroupBuilder::InitBudget` with fully enabled threading. O(nrows_in_training_dataset) memory is required for all threads. It was eliminated before reverted commit https://github.com/dmlc/xgboost/pull/5877/commits/bdebab195d8ab6b3f0104b7ed6132ee7585f8d40 as part of https://github.com/dmlc/xgboost/pull/5877 at least for dense adapter.

The fix for dense adapter can be restored easily. For different from dense adapters it requires time or silly proposal is possible: keep single thread behavior for not dense adapters until better solution is ready.

**Comment by fordicus** [comment] 2020-12-30 22:25
I have added alternative link for the data
https://drive.google.com/file/d/14RCv2COi6rw7JWDkYp9825z7zSHY1ogQ/view?usp=sharing
which is using google drive and supposedely not requiring an installation of a program.

**Comment by IvanUkhov** [comment] 2020-12-31 06:50
I might have stumbled upon the same problem:

https://discuss.xgboost.ai/t/performance-changes-between-1-2-1-and-1-3-1

Thank you for investigating!

**Comment by hcho3** [comment] 2021-03-16 23:35
I had a chance to dive into this bug. Git bisect reveals that the following commit had introduced the performance regression:

f779980f7ea7f6f07e86229b8e78144e8a74e6b3
```
    gpu_hist performance tweaks (#5707)
    
    * Remove device vectors
    
    * Remove allreduce synchronize
    
    * Remove double buffer
```

**Comment by RAMitchell** [comment] 2021-03-17 00:08
I wonder if simply adding the allreduce back solves the problem?

**Comment by hcho3** [comment] 2021-03-17 04:58
Hello everyone,  #6757 will fix the slow training performance in gpu_hist. It does not reduce the memory consumption of `ParallelGroupBuilder`; it will be addressed in another pull request.

**Comment by trivialfis** [comment] 2021-03-18 21:00
Thanks for investigating @hcho3 !  I'm reopening as not fully fixed yet.  Hopefully we can come up with a solution for the mem use

**Comment by hcho3** [comment] 2021-03-18 22:20
@trivialfis Hi, I found out that setting the default `nthread` to 1 reduces the memory consumption to the level of 1.1.0. #5877 changed the default `nthread` from 1 to -1 (all threads):
https://github.com/dmlc/xgboost/commit/24f2e6c97eb8c9562ec3ea7218fcb9b795315d80#diff-a4ce908f1993b97eed5270a86e89c56a0580db80dcfb21e51c3e38a4aae9a3c2L425

I tried changing -1 back to 1 and the memory consumption goes down.

* `nthread=1`: 40.32 GB peak
* `nthread=-1`: 57.45 GB peak

**Comment by ShvetsKS** [comment] 2021-03-19 04:48
@hcho3 Disabling threading in DMatrix create by default is not good solution as we can mitigate it in another way.
There is already solution for Dense adapter (unfortunately reverted): https://github.com/dmlc/xgboost/commit/bdebab195d8ab6b3f0104b7ed6132ee7585f8d40
With this fix it's possible to get similar to `nthread=1` memory consumption.

**Comment by trivialfis** [comment] 2021-03-23 02:48
@ShvetsKS Do you know any sparse matrix transpose algorithm that doesn't have `O(NT)` runtime memory requirement, with `N` as rows and `T` as threads?

**Comment by trivialfis** [comment] 2021-03-23 03:03
I will try some different solutions.

**Comment by hcho3** [comment] 2021-03-23 03:07
For the upcoming release (1.4.0), let's document this as a known issue, as the true fix may take a while to achieve.

Known limitation: the DMatrix construction may cause a high amount of memory consumption. If your machine is constrained in the amount of memory available, please set `nthread=1`.

**Comment by trivialfis** [comment] 2021-03-23 12:08
> the true fix may take a while to achieve.

Didn't think parallel transpose is such a difficult problem.  I couldn't find an algorithm that's close to ideal.  Sorting-based can be quite efficient for sparse data but performs poorly on dense data due to its complexity.  Atomic-based also performs poorly on dense data.  Scan-based (what we are currently employing) has `O(NT)` memory consumption and merge-based is no better.

The fix from @ShvetsKS specializes on dense matrix and also applicable to only `hist` since the `SparsePage::Transpose` also uses the parallel transpose and likely to consume as much memory as the current DMatrix construction.

I'm quite reluctant to let this bug slip into the next release since I also need to change the default thread for dask.

**Comment by ShvetsKS** [comment] 2021-03-23 13:44
@trivialfis What if we still preserve default `-1` value for dispatched `_from_numpy_array` (always calls with `DenseAdapter`) as for this branch we are still able to reduce memory consumption `nthread` times (result: O(N/T) for each thread) ? Seems that this approach for memory reduction can be applied for each Adapters with row-oriented memory.

For columnar-oriented storage (`CSCAdapter` ?) we could at least have threading by columns for `AddBudget` calls to calculate number of not missing and not nans elements. And it would require O(nColumns/nThreads) memory consumption.

**Note**: For CSCAdapter https://github.com/dmlc/xgboost/blob/master/src/c_api/c_api.cc#L273 `nthread` is equal to `1` already and it doesn't depend on `nthread` value.

**Comment by trivialfis** [comment] 2021-03-23 14:06
@ShvetsKS

> What if we still preserve default -1 value for dispatched _from_numpy_array (always calls with DenseAdapter)

Setting the default to -1 means some automated value right?  We will still have to pick the correct value for `omp_set_num_threads`?  Or we just bypass this call when input number of threads is invalid and let the system decide?

**Comment by ShvetsKS** [comment] 2021-03-23 14:10
No. Just allow lazy `self.nthread` initialization in `dispatch_data_backend`
https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/core.py#L538
It allows to preserve user defined value if it's different from `None`

**Comment by trivialfis** [comment] 2021-03-23 14:14
The `-1` is preserved and passed down to `SimpleDMatrix` where we call `common::OmpSetNumThreadsWithoutHT`, which then uses `omp_get_max_threads()` due to `-1` being an invalid value.  From here on we are using the maximum number of threads.  I'm not sure how lazy initialization for `DMatrix.nthread` can be applied here?  Sorry for not catching up.

**Comment by ShvetsKS** [comment] 2021-03-23 14:40
Sorry for not clear description.
If we change default value from `-1` to `1` [here](https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/core.py#L528) it would not be possible to distinguish `1` was provided by user or by default settings. That's why I propose to keep `-1` value if `nthread is None` and call `XGDMatrixCreateFromMat_omp`  to preserve threading construction for  this case (seems lazy initialization is redundant here).

So propagation of `-1` value right to the call `common::OmpSetNumThreadsWithoutHT` is exactly I propose for `DenseAdapterBatch` (original value is reverted [here](https://github.com/dmlc/xgboost/blob/master/src/data/simple_dmatrix.cc#L187)).
It will be possible only if we reduce memory consumption (right to `O(N/T)`) of course.

**Comment by trivialfis** [comment] 2021-03-23 15:02
> If we change default value from -1 to 1 here it would not be possible to distinguish 1 was provided by user or by default settings. 

Okay, we keep it as -1.

> It will be possible only if we reduce memory consumption (right to O(N/T)) of course.

Yes, that will be the cost per-thread.

> So propagation of -1 value right to the call common::OmpSetNumThreadsWithoutHT is exactly I propose for DenseAdapterBatch 

So are you suggesting that we change this internally instead of changing it in the interface parameter?  If so then I fully agree. ;-)

> I don't see any reasons to disable threading for DenseAdapterBatch by default, sorry.

Any chance your previous fix can be generalized to all row-major formats?

**Comment by trivialfis** [comment] 2021-03-23 15:03
> Any chance your previous fix can be generalized to all row-major formats?

If your assessment is that's doable I would like to help (by contributing to your code branch and review etc).

**Comment by trivialfis** [comment] 2021-03-23 15:40
For now I will put a temp fix by changing internal number of threads inside DMatrix.

**Comment by ShvetsKS** [comment] 2021-03-23 15:43
> Any chance your previous fix can be generalized to all row-major formats?
I suppose so and try to generalize it.

**Comment by trivialfis** [comment] 2021-03-23 15:45
I'm hoping to get a release candidate this week.  But we can still backport before final release, or use patch release, so no strict timeframe.

**Comment by trivialfis** [comment] 2021-03-26 00:44
Closed by https://github.com/dmlc/xgboost/pull/6779 .

**Comment by IvanUkhov** [comment] 2021-06-05 10:24
Does everybody perceive it as a solved issue? I currently alternate between 1.2.4 and 1.4.2 with everything else held constant, and while the former successfully finishes in reasonable time, the latter does not seem to be able to do so: it just keeps the machine indefinitely busy.

**Comment by trivialfis** [comment] 2021-06-05 10:35
@IvanUkhov Could you please open a new issue?  This particular one is resolved since we reduced the memory usage down by https://github.com/dmlc/xgboost/pull/6779

**Comment by IvanUkhov** [comment] 2021-06-05 16:48
I think I have figured it out. It was in the context of `GridSearchCV(n_jobs=-1)`. It turns out XGBoost sets `nthreads` to the maximum value if unset, which was the case in my case. So both were working against each other. Not sure how it was working up till 1.2.1. Maybe the default has changed.

**Comment by erensahin** [comment] 2021-06-17 14:46
I had faced a similar issue as I migrate from 0.90 to 1.x when I use a validation set through eval_set parameter of fit method in sklearn API. The training did not end at all and all CPUs were %100 used.

So, I figured out that default value of n_jobs parameter was 1 in 0.90 and None in 1.x. Setting n_jobs=1 back solved my problem. 

Hope this helps.

**Comment by ArsalShakil** [comment] 2021-06-18 11:37
I was previously using 0.81 and now using 1.4.2. Even though the dataset/parameters are exactly same and all cores are used 100%, 0.81 version took an hour for training while 1.4.2 version is taking 12+ hours... I've checked everything, not sure what's causing this.

**Comment by trivialfis** [comment] 2021-06-18 11:59
Could you please share your parameters?

**Comment by ArsalShakil** [comment] 2021-06-18 12:03
{'eta': 0.2, 'n_estimators': 1000, 'lambda': 0.57, 'max_depth': 8, 'min_child_weight': 3, 'gamma': 2.69, 'subsample': 0.8, 'colsample_bytree': 0.8, 'silent': 1, 'eval_metric': 'auc','objective': 'binary:logistic', 'tree_method': 'hist', 'grow_policy': 'lossguide',
'n_jobs': 60,'random_state': 0}

Btw, I'm training on CPU.

**Comment by trivialfis** [comment] 2021-06-18 12:12
@ShvetsKS Could you please take a look at the perf difference.

Also @ArsalShakil could you please share the shape and sparsity of your data set?  Or you using scikit learn grid search?

**Comment by ArsalShakil** [comment] 2021-06-18 12:32
The dataset is about 16mil x 87 and sparsity is 0.23. I'm using simple xgb.train(params, dmatrix, num_rounds) without any evalset.

**Comment by trivialfis** [comment] 2021-06-18 12:41
Thank you for the details!   So evaluation metic AUC is not a factor here, what remains are DMatrix, hist and objective.  @ShvetsKS do you have any insight?

**Comment by ShvetsKS** [comment] 2021-06-18 16:04
> Thank you for the details! So evaluation metic AUC is not a factor here, what remains are DMatrix, hist and objective. @ShvetsKS do you have any insight?

It's interesting. I didn't noticed any degradations between 0.81 and 1.4.0 on similar dimensions.

@trivialfis seems DMatrix create is not the reason of perf degradations as DMatrix is already created before  `xgb.train(params, dmatrix, num_rounds)` (not sklearn api is used).

@ArsalShakil  It would be great to have some full reproducer, otherwise can I use just `sklearn.datasets.make_classification` as such huge degradation should be also reproduced on dense dataset.

**Comment by ArsalShakil** [comment] 2021-06-18 17:01
@ShvetsKS Yeah `sklearn.datasets.make_classification` should work just fine for reproducibility. I'll prep a full reproducer and share it.

**Comment by ArsalShakil** [comment] 2021-06-21 05:00
@ShvetsKS @trivialfis Thanks a lot guys! The issue is resolved, it was an issue at training pipeline's end. I however had tested with the following code too:

```
import xgboost as xgb
from datetime import datetime
from sklearn.datasets import make_classification
import numpy as np

params = {'eta': 0.2, 'n_estimators': 1000, 'lambda': 0.57, 'max_depth': 8, 'min_child_weight': 3, 'gamma': 2.69, 'subsample': 0.8, 'colsample_bytree': 0.8, 'silent': 1, 'eval_metric': 'auc','objective': 'binary:logistic', 'tree_method': 'hist', 'grow_policy': 'lossguide',
'n_jobs': 60,'random_state': 0}

make_classification_start = datetime.now()
X, Y = make_classification(n_samples=16000000, n_features=87, n_redundant=5, n_informative=4,n_clusters_per_class=2, weights=[0.83,0.17], random_state=0)
params['scale_pos_weight'] = np.sqrt(1. * (len(Y)-sum(Y)) / sum(Y))
print ("Time taken for data creation: {}".format(datetime.now() - make_classification_start))

print ("\nParameters: \n{}".format(params))

dmatrix_start = datetime.now()
dmatrix = xgb.DMatrix(X, label=Y, silent=True, nthread=60)
print('\nTime taken for DMatrix loading: {}'.format(datetime.now() - dmatrix_start))

train_start = datetime.now()
xgb_mod = xgb.train(params, dmatrix, num_boost_round=params['n_estimators'], verbose_eval=False)
print('\nTime taken for training: {}'.format(datetime.now() - train_start))
```
0.81 version's output:
```
Time taken for data creation: 0:02:29.842816

Parameters: 
{'n_jobs': 60, 'eval_metric': 'auc', 'scale_pos_weight': 2.18400229150214, 'random_state': 0, 'n_estimators': 1000, 'tree_method': 'hist', 'colsample_bytree': 0.8, 'silent': 1, 'grow_policy': 'lossguide', 'min_c
hild_weight': 3, 'subsample': 0.8, 'eta': 0.2, 'objective': 'binary:logistic', 'max_depth': 8, 'gamma': 2.69, 'lambda': 0.57}

Time taken for DMatrix loading: 0:00:08.687441

Time taken for training: 0:43:23.475236
```
1.4.0 version's output:
```
Time taken for data creation: 0:02:51.377007

Parameters: 
{'eta': 0.2, 'n_estimators': 1000, 'lambda': 0.57, 'max_depth': 8, 'min_child_weight': 3, 'gamma': 2.69, 'subsample': 0.8, 'colsample_bytree': 0.8, 'silent': 1, 'eval_metric': 'auc', 'objective': 'binary:logistic', 'tree_method': 'hist', 'gr
ow_policy': 'lossguide', 'n_jobs': 60, 'random_state': 0, 'scale_pos_weight': 2.18400229150214}

Time taken for DMatrix loading: 0:00:10.915084

Time taken for training: 0:21:20.060458
```

**Closed** 2021-07-15 03:49 UTC
Labels: type: bug
