### ISSUE TITLE
OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized.

### ISSUE THREAD

**Issue by symPhysics** [dmlc/xgboost#1715] opened 2016-10-28 04:56 UTC
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.
## Environment info

Operating System: Mac OSX Sierra 10.12.1

Compiler:

Package used (python):

`xgboost` version used: xgboost 0.6a2

If you are using python package, please provide
1. The python version and distribution: 
   Pythong 2.7.12
2. The command to install `xgboost` if you are not installing from source
   pip install xgboost
## Steps to reproduce
1.  from xgboost import XGBClassifier
    import numpy as np
    import matplotlib.pyplot as plt
    x = np.array([[1,2],[3,4]])
    y = np.array([0,1])
    clf = XGBClassifier(base_score = 0.005)
    clf.fit(x,y)
    plt.hist(clf.feature_importances_)
   ## What have you tried?
   
   See the error message:
    "OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized.
   OMP: Hint: This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/."

I tried:
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

It can do the job for me. But it is kind of ugly.

---

I know it might be not the problem of xgboost, but I'm pretty sure this problem happened after I upgrade xgboost using 'pip install xgboost'.    I post the issue here to see if someone had the same problem as me.  I have very little knowledge about OpenMP.  Please help!  
Thanks in advance!

**Comment by staubda** [comment] 2016-11-09 21:15
I'm having the same issue when I try to use both xgboost and matplotlib.

OS X 10.10.5
Python 2.7.12
xgboost 0.6
matplotlib 1.5.1

**Comment by jimthompson5802** [comment] 2017-03-25 23:18
I've encountered the same problem with xgboost and matplotlib.  Same symptom...kernel dies with the same error message as reported by @symPhysics 

Mac OS X 10.12.3

Python 3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin

xgboost 0.6a2

matplotlib 2.0.0

**Comment by jimthompson5802** [comment] 2017-03-26 03:25
FWIW...this seems to be a MacOS specific problem.  I was not able to recreate the problem on a CentOS Linux VM.

**Comment by ilovejs** [comment] 2017-07-06 06:30
At least for Mac, 

`brew uninstall libiomp clang-omp`

as long as u got gcc v5 from brew it come with openmp

follow steps in:
https://github.com/dmlc/xgboost/tree/master/python-package

**Comment by deltaoui** [comment] 2018-09-11 15:01
I tried this and the error stopped !

import os

os.environ['KMP_DUPLICATE_LIB_OK']='True'

**Comment by JamieGainer** [comment] 2018-09-24 04:06
For me the issue (on a Mac) was fixed with 
pip uninstall xgboost
followed by 
pip install xgboost

**Comment by Toooodd** [comment] 2018-11-09 09:02
> I tried this and the error stopped !
> 
> import os
> 
> os.environ['KMP_DUPLICATE_LIB_OK']='True'

thanks, it works!!!

**Comment by gpetty** [comment] 2018-11-15 05:42
I had the same error on my Mac with a python program using numpy, keras, and matplotlib.  I solved it with 'conda install nomkl'.

**Comment by willsnowdev** [comment] 2018-11-17 03:37
> I had the same error on my Mac with a python program using numpy, keras, and matplotlib. I solved it with 'conda install nomkl'.

thanks a lot, it works.

**Comment by csuagui** [comment] 2018-11-25 16:04
> I had the same error on my Mac with a python program using numpy, keras, and matplotlib. I solved it with 'conda install nomkl'.

Thanks too, it works for me too.

**Comment by AlamiSimo** [comment] 2018-11-27 23:50
@gpetty  You sir are a true hero. Thank you!

**Comment by EDODz** [comment] 2018-11-28 07:36
@gpetty It works! THANKSSS :))

**Comment by christabella** [comment] 2018-11-30 07:37
Strangely `conda install nomkl` didn't work for me (don't have `libiomp clang-omp` installed on Brew either), only 
```import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
```
could work

**Comment by SumNeuron** [comment] 2018-11-30 20:10
```
brew uninstall libiomp clang-omp

Error: No such keg: /usr/local/Cellar/libiomp
```

**Comment by kangkang59812** [comment] 2018-12-03 14:48
> I had the same error on my Mac with a python program using numpy, keras, and matplotlib. I solved it with 'conda install nomkl'.

thanks a lot, even though i dont know what is nomkl. It confused me a few days when i run a CNN-RNN model using tensorflow.When i used os.environ['KMP_DUPLICATE_LIB_OK']='True' , it worked, but the program run so slow.You got the right ans.

**Comment by Bjvanminnen** [comment] 2018-12-07 00:08
My issues were completely unrelated to xgboost, but I got here via google so that I'd share for the sake of others.

I am using keras and matplotlib installed via conda. Setting `KMP_DUPLICATE_LIB_OK` just changed my experience from a warning to an exception/crash.  Install `nomkl` didn't change anything for me. Eventually I downgraded my version of matplotlib and that fixed things for me
`conda install matplotlib=2.2.3`

**Comment by esvhd** [comment] 2018-12-22 21:41
For people googling this error, the best solution that I found is listed [here](https://blog.csdn.net/Jimmyzqb/article/details/83017650). 

The site lists two method. I prefer method 1, which is to go into your `anaconda3/lib` directory and remove the old `libiomp5.dylib` file. Nice and simple.

**Comment by leong1016** [comment] 2018-12-29 19:10
> For people googling this error, the best solution that I found is listed [here](https://blog.csdn.net/Jimmyzqb/article/details/83017650).
> 
> The site lists two method. I prefer method 1, which is to go into your `anaconda3/lib` directory and remove the old `libiomp5.dylib` file. Nice and simple.

Please be really careful if you want to try method 1. Everything crashed after I deleted the file and I have to reinstall openmp. Same problem reported in the original csdn link (in Chinese).

**Comment by Cuica20** [comment] 2018-12-30 00:46
Thanks!!
For me on MAC:
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

**Comment by sam1902** [comment] 2019-01-02 13:49
Had the same problem after switching from homebrew/virtualenv installed numpy/keras/matplotlib/tensorflow to miniconda installed. Solved by running `conda install nomkl` though I reckon keras (and numpy) wont run as fast as they could if they don't make use of Intel's Math Kernel Lib but at least my code still run so ¯\_(ツ)_/¯

**Comment by jms-dipadua** [comment] 2019-01-08 19:35
@sam1902 that worked for me too -- updating the os.environ variable did not. thanks!

**Comment by TVI-BIZ** [comment] 2019-01-13 17:42
have same issue on my Mac
Just run -  conda update -n base conda
it install and update needed dependences

**Comment by wangcj05** [comment] 2019-01-15 23:30
Got the same issue on my mac, tried suggested method and it works
```
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
```

**Comment by mfansler** [comment] 2019-01-20 01:53
> I tried this and the error stopped !
> 
> import os
> 
> os.environ['KMP_DUPLICATE_LIB_OK']='True'

It should be noted that this is **strongly discouraged by the OpenMP devs**.  From their error message:

> The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable `KMP_DUPLICATE_LIB_OK=TRUE` to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results.

**Comment by georgeu2000** [comment] 2019-02-17 02:19
`conda install nomkl` worked for me. 

Can anyone explain what this does and why it fixes the problem?

**Comment by jscriptcoder** [comment] 2019-02-17 21:27
@georgeu2000, I'm wondering about the same. It did also fix the problem for me. I'm using Numpy, Matplotlib, Keras and Tensorflow as backend. I don't seem to understand what that package does. Anyone could explain?

Thanks a lot.

**Comment by trivialfis** [comment] 2019-02-17 21:36
I saw some benchmarks between openblas and mkl before, mkl is not superior.  Is there any reason for using mkl over openblas?  Explaining something without the source code at hand is not very motivating.

**Comment by lvwarren** [comment] 2019-02-21 09:17
> conda install nomkl
works but it has to downgrade:
<pre>
  mkl_fft                             1.0.10-py36h5e564d8_0 --> 1.0.1-py36h917ab60_0
  mkl_random                           1.0.2-py36h27c97d8_0 --> 1.0.1-py36h78cc56f_0
  numexpr                              2.6.9-py36h7413580_0 --> 2.6.9-py36hafae301_0
  numpy                               1.15.4-py36hacdab7b_0 --> 1.15.4-py36h926163e_0
  numpy-base                          1.15.4-py36h6575580_0 --> 1.15.4-py36ha711998_0
  scikit-learn                        0.20.2-py36h27c97d8_0 --> 0.20.2-py36hebd9d1a_0
  scipy                                1.2.1-py36h1410ff5_0 --> 1.2.1-py36h1a1e112_0
</pre>

**Comment by ZhuoerLyu** [comment] 2019-03-09 04:10
> My issues were completely unrelated to xgboost, but I got here via google so that I'd share for the sake of others.
> 
> I am using keras and matplotlib installed via conda. Setting `KMP_DUPLICATE_LIB_OK` just changed my experience from a warning to an exception/crash. Install `nomkl` didn't change anything for me. Eventually I downgraded my version of matplotlib and that fixed things for me
> `conda install matplotlib=2.2.3`

Hey buddy, you saved my ass

**Comment by gitjonez** [comment] 2019-03-21 21:56
> Had the same problem after switching from homebrew/virtualenv installed numpy/keras/matplotlib/tensorflow to miniconda installed. Solved by running `conda install nomkl` though I reckon keras (and numpy) wont run as fast as they could if they don't make use of Intel's Math Kernel Lib but at least my code still run so ¯\_(ツ)_/¯

^^^^   This is what did the trick for me. Thanks!

**Comment by Isaac009** [comment] 2019-04-03 06:56
> Thanks!!
> For me on MAC:
> import os
> os.environ['KMP_DUPLICATE_LIB_OK']='True'

WORKS FOR ME THANKS

**Comment by jolespin** [comment] 2019-04-16 17:31
In my conda `lib`, I have multiple `libgomp`:

I got the expected error: 
```
OMP: Error #15: Initializing libiomp5.dylib, but found libomp.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
```
This definitely helps:
```
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
```
Here are all of my versions:
```
(µ_env) jespinozlt-osx:lib jespinoz$ ls -lhtr | grep "omp"
-rwxr-xr-x    1 jespinoz  tigr    62K Oct 28  2016 libgomp.1.dylib
-rwxr-xr-x    1 jespinoz  tigr   110K Aug 11  2017 libiompstubs5.dylib
-rwxr-xr-x    1 jespinoz  tigr   1.3M Aug 11  2017 libiomp5.dylib
lrwxr-xr-x    1 jespinoz  tigr    15B Feb 23  2018 libgomp.dylib -> libgomp.1.dylib
```

Should I just remove one of them? If so, should I keep `libiomp5.dylib` instead of `libgomp.1.dylib` and just symlink?

**Comment by yangzhou95** [comment] 2019-05-02 20:05
# OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized.

## OMP: Hint: This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

**Comment by hzitoun** [comment] 2019-05-12 13:36
> I tried this and the error stopped !
> 
> import os
> 
> os.environ['KMP_DUPLICATE_LIB_OK']='True'

Does fix the problem. Thanks

**Comment by binkod2000** [comment] 2019-05-30 01:32
I ran into this problem on a fresh install of anaconda on an a brand new Mac book pro in Anaconda trying to use tensor-flow and keras. I used. 'conda update --all' and it fixed the problem.

**Comment by preet1881** [comment] 2019-06-13 07:38
> ```
> brew uninstall libiomp clang-omp
> 
> Error: No such keg: /usr/local/Cellar/libiomp
> ```
i have the same error how did you solve it , and conda insatll nomkl is not working either 
its giving the error
UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: torch
  channel url: https://conda.anaconda.org/torch
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.

**Comment by hxuaj** [comment] 2019-07-07 15:09
I ran into the same problem and I used keras, numpy and tf 1.14.
```conda install nomkl``` dose solve my problem! Thank you.

> I had the same error on my Mac with a python program using numpy, keras, and matplotlib. I solved it with 'conda install nomkl'.

**Comment by hxuaj** [comment] 2019-07-07 15:12
> I had the same error on my Mac with a python program using numpy, keras, and matplotlib. I solved it with 'conda install nomkl'.

I ran into the same problem and I use keras, numpy and tensorflow 1.14.
```conda install nomkl``` does solve my problem! Thank you @gpetty

**Comment by sameershmedianet** [comment] 2019-07-10 08:17
> I had the same error on my Mac with a python program using numpy, keras, and matplotlib. I solved it with 
'conda install nomkl'.

This worked for me as well. I was getting error while running LightGBM package, it was erroring out after a certain number of rows or certain number of features. 

I'm guessing it has something to do with memory usage or parallelising process. it would be great if someone can explain what exactly 'libomp' does and why 'nomkl' solves it. Thanks.

**Comment by ppmdatix** [comment] 2019-07-23 13:52
> Strangely `conda install nomkl` didn't work for me (don't have `libiomp clang-omp` installed on Brew either), only
> 
> ```
> os.environ['KMP_DUPLICATE_LIB_OK']='True'
> ```
> 
> could work

Hello
Same for me but
`conda install -c anaconda nomkl`
worked for me
Hope it helps

**Comment by hoveidar** [comment] 2019-08-02 20:51
Hey all,

although using `os.environ['KMP_DUPLICATE_LIB_OK']='True'` is absolutely frowned upon, but eventually, I had to use it cause `conda install -c anaconda nomkl` didn't work for me. Any other ideas?

**Comment by mayhuifu** [comment] 2019-09-20 03:42
use the os.environ['KMP_DUPLICATE_LIB_OK']='True' works but was not recommended. use Conda install nomkl looks running endless, has to kill it. use conda update -n base Conda works and it updated the lib

**Comment by LangziXing** [comment] 2019-11-05 08:51
> I tried this and the error stopped !
> 
> import os
> 
> os.environ['KMP_DUPLICATE_LIB_OK']='True'

Thank you very much! It works for me!

**Comment by JackGuoFranklin** [comment] 2019-11-07 13:43
import os

os.environ['KMP_DUPLICATE_LIB_OK']='True'

it  works for me,thank you .

**Comment by MakeWater** [comment] 2019-11-20 01:22
> I had the same error on my Mac with a python program using numpy, keras, and matplotlib. I solved it with 'conda install nomkl'.

Thanks Bro！ It worked for me!

**Comment by MakeWater** [comment] 2019-11-20 01:25
> > I had the same error on my Mac with a python program using numpy, keras, and matplotlib. I solved it with 'conda install nomkl'.
> 
> Thanks Bro！ It worked for me!

I just test tensorflow object_detection API  and run the object_detection_tutorial.ipynb file

**Comment by trypythy** [comment] 2019-12-26 04:49
i'm on a 2010 MBP, running the python(3.7) file on anaconda; so I guess it was something to do with my 'old' system - i have no clue on what territories i'm treading here - tried uninstalling xgboost, realised it's not installed, tried installing it, it just got stuck;  tried conda install nomkl, and then my python script itself wouldn't run (`illegal instruction: 4`); uninstalled nomkl; finally worked when i used 

```
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
```
i still don't know how and why it worked, but hey, it works now

**Comment by sharonwoo** [comment] 2020-01-20 06:59
Thanks for this; ```conda update --all``` was what worked for me. Running Mac OS Mojave with Python 3.7 Anaconda (not the new install... dates from last year).

**Comment by trivialfis** [comment] 2020-01-20 07:22
Reopening, if someone has any insight to the issue, please share.

**Comment by CarcajadaArtificial** [comment] 2020-02-06 23:43
> We can close this issue now.

LMAO

**Comment by Bue-von-hon** [comment] 2020-02-14 05:36
> I tried this and the error stopped !
> 
> import os
> 
> os.environ['KMP_DUPLICATE_LIB_OK']='True'

it works for me thx

**Comment by 1ps0** [comment] 2020-02-16 20:33
For me, this combination worked:
```
brew uninstall libiomp clamp-omp
conda uninstall intel-openmp -n base
conda install -c intel openmp -n myenv
conda install nomkl -n myenv
```
The primary conflict came from the `brew` `libiomp` but then later conflicts with the `conda` `base` env and my `python 3.7` env over `openmp` sent me in circles until i sorted out the dependency chain/fallback. The channel source distinction made a huge difference.

**Comment by j4m3sb0nd007** [comment] 2020-02-17 12:30
> I tried this and the error stopped !
> 
> import os
> 
> os.environ['KMP_DUPLICATE_LIB_OK']='True'

It works for me too

**Comment by cheetah90** [comment] 2020-03-19 05:30
> I had the same error on my Mac with a python program using numpy, keras, and matplotlib. I solved it with 'conda install nomkl'.

Thanks! It works for me as of today! Can anyone explain why this works?

**Comment by hcho3** [comment] 2020-06-18 06:14
We now provide a binary wheel for Mac OSX, which links to `/usr/local/lib/libomp.dylib`. Install XGBoost by running
```
python -m pip install xgboost
```

**Closed by hcho3** 2020-06-18 06:14 UTC

**Comment by apneaHomosapiens** [comment] 2020-07-19 03:50
Thank you this solved my case. My Mac did not have libiomp and clamp-omp, and I did not install nomkl.
So I only do these two steps.
```
conda uninstall intel-openmp
conda install -c intel openmp
```

> For me, this combination worked:
> 
> ```
> brew uninstall libiomp clamp-omp
> conda uninstall intel-openmp -n base
> conda install -c intel openmp -n myenv
> conda install nomkl -n myenv
> ```
> 
> The primary conflict came from the `brew` `libiomp` but then later conflicts with the `conda` `base` env and my `python 3.7` env over `openmp` sent me in circles until i sorted out the dependency chain/fallback. The channel source distinction made a huge difference.

**Comment by xbiggyl** [comment] 2020-07-22 12:09
(macOS Catalina 10.15.5)

Going through the installed package in my env, I noticed that there was an update for mkl.

So I was able to solve my case by updating mkl.


`conda install -c intel mkl`

**Comment by chegini** [comment] 2020-08-13 06:54
you can do ``conda install nomkl`

**Comment by caffett** [comment] 2020-08-25 03:15
> I had the same error on my Mac with a python program using numpy, keras, and matplotlib. I solved it with 'conda install nomkl'.

What is the magic behind this?

**Comment by CatNofishing** [comment] 2020-09-09 11:05
I had the same error on my window10.

**Comment by vickykhan89** [comment] 2020-10-09 06:35
os.environ['KMP_DUPLICATE_LIB_OK']='True', I tried this command and the problem solve thanks to @Toooodd

**Comment by sjoerdvansteenkiste** [comment] 2020-10-13 14:13
I found an alternative solution to this problem [here](https://docs.openvinotoolkit.org/2018_R5/_docs_MO_DG_Known_Issues_Limitations.html), which is to preload the OpenMP runtime using the `LD_PRELOAD` variable:

```
LD_PRELOAD=<path_to_libiomp5.so> <path_to your_executable>
```

This eliminates multiple loadings of libiomp, and makes all the components use this specific version of OpenMP.

**Comment by powarvinayak** [comment] 2020-10-14 09:24
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

Followed by 

> conda install nomkl

Worked for me. Thanks!

**Comment by octoviaa** [comment] 2021-02-22 13:36
> (macOS Catalina 10.15.5)
> 
> Going through the installed package in my env, I noticed that there was an update for mkl.
> 
> So I was able to solve my case by updating mkl.
> 
> `conda install -c intel mkl`

This works for me (macOS Big Sur)

**Comment by daveloui** [comment] 2021-05-09 01:20
> I had the same error on my Mac with a python program using numpy, keras, and matplotlib. I solved it with 'conda install nomkl'.

Thanks so much @gpetty !! You're a life saver! :D

**Comment by WissenY** [comment] 2021-05-13 17:31
> For people googling this error, the best solution that I found is listed [here](https://blog.csdn.net/Jimmyzqb/article/details/83017650).
> 
> The site lists two method. I prefer method 1, which is to go into your `anaconda3/lib` directory and remove the old `libiomp5.dylib` file. Nice and simple.

For me, it works! But the file I removed is a little different from yours which is `libiomp5md.dll` in the path  of `C:\Users\***\Anaconda3\Library\bin`. I think it may caused by installing full package of pytorch by me after installing anaconda. So the better way is to use miniconda or install pytorch by `conda install torch torchvision torchaudio`

**Comment by chestergan** [comment] 2021-05-22 08:55
> I had the same error on my Mac with a python program using numpy, keras, and matplotlib. I solved it with 'conda install nomkl'.

Legend!

**Comment by Sophal24** [comment] 2022-02-19 11:10
On Mac M1, **conda install nomkl** works. 
But if it doesn't work for the first time, you should uninstall and install that command again.

**Comment by changhyeonnam** [comment] 2022-06-20 04:43
> 
This works for me. Thanks!.

**Comment by changhyeonnam** [comment] 2022-06-20 04:43
> On Mac M1, `conda install nomkl` works. But if it doesn't work for the first time, you should _uninstall_ and _install_ that command again.
> 
> Above didn't fix my issue after update mac os version ❌
> 
> these 2 works:
> 
> ```
> conda uninstall intel-openmp
> conda install -c intel openmp
> ```

This works for my intel-Mac too!. Thanks alot!

**Comment by ckgresla** [comment] 2022-07-26 18:50
Uninstalling and Reinstalling `intel-openmp` within the Conda Env solved the issue on my Intel Based MacBook

**Comment by M-Parvini** [comment] 2022-08-15 15:17
Thanks

**Comment by OtistarSun** [comment] 2022-09-23 11:12
> WissenY

it works, thank u

**Comment by teppotk** [comment] 2023-05-09 13:29
Umm, because the `conda install nomkl` doesn't work on M1 for me, is the correct full process on M1:

'conda uninstall intel-openmp
conda install -c intel openmp
conda install nomkl'

?

Actually I ran all those 3 and now nothing works. :) I'm actually trying to run AutoGPT on M1, when all the original libiomp5.dylib problem came up.

> > On Mac M1, `conda install nomkl` works. But if it doesn't work for the first time, you should _uninstall_ and _install_ that command again.
> > Above didn't fix my issue after update mac os version ❌
> > these 2 works:
> > ```
> > conda uninstall intel-openmp
> > conda install -c intel openmp
> > ```
> 
> This works for my intel-Mac!. Thanks alot!

**Comment by Jeremy-Niu** [comment] 2023-05-23 16:43
My solution is 
```
conda uninstall intel-openmp
conda install nomkl
```
It seems to work well!
Due to package conflicts, I did not do `conda install -c intel openmp`.  My mbp is intel-mac with os 13.3.1.

**Comment by chen0143** [comment] 2023-06-30 08:16
I met the same error(not with xgboost though), and I fix it by change
```python
import numpy 
import torch
```
to 
```python
import torch
import numpy
```

it seems that import numpy later would solve this problem. But I don't understand why this bug would be fixed in this way .

**Comment by mr-fallen-angel** [comment] 2023-07-03 19:59
> I tried this and the error stopped !
> 
> import os
> 
> os.environ['KMP_DUPLICATE_LIB_OK']='True'

it doesnt seem to help for macOS

**Comment by an-1024** [comment] 2023-12-26 06:46
> I tried this and the error stopped !
> 
> import os
> 
> os.environ['KMP_DUPLICATE_LIB_OK']='True'

It work. Thank You.

**Comment by Viditagarwal7479** [comment] 2024-03-14 18:45
>  I tried this and the error stopped !
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

[MacOS]
This was program termination due to segmentation fault.
Through conda I reinstalled pytorch and then also reinstalled torchvision this fixed the issue for me.

**Comment by DomizianoScarcelli** [comment] 2024-03-19 09:23
> > I tried this and the error stopped !
> > import os
> > os.environ['KMP_DUPLICATE_LIB_OK']='True'
> 
> [MacOS] This was program termination due to segmentation fault. Through conda I reinstalled pytorch and then also reinstalled torchvision this fixed the issue for me.

This worked for me!

**Comment by AugustNilsson** [comment] 2024-10-21 08:06
Have people got problems with this solution?

> I tried this and the error stopped !
> 
> import os
> 
> os.environ['KMP_DUPLICATE_LIB_OK']='True'

It is quite explicitly not recommended
From the original post: 
"As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results."
