### ISSUE TITLE
BUG: Predict errors out if feature matrix only has boolean columns (python)

### ISSUE THREAD

**Issue by freddyaboulton** [dmlc/xgboost#7157] opened 2021-08-05 22:33 UTC
```python
import xgboost
import pandas as pd
import pytest
import sklearn

print(sklearn.__version__)
print(xgboost.__version__)
print(pd.__version__)
```
```
0.24.2
1.4.2
1.3.1
```

```python
X = pd.DataFrame({"a": [True, False, True],
                  "b": [True, False, True]})
y = pd.Series([True, False, False])
xgb = xgboost.XGBClassifier()
xgb.fit(X, y)

with pytest.raises(Exception, match="Boolean is not supported."):
    xgb.predict_proba(X)
    
with pytest.raises(Exception, match="Boolean is not supported."):
    xgb.predict(X)
```

This error does not happen for version 1.3.3 so I'm wondering why the change of behavior has occurred. It's also curious that fit does not throw an error - only the predict methods do. Is it possible to restore the old behavior?

Thank you!

**Comment by trivialfis** [comment] 2021-08-06 03:09
That's caused by the inplace predict.  We used to convert the boolean value into float and make a CSR copy by DMatrix.  Now the scikit-learn interface will use inplace predict directly so no conversion is performed.  I will fix it by falling back to the old method.  Thanks for raising the issue.

**Comment by trivialfis** [comment] 2021-08-11 08:57
This is now fixed in master branch without creating a CSR matrix.  Will be included in the next release.

**Closed by trivialfis** 2021-08-11 08:57 UTC

**Comment by freddyaboulton** [comment] 2021-08-11 14:26
Thank you @trivialfis !
