### ISSUE TITLE
AssertError:read can not have position excceed buffer length.

### ISSUE THREAD

**Issue by wangfengchao** [dmlc/xgboost#5958] opened 2020-07-30 06:20 UTC
1. Why is Java API 1.x version backward incompatible?
2.1.x version of the training model, through the Java API 1.0 API when loading the model reported:
![image](https://user-images.githubusercontent.com/10843363/88887832-bfd79180-d26f-11ea-948a-0c1042ce8760.png)

**Comment by thvasilo** [comment] 2020-07-30 21:12
Potential duplicate of #5863

**Comment by trivialfis** [comment] 2020-08-11 11:19
This error is quite obscure.  Basically any error might lead to this one.

**Comment by trivialfis** [comment] 2020-11-11 18:33
Not a maintainer for jvm package.  But what is Java API 1.x?

**Closed** 2020-12-17 13:17 UTC
