### ISSUE TITLE
 objective given invalid value reg:linear using spark 2.4

### ISSUE THREAD

**Issue by anayyar82** [dmlc/xgboost#4485] opened 2019-05-22 14:34 UTC
When giving with 

  "booster" -> "gbtree", 
      "objective" -> "reg:linear",

with latest build using spark 2.4

xgbr_f65bb991230b parameter objective given invalid value reg:linear.

**Comment by trivialfis** [comment] 2019-05-23 16:22
@anayyar82 f65bb991230b is not a git hash.  Could you please provide a complete error trace with XGBoost release tag or git commit hash?

**Comment by CodingCat** [comment] 2019-05-23 16:26
reg:linear is renamed to reg:squarederror read https://xgboost.readthedocs.io/en/latest/parameter.html#learning-task-parameters

**Comment by trivialfis** [comment] 2019-05-23 16:38
@CodingCat I committed the renaming,  it should emit a warning instead of an error.

**Comment by trivialfis** [comment] 2019-05-23 16:39
@CodingCat See https://github.com/dmlc/xgboost/blob/5a567ec24979ddd3bd033f336ff15585e736701e/src/objective/regression_obj.cu#L178

**Comment by CodingCat** [comment] 2019-05-23 16:51
well, because of this change, it throws error in spark layer, https://github.com/dmlc/xgboost/commit/29a1356669cb3c3ca2a6b22bced5047912072804#diff-4a340c5f54c4e6a6241957fae8581075L102

it's not that bad to me

**Comment by trivialfis** [comment] 2019-05-23 17:01
@CodingCat Oops, I will add it back later, the plan was to keep it for a while.  But this does alert me that lots of logic got duplicated in language binding layers.  I was to add more objectives and metrics, is it possible that we lower these things all into C++?  I can code some java but not scala ...

**Closed** 2019-05-23 22:02 UTC
