### ISSUE TITLE
Stratified sampling cross validation in xgboost, python

### ISSUE THREAD

**Issue by aksbond** [dmlc/xgboost#729] opened 2016-01-07 21:00 UTC
Hi, 

I am trying to run a model using the "NDCG" evaluation metric. However, the distribution of my data across classes is not uniform. Therefore, when I use xgb.cv, it throws the error below which states that the label sizes don't match. 
I am assuming this is because the num_class parameter is defined as 12 while one of the folds may or may not have all 12 classes present. I am simply assuming it to be the cause and haven't gone through the actual code behind this. 
Nevertheless, whether that is the problem or not, I would like to know whether it is possible to perform a stratified (sampling) cross validation with xgboost?

FYI, the same code runs with no issue if my evaluation metric is "mlogloss". 

Please let me know if I am missing something and/or there is an alternative way of doing it.

Code: 

``` 
params = {"objective": "multi:softprob", "num_class": 12, 'bst:eta':0.1, 'nthread':4}
params['eval_metric'] = 'ndcg'
bst_cv = xgb.cv(params, T_train_sample_xgb, nfold = 3, num_boost_round = 2)
```

Error:
```
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3066, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-224-50b9d65f9cb9>", line 3, in <module>
    bst_cv = xgb.cv(params, T_train_sample_xgb, nfold = 3, num_boost_round = 2)
  File "C:\Anaconda3\lib\site-packages\xgboost-0.4-py3.5.egg\xgboost\training.py", line 443, in cv
    res = aggcv([f.eval(i, feval) for f in cvfolds],
  File "C:\Anaconda3\lib\site-packages\xgboost-0.4-py3.5.egg\xgboost\training.py", line 443, in <listcomp>
    res = aggcv([f.eval(i, feval) for f in cvfolds],
  File "C:\Anaconda3\lib\site-packages\xgboost-0.4-py3.5.egg\xgboost\training.py", line 261, in eval
    return self.bst.eval_set(self.watchlist, iteration, feval)
  File "C:\Anaconda3\lib\site-packages\xgboost-0.4-py3.5.egg\xgboost\core.py", line 755, in eval_set
    ctypes.byref(msg)))
  File "C:\Anaconda3\lib\site-packages\xgboost-0.4-py3.5.egg\xgboost\core.py", line 97, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: b'label size predict size not match'  
```

**Comment by derek-damron** [comment] 2016-01-09 18:21
I'm not sure if the `xgboost` folks want to make stratified sampling the default for `multi:softprob`, but here's some code you can use to do stratified sampling so that each of the folds has a roughly equal mix of the outcomes.  

1. Take the row indices of the outcome variable in your data
2. Sort them on the outcome
3. Use the `split` function to assign roughly equal amounts of each outcome to each fold 

Here's some code to do it for 3 folds, as in your example.

```r
# Number of folds
model_nfolds <- 3
# Split to create list of fold indices
model_folds <- split( order(dat$dv_country)
                    , 1:model_nfolds
                    )
# Convert list elements to integers
model_folds <- lapply(model_folds, as.integer)
# QC - look at first five elements of each fold
lapply(model_folds, head)
# QC looks good
```

If you cross-reference these folds with our data set, you'll notice that the first element in each list component is the first "ordered" group of your outcome.  You might get a `data length is not a multiple of split variable` warning, but you can ignore that since R handles the vector recycling for you.

Finally, in your `xgb.cv` call, just remove `nfold = 3` and add `folds = model_folds` to your parameters to specify the folds you created rather than whatever folds `xgb.cv` would have created for you.  Let me know if that doesn't solve your problem!

@terrytangyuan, what do you think about adding some code like this is as a default to help users automatically avoid this type of error from occurring?  Of course users can always supply their own folds, but I think this type of a default could really help users understand the power of `xgb.cv`.

**Comment by aksbond** [comment] 2016-01-09 20:41
Thanks for that little piece @derek-damron. It would definitely work like a dream in R. However, I couldn't find the same parameter named ```folds``` in Python. There's only the ```nfold``` parameter which accepts integer data as input and that's what prompted me to raise the issue. There isn't a mention in the documentation as well. :( 

It's quite strange that the functionality exists in R but not in Python. Another excuse to drag myself back to R.. :P

**Comment by terrytangyuan** [comment] 2016-01-10 02:59
@derek-damron Thanks so much for your thoughts/suggestions. Yes, a default value for that sounds good to me. Would you be able to submit a PR for that? 

@aksbond Unfortunately it doesn't exist in Python. There's certainly known inconsistent between different language bindings of xgboost. Feel free to submit a PR to add that functionality you want.  It should be very similar to that in R. :-)

**Comment by derek-damron** [comment] 2016-01-10 03:29
@aksbond Sure thing, and good luck!

@terrytangyuan Absolutely!  Do you think that this "sorting" structure of the cross-validation folds would be a good default for all metrics?  This would help ensure that the folds have roughly the same distribution in outcomes for any modelling goal.  Using `binary:logistic` as an example, this type of stratified sampling would ensure that each fold gets a roughly equal number of "yeses" by default, which could be an issue when dealing with rare events.

**Comment by terrytangyuan** [comment] 2016-01-10 03:35
That's fine. We'll see what else needs to be added later after users' experience on this. Please also add additional test for the change and add some helpful docs to notify the default option to users.

**Comment by derek-damron** [comment] 2016-01-10 03:57
Will do.  Might be a few days, but I'll submit a pull request for us to talk about.

**Comment by khotilov** [comment] 2016-01-10 04:01
@derek-damron just to make sure that it's clear: stratified CV was
implemented and is enabled as a default option in R interface, but it's the
Python interface where this is missing.
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by derek-damron** [comment] 2016-01-10 04:10
@khotilov Thanks for the clarification, I was talking about R and not Python.

And the stratified default is interesting, because I have received errors in the past when using `multi:softprob` with incredibly rare events that I could only trace back to a particular fold not having any observations with that label.  I can't remember what the specific error was offhand, but I was able to get around it by manually specifying the folds using `folds`.  I'll see if I can create a reproducible example.

**Comment by aksbond** [comment] 2016-01-10 04:15
@terrytangyuan thanks for the clarification. However, I'd prefer @derek-damron creating the PR. I started python a week ago, so I'm still finding my feet here. I will still contribute if and when I can on this request. 

Thanks everyone for the comments and clarifications! Good luck!

**Comment by Far0n** [comment] 2016-01-17 11:02
I'm considering making a PR for python.

**Comment by derek-damron** [comment] 2016-01-17 18:35
Go for it @Far0n!

**Comment by Far0n** [comment] 2016-01-24 07:55
@terrytangyuan Is it fine to rely on sklearn for implementing the stratified cv? So here is what I would like to do:
a) adding two new parameter to xgb.cv *stratified* and *folds* (just like in R)
b) setting stratified=False as default to keep the current behavior.
c) checking sklearn if sklearn is installed as soon as stratified=True and printing a warning if that is not the case
You can then pass sklearn folds via the *folds* parameter to xgb.cv. That would be the most convenient setup in python I think. Other opinions?

**Comment by terrytangyuan** [comment] 2016-01-24 15:10
@Far0n I am not sure if we want to rely on sklearn for stratified cv. @tqchen What do you think?

**Comment by Far0n** [comment] 2016-01-29 20:50
any news? ^^

**Comment by terrytangyuan** [comment] 2016-01-29 21:22
@Far0n Yeah I think you can go ahead and do it so we can discuss details from PR. Just make sure it's backward compatible and keep behavior consistent with R.

**Comment by Far0n** [comment] 2016-01-29 21:27
@terrytangyuan .. but making the behavior consistent with R would change the current python default behavior, 'cause to my best knowledge stratified=true is the default setting for R. So, it is ok to set  stratified=True as default for python as well?

**Comment by terrytangyuan** [comment] 2016-01-29 21:30
@Far0n ok just set it to False for now and we'll see how users feel about it later on.

**Comment by Far0n** [comment] 2016-01-29 21:35
@terrytangyuan roger that :)

**Comment by jiacheliu3** [comment] 2016-02-10 16:47
Hi!
I'm using xgboost in python 2.7 and I faced the same exception as the initial issue report. I'm trying to do a 3-class classification. When I tried to 'hack' the problem by using nfold=1 I faced another exception (only related traceback provided):

File "/usr/local/lib/python2.7/dist-packages/xgboost-0.4-py2.7.egg/xgboost/training.py", line 439, in cv
    cvfolds = mknfold(dtrain, nfold, params, seed, metrics, fpreproc)
  File "/usr/local/lib/python2.7/dist-packages/xgboost-0.4-py2.7.egg/xgboost/training.py", line 275, in mknfold
    dtrain = dall.slice(np.concatenate([idset[i] for i in range(nfold) if k != i]))
**ValueError: need at least one array to concatenate**

Since this issue in python version seems still not solved by another commit, may I know if there are any known hacks to avoid the XGBoostError please?

**Comment by Far0n** [comment] 2016-02-14 10:08
PR created: https://github.com/dmlc/xgboost/pull/823

**Comment by derek-damron** [comment] 2016-02-28 16:39
Can we close this issue since @Far0n's PR has been merged?

**Closed** 2016-02-28 16:51 UTC
Labels: enhancement, Python-Package, R-package
