### ISSUE TITLE
Model produced in 1.0.0 cannot be loaded into 0.90

### ISSUE THREAD

**Issue by leedrake5** [dmlc/xgboost#5345] opened 2020-02-22 03:20 UTC
Following the instructions here: https://xgboost.readthedocs.io/en/latest/R-package/xgboostPresentation.html

```
> install.packages("drat", repos="https://cran.rstudio.com")
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/drat_0.1.5.zip'
Content type 'application/zip' length 87572 bytes (85 KB)
downloaded 85 KB

package ‘drat’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\lee\AppData\Local\Temp\RtmpiE0N3D\downloaded_packages
> drat:::addRepo("dmlc")
> install.packages("xgboost", repos="http://dmlc.ml/drat/", type = "source")
Warning: unable to access index for repository http://dmlc.ml/drat/src/contrib:
  Line starting '<!DOCTYPE html> ...' is malformed!
Warning message:
package ‘xgboost’ is not available (for R version 3.6.0) 
```

It also fails on R 3.6.2 with the same error. 

Note: I would much prefer to use the CRAN version. But models I train on linux and Mac and save using the saveRDS function don't predict on another system (windows), they just produce numeric(0). If anyone has any guidelines on how to save an XGBoost model for use on other computers, please let me know. I've tried xgb.save.raw and xgb.load - both produce numeric(0) as well. But on the computer I trained the model on (a month ago), readRDS in R works just fine. Absolutely baffling to me.

**Comment by hcho3** [comment] 2020-02-22 03:28
Did you try install.packages(‘xgboost’) ?

**Comment by leedrake5** [comment] 2020-02-22 03:58
> Did you try install.packages(‘xgboost’) ?

That works just fine, but then all predictions from saved models (using saveRDS) produce numeric(0). It seems that models trained using openMP don't work on computers without that framework. My hope was that compiling from source would resolve this.

**Comment by hcho3** [comment] 2020-02-22 05:21
This is how you compile XGBoost from the source:

```
mkdir build
cd build
cmake .. -G"Visual Studio 14 2015 Win64" -DR_LIB=ON
cmake --build . --target install --config Release
```

Can you share the model file so that we can try to find why you are getting a 0 for prediction?

**Comment by leedrake5** [comment] 2020-02-22 05:46
Thanks - do you want the R object or would you prefer it converted via xgb.save.raw?

**Comment by hcho3** [comment] 2020-02-22 06:02
Both

**Comment by leedrake5** [comment] 2020-02-22 06:20
Thank you for your help and support (and with making such an extraordinary learning program). 

Attached is a zipped .rdata file. On 3 systems (Mac, MacBook, Ubuntu), I can run the following code:

```
readRDS("<path_to_folder>/modelList.rdata")
attach(modelList)
predictions_caret <- predict(object=caretModel, newdata=caretModel$trainingData[,!colnames(caretModel$trainingData) %in% ".outcome"])
predictions_xgbbase <- predict(object=xgbModel, newdata=as.matrix(caretModel$trainingData[,!colnames(caretModel$trainingData) %in% ".outcome"]))
```
And get the following output:

```
> predictions_caret <- predict(object=caretModel, newdata=caretModel$trainingData[,!colnames(caretModel$trainingData) %in% ".outcome"])
[23:12:50] WARNING: ../..//amalgamation/../src/objective/regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
> head(predictions_caret)
[1] 14.0180358887 13.0352602005 12.9208145142 13.2430124283 13.6698570251
[6] 12.9033651352

>predictions_xgbbase <- predict(object=xgbModel, newdata=as.matrix(caretModel$trainingData[,!colnames(caretModel$trainingData) %in% ".outcome"]))
[23:16:17] WARNING: ../..//amalgamation/../src/objective/regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
> head(predictions_xgbbase)
[1] 14.0180358887 13.0352602005 12.9208145142 13.2430124283 13.6698570251
[6] 12.9033651352
```

On system 4 (windows base R with xgboost installed from CRAN) I get very different outcomes:

```
predictions_caret <- predict(object=caretModel, newdata=caretModel$trainingData[,!colnames(caretModel$trainingData) %in% ".outcome"])
[23:18:04] WARNING: amalgamation/../src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
> head(predictions_caret)
numeric(0)

> predictions_xgbbase <- predict(object=xgbModel, newdata=as.matrix(caretModel$trainingData[,!colnames(caretModel$trainingData) %in% ".outcome"]))
[23:18:41] WARNING: amalgamation/../src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
> head(predictions_xgbbase)
numeric(0)

```

I suspect this may need a new issue opened, but I appreciate any guidance you can give for why the same code would behave differently on different systems. 

Thank you once again. 

[modelList.rdata.zip](https://github.com/dmlc/xgboost/files/4238889/modelList.rdata.zip)

**Comment by trivialfis** [comment] 2020-02-22 07:15
Probably due to our dmlc guard over omp exception?

**Comment by hcho3** [comment] 2020-02-22 08:19
@leedrake5 Does your machine not support OpenMP?

**Comment by trivialfis** [comment] 2020-02-22 08:47
@hcho3 Did you find the cause?  I just compile XGBoost without OpenMP (with some patches to CMakeLists), external memory tests are failing as expected, also hist parallel group test is failing (which I fixed in local branch).  But so far I can get perfect prediction values.

**Comment by leedrake5** [comment] 2020-02-22 16:58
@hcho3 My machine supports openmp. But we are deploying these models on an industrial scale, and lots of the computers at specific sites don't have openmp. We just discovered this after 6 months of prep and one week till implementation, so we are scrambling to figure out why the models work on some computers and not others.

**Comment by trivialfis** [comment] 2020-02-22 20:09
@leedrake5 It's a bug.  I tried to reproduce it on Ubuntu with openmp disabled but so far no luck.

**Comment by leedrake5** [comment] 2020-02-22 20:14
@trivialfs If it helps, I and most my colleagues experiencing the bug on windows. Though a colleague of mine was able to reproduce it on ubuntu without openmp.

**Comment by trivialfis** [comment] 2020-02-22 20:26
@leedrake5 If there's a way to reproduce it on Linux distributions it would be of great help!

I disabled all options including google test, omp ...  But still have the correct result loading your models.  The installation of R is the default distribution from `apt`, I don't think it has anything to do with XGBoost prediction.

**Comment by trivialfis** [comment] 2020-02-22 20:45
It might not be caused by OpenMP.  As even the prediction goes really wrong there's still global bias, not 0.

The only reason I can think of is XGBoost is not actually being installed.

I tried both CMake build and autotools build.  This is my compilation flags reported by `install.packages(...)`:
```
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I../..//include -I../..//dmlc-core/include -I../..//rabit/include -I../../ -DXGBOOST_STRICT_R_MODE=1 -DDMLC_LOG_BEFORE_THROW=0 -DDMLC_ENABLE_STD_THREAD=1 -DDMLC_DISABLE_STDIN=1 -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_CUSTOMIZE_LOGGER=1 -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_    -DDMLC_CMAKE_LITTLE_ENDIAN=1 -pthread -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-el7SHG/r-base-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c ../..//amalgamation/xgboost-all0.cc -o ../..//amalgamation/xgboost-all0.o
```

**Comment by leedrake5** [comment] 2020-02-22 21:13
@trivialfis Even more curious, as XGBoost installs successfully from CRAN, and library(xgboost) works without any problem.

**Comment by trivialfis** [comment] 2020-02-23 06:51
> Though a colleague of mine was able to reproduce it on ubuntu without openmp.

Is it possible that he/she can kindly share how to reproduce?

**Comment by leedrake5** [comment] 2020-02-23 17:57
> > Though a colleague of mine was able to reproduce it on ubuntu without openmp.
> 
> Is it possible that he/she can kindly share how to reproduce?

Not sure they know enough about how linux systems work - but if you know of any diagnostics they can provide let me know. 

For my part, I am trying to create a virtual box ubuntu installation that can replicate the problem - if successful I will send a download link for that.

**Comment by leedrake5** [comment] 2020-02-23 20:03
I've successfully reproduced the issue on linux - see attached screenshot. 

I am uploading the virtual box to dropbox. But in case you'd prefer to install from scratch, instructions to replicate are as follows:

1. Download and install virtualbox
2. Download a build of ubuntu bionic beaver (I used ubuntu-18.04.3-desktop-amd64). 
3. Configure for R 3.6.2 by the following:

```
sudo apt-get update
sudo apt-get install vim
sudo vim /etc/apt/sources.list
i
deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/
<esc> :wq
gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
gpg -a --export E298A3A825C0D65DFD57CBB651716619E084DAB9 | sudo apt-key add -
sudo apt-get update
sudo apt-get install r-base-dev
```
4. install packages in R
`install.packages(c("caret", "xgboost"))
`5. load packages in R
```
library(caret)
library(xgboost)
```
6. Load the data
```
modelList <- readRDS("~/Desktop/modelList.rdata")
attach(modelList)
```
7. Attempt to predict
`predict(object=xgbModel, newdata=as.matrix(caretModel$trainingData[,!colnames(caretModel$trainingData) %in% ".outcome"]))`

And this returned the now familiar:

> [13:00:55] WARNING: amalgamation/../src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
> numeric(0)

<img width="1601" alt="Screen Shot 2020-02-23 at 12 33 13 PM" src="https://user-images.githubusercontent.com/1229542/75118730-d848dd80-5639-11ea-9512-9db0c224b3d3.png">

**Comment by leedrake5** [comment] 2020-02-24 00:32
Link to 7z compressed virtual instance is here: https://www.dropbox.com/s/ld06zz798m0segf/UbuntuDebug.7z?dl=0

**Comment by trivialfis** [comment] 2020-02-24 05:20
Let me get virtual box first.  I usually use KVM.

**Comment by hcho3** [comment] 2020-02-27 06:19
Looking at this now.

**Comment by hcho3** [comment] 2020-02-27 07:19
@leedrake5 I managed to reproduce the issue on the virtual machine you provided. It appears that there is an issue with `saveRDS` and `xgb.save.raw`. Did you try using `xgb.save` and `xgb.load` instead?

**Comment by trivialfis** [comment] 2020-02-27 08:34
The save raw should not be a problem.  The problem might be in how R serialize the R code.  We added a new optional parameter to predict, which might affect loading these kinds of serialization.  I tried looking into it but seems really quirky, just like the problem with Python pickle.

**Comment by leedrake5** [comment] 2020-02-27 17:45
@trivialfis any ideas on options in the predict function that could potentially circumvent this? My thought is that it has something to do with CPU instructions, possibly deeper in R than can be addressed by the package.

@hcho3 I will try adding xgb.save.raw to the current data pipe and see if that helps. Though in the example I sent, I did try this by using xgb.save.raw on the computer where predictions worked, and it unfortunately still lead to numeric(0) on xgb.load. Admittedly, this was after the model had already been saved via saveRDS, perhaps something about that process corrupts it, even though it still works in the environment it was created. 

As far as I can tell, there is still something about the environment where the model was created that needs to be present in every environment it is used. I don't know what it is though.

**Comment by hcho3** [comment] 2020-02-27 18:02
No, I meant `xgb.save`, not `xgb.save.raw`.

**Comment by hcho3** [comment] 2020-02-27 18:03
@trivialfis Note that the XGBoost package is still 0.90 on CRAN.

**Comment by leedrake5** [comment] 2020-03-03 23:05
I tried xgb.save, loaded it in R via xgb.load(), and same thing, numeric(0). See attached from xgb.save

[xgbModelSaved.xgb.zip](https://github.com/dmlc/xgboost/files/4284054/xgbModelSaved.xgb.zip)

**Comment by leedrake5** [comment] 2020-03-04 00:53
Also- tested the same method using the data in modelList earlier in this thread on the same computer that generated the model - it worked there. 

No matter how you slice it, xgb.save, xgb.save.raw, saveRDS, etc., there is something about the computer environment the model was created on that precludes its use elsewhere.

**Comment by hcho3** [comment] 2020-03-04 00:55
I am able to reproduce the issue using the model file you provided. However, I have no idea as to how the model file was generated. Can you provide more context, e.g.
* OS
* XGBoost version
* Command to save the model

**Comment by leedrake5** [comment] 2020-03-04 01:01
OS X (Catalina). XGBoost build from source, 1.0 (openMP supported on the system). Model originally saved using saveRDS. I will try rerunning it and saving via different ways and report back.

**Comment by leedrake5** [comment] 2020-03-04 01:57
I regenerated a model from scratch, saved it using xgb.save (e.g. no use of saveRDS or readRDS except for prediction data) and loaded using xgb.load. Same results - prediction works on the computer system used to generate the model (OS X, XGB 1.0) and fails on another system (Windows 7, XGB 0.9). Attaching it and the modelList to this message. If there is anything else I can do to help diagnose this issue please let me know. 

```
xgb_model <- xgb.load("Z:/Desktop/newxgbModelSaved.xgb")
modelList <- readRDS("Z:/Desktop/modelList2.rdata")
attach(modelList)
predict(object=xgb_model, newdata=as.matrix(caretModel$trainingData[,!colnames(caretModel$trainingData) %in% ".outcome"]))
numeric(0)
```

[newxgbModelSaved.xgb.zip](https://github.com/dmlc/xgboost/files/4284635/newxgbModelSaved.xgb.zip)

[modelList2.rdata.zip](https://github.com/dmlc/xgboost/files/4284634/modelList2.rdata.zip)

**Comment by hcho3** [comment] 2020-03-04 02:55
@leedrake5 Is it possible to use XGBoost 1.0 on Windows?

@trivialfis This might be a problem with backward compatibility of model files.

**Comment by leedrake5** [comment] 2020-03-04 03:01
It's definitely versioning. I just dropped by 1.0 version of XGBoost, installed 0.9 from CRAN, and the method outlined above worked. 

I tried to install 0.90 from source using the [latest release](https://github.com/dmlc/xgboost/releases/tag/v0.90), but the dmlc-core folder is empty, so Cmake throws the necessary error. Would very much like to keep openMP functionality however this goes.

**Comment by hcho3** [comment] 2020-03-04 03:30
I see. Did you try to install 1.0.0 version on Windows?

**Comment by leedrake5** [comment] 2020-03-04 03:49
That was the initial reason for this thread, oddly enough. Will try, but there will be a delay as the project can't wait any longer. If this is a problem, I suspect that installing 1.0 from source on the ubuntu virtual image I sent would address the same thing.

**Comment by hcho3** [comment] 2020-03-04 04:08
Yes, you should match the version of  XGBoost. Either use 0.90 everywhere or 1.0.0 everywhere.

@trivialfis I do recall that we made a breaking change in the binary model format. Is that right?

**Comment by trivialfis** [comment] 2020-03-04 04:20
No, we are backward compatible, 1.0 should definitely load model from 0.9

**Comment by hcho3** [comment] 2020-03-04 04:21
@trivialfis Thanks for clarification. In that case, let’s treat this ticket as a bug. I will look at it this week.

**Comment by leedrake5** [comment] 2020-03-04 04:35
I think the proposed title change has it backwards - model produced in 1.0 can't be used to predict in 0.90. I don't know what degree of compatibility is intended between versions, but at minimum an informative error should help.

**Comment by hcho3** [comment] 2020-03-04 04:37
Oops, my bad.

@trivialfis I believe what @leedrake5 is asking is forward compatibility, i.e. loading model from 1.0.0 into 0.90.

**Comment by hcho3** [comment] 2020-03-04 04:41
@leedrake5 I tried installing 1.0.0 in the Ubuntu virtual machine, and now the RDS file loads fine and I get a vector of real numbers. So most likely it is the version issue.

**Comment by leedrake5** [comment] 2020-03-04 04:45
I agree. Very glad to set convergence on what the problem is. 

Unfortunately, from a production standpoint, I've got to make models deployable in the mass version (ergo, CRAN installation). But, I know how to make XGBoost work from here on out, which is the absolute critical point. 

I am still having troubles installing 0.9 from source downloaded from releases or the tree, but I think I found the problem. cub, dmlc-core, rabit, all are empty folders in these downloads. They also have @ <tag> after the folders - I think that is related to which folders are empty. If I follow those links, I can rebuild folders and continue installation. 

See screenshot:
<img width="1013" alt="Screen Shot 2020-03-03 at 9 41 33 PM" src="https://user-images.githubusercontent.com/1229542/75845980-05af2d00-5d98-11ea-9d75-7f0aadb3e45a.png">

**Comment by hcho3** [comment] 2020-03-04 04:48
Yes, we use git submodules, so the build instruction asks you to use `git clone --recursive`. Are you in a situation where CRAN installation is inadequate?

**Comment by leedrake5** [comment] 2020-03-04 04:50
Yes - CRAN doesn't allow for openMP, which for model generation is a huge boon. So will spend some time figuring out how to compile xgboost 0.90 from source to get that working again. I appreciate all of your help on diagnosing this issue.

**Comment by hcho3** [comment] 2020-03-04 04:54
@leedrake5 

Got it. For now, here is the command you can use to get the full source code, including the git submodules:
```
git clone --recursive https://github.com/dmlc/xgboost -b release_0.90
```
This should populate rabit, cub, dmlc-core directories.

Aside:

>  CRAN doesn't allow for openMP

This is actually fixed in 1.0.0. I will try to get 1.0.0 version on CRAN soon.

**Comment by leedrake5** [comment] 2020-03-04 04:58
Thank you, much appreciated on all counts!

**Comment by hcho3** [comment] 2020-03-04 06:58
@hetong007 Can we submit 1.0.0 to CRAN?

**Comment by hetong007** [comment] 2020-03-04 07:11
@hcho3 Sounds good, given that we have a valid endian detection. I'll make a submission in a week.

**Comment by hcho3** [comment] 2020-03-12 08:11
@hetong007 Any updates? Let me know if you need any help.

**Comment by hetong007** [comment] 2020-03-12 08:22
@hcho3 oh yes. I'd like to ask if we have the environment for solaris testing? There's an unresolved error on solaris from 0.9: https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/xgboost-00check.html I'd like to have it checked before the submission.

**Comment by hcho3** [comment] 2020-03-13 07:00
@hetong007 I just downloaded Solaris VM image from Oracle that can run with VirtualBox. Let me try to reproduce the issue.

**Comment by hcho3** [comment] 2020-03-13 20:35
@hetong007 I am having lots of trouble setting up the R environment in Solaris. In particular, I cannot install R packages like `igraph` because utilities like `awk` behave differently on Solaris.

**Comment by hetong007** [comment] 2020-03-14 03:01
@hcho3 Would you please be clearer? I imaging one could install packages in R console with `install.packages('testthat')`, given that `testthat` has passed solaris check on CRAN.

**Comment by hcho3** [comment] 2020-03-14 03:04
@hetong007 The package `igraph` uses `awk` in configure step, and Solaris's `awk` is not feature compatible with GNU awk.

**Comment by hetong007** [comment] 2020-03-14 03:08
@hcho3 OK this sounds awful. I have no knowledge in how to proceed either. I just took a look at `igraph`'s result page on CRAN: https://cran.r-project.org/web/checks/check_results_igraph.html. Feels that we are not going to be worse. I'll make a submission regardless.

**Comment by hcho3** [comment] 2020-03-14 03:10
@hetong007 Thanks. I'll try to get back to Solaris testing at some point.

**Comment by hcho3** [comment] 2020-03-14 23:21
@hetong007 Ah yes, make sure to use the branch `release_1.0.0` when submitting the code.

**Comment by hetong007** [comment] 2020-03-15 08:58
@hcho3 The pre-check warns:

```
* checking whether package 'xgboost' can be installed ... WARNING
Found the following significant warnings:
  amalgamation/../src/common/hist_util.cc:666:72: warning: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'struct xgboost::tree::GradStats'; use assignment or value-initialization instead [-Wclass-memaccess]
See 'd:/RCompile/CRANguest/R-devel_gcc8/xgboost.Rcheck/00install.out' for details.
```

and the `00install.out` file is here (available in ~72 hours): https://win-builder.r-project.org/v6XJQBjzgMaW/00install.out 

Would it be possible to have a quick fix?

**Comment by hcho3** [comment] 2020-03-15 09:16
@hetong007 Is this a blocker? Memset was used to speed up zeroing out histogram (array of structure). If this is blocking CRAN, I will put a macro guard so that the R package will use ordinary constructor instead.

**Comment by hetong007** [comment] 2020-03-15 09:26
@hcho3 Yes It is a blocker. The pre-check is automated and the submission should pass without warning. The macro sounds good enough, thanks!

**Comment by trivialfis** [comment] 2020-03-15 22:18
@hcho3  Could you please try using `std::fill` first?  Even the compiler cannot optimize it into `memset`, I don't think it's critical enough to have any visible performance impact.

**Comment by hcho3** [comment] 2020-03-22 05:45
@hetong007 I made the necessary change (https://github.com/dmlc/xgboost/commit/3550b16a34055bc8ec33bf0b7006448e8c1a4eca). Can you try again?

**Comment by hetong007** [comment] 2020-03-23 07:54
@hcho3 thanks for the fix! If nothing serious goes wrong, it is on the way to CRAN.

**Comment by hetong007** [comment] 2020-03-23 13:58
@hcho3 So it fails on Soalris, from Prof. Ripley:

```

On Solaris it was quicker to diagnose the problems with the GCC compilers:

amalgamation/../src/common/io.cc:120:27: error: ‘POSIX_FADV_SEQUENTIAL’
was not declared in this scope
    posix_fadvise(fd, 0, 0, POSIX_FADV_SEQUENTIAL);

amalgamation/../src/common/io.cc:120:48: error: ‘posix_fadvise’ was not
declared in this scope
    posix_fadvise(fd, 0, 0, POSIX_FADV_SEQUENTIAL);

As 'Writing R Extensions' told you, you need to use configure to test
for the presence of non-standard C/C++ functions.  In this case, it
seems that line is not actually necessary.

```

**Comment by hcho3** [comment] 2020-03-23 21:38
@hetong007 Nice. Please tell Prof. Ripley thanks for taking time to debug the problem. I will go ahead and guard that line to only run in proper Linux environment only, since we only have proper testing facility to test non-standard C++ facilities.

**Comment by hetong007** [comment] 2020-03-24 00:16
@hcho3 sounds good to me. The deadline from Prof. Ripley for a new submission to CRAN is 2020-04-06. If you are interested in detailed installation log, please visit https://cran.r-project.org/web/checks/check_results_xgboost.html

**Comment by hcho3** [comment] 2020-03-25 00:12
@hetong007 The commit https://github.com/dmlc/xgboost/commit/d83db4844bae5969609e58cd6bb201e7831cfaa3 should address the problem. I finally managed to get the latest R working with my Solaris VM and run CRAN checks for XGBoost.

**Comment by hetong007** [comment] 2020-03-25 01:01
@hcho3 Brilliant! Can I take it as you have made it pass the check on Solaris?

**Comment by hcho3** [comment] 2020-03-25 01:02
Yes, we should submit it now.

**Comment by sunhs** [comment] 2020-03-25 03:00
Hi, I'm faced with similar issues with Python. I saved the model via xgboost 1.0.1, and loaded it via xgboost 0.9, and the predictions are empty lists. Since our production environment is using xgboost 0.9, I'm wondering if there's any way I can load a saved-via-xgboost-1.0 model into xgboost 0.9?

**Comment by hetong007** [comment] 2020-03-25 03:42
@hcho3 Is there a way to share your snapshot? It is valuable for our further submission as well.

**Comment by giladmaya** [comment] 2020-06-04 13:46
@sunhs I'm also facing a similar issue. Were you able to solve this?

**Comment by sunhs** [comment] 2020-06-05 02:14
@giladmaya Nope man. After trying several methods, I finally decided that retraining the model saved my time.

**Comment by hcho3** [comment] 2020-06-18 04:39
Closing this, since we are unable to promise that models from newer versions would be supported by older versions. We promise only backward compatibility, so that the model format can gradually evolve over time.

**Closed by hcho3** 2020-06-18 04:39 UTC
