### ISSUE TITLE
Allreduce failed and boundary errors since v1.7.0 with dask and rabit

### ISSUE THREAD

**Issue by efocht** [dmlc/xgboost#9107] opened 2023-04-28 10:35 UTC
Since v1.7.0 I'm getting allreduce problems when training with dask. Using LocalCluster with 4 - 16 workers, 1 thread per worker. Example below is from 16 workers.

The dataset is huge and there are many features, I wasn't able to create a reproducer. Instead I instrumented the code in `rabit/src/allreduce_base.cc` as you can see in the patch https://github.com/efocht/xgboost/commit/161ed3cd7dc7c762edf7f46a49d1bde2c45c3836

The problems start after a while, I can see that allreduce works fine many times but suddenly things go wrong:
```
[11:21:29] TryAllreduceRing byte_size=8 count=553842
[11:21:29] TryAllreduceRing byte_size=8 count=502914
[11:21:29] TryAllreduceRing byte_size=8 count=502914
[11:21:29] TryAllreduceRing byte_size=8 count=502914
[11:21:29] TryAllreduceRing byte_size=8 count=496548
[11:21:29] TryAllreduceRing byte_size=8 count=509280
[11:21:29] TryAllreduceRing byte_size=8 count=496548
[11:21:29] TryAllreduceRing byte_size=8 count=502914
[11:21:29] TryAllreduceRing byte_size=8 count=509280
[11:21:29] TryAllreduceRing byte_size=8 count=509280
[11:21:29] TryAllreduceRing byte_size=8 count=515646
[11:21:29] TryAllreduceRing byte_size=8 count=509280
[11:21:29] TryAllreduceRing byte_size=8 count=502914
[11:21:29] TryAllreduceRing byte_size=8 count=509280
[11:21:29] TryAllreduceRing byte_size=8 count=496548
[11:21:29] TryReduceScatterRing ERROR end len = -1
[11:21:29] TryReduceScatterRing ERROR end len = -1
[11:21:29] TryReduceScatterRing ERROR end len = -1
[11:21:29] TryReduceScatterRing ERROR end len = -1
[11:21:29] TryReduceScatterRing ERROR end len = -1
[11:21:29] TryReduceScatterRing ERROR end len = -1
[11:21:29] TryReduceScatterRing ERROR end len = -1
[11:21:29] TryReduceScatterRing ERROR end len = -1
[11:21:29] TryReduceScatterRing ERROR end len = -1
[11:21:29] TryReduceScatterRing ERROR end len = -1
[11:21:29] TryReduceScatterRing ERROR end len = -1
[11:21:29] TryReduceScatterRing ERROR end len = -1
[11:21:29] TryReduceScatterRing ERROR end len = -1
[11:21:29] TryReduceScatterRing ERROR end len = -1
[11:21:29] TryReduceScatterRing ERROR end len = -1
[11:21:29] TryReduceScatterRing ERROR end len = -1
[11:21:29] TryReduceScatterRing ERROR end len = -1
[11:21:29] TryReduceScatterRing ERROR end len = -1
[11:21:29] TryAllreduceRing byte_size=8 count=509280
[11:21:29] TryAllreduceTree byte_size=8 count=1
[11:21:29] TryAllreduceTree byte_size=8 count=1
[11:21:29] TryAllreduceTree byte_size=8 count=1
[11:21:29] TryAllreduceTree byte_size=8 count=1
[11:21:29] TryAllreduceTree byte_size=8 count=1
[11:21:29] TryAllreduceTree byte_size=8 count=1
[11:21:29] TryAllreduceTree byte_size=8 count=1
[11:21:29] TryAllreduceTree byte_size=8 count=1
[11:21:29] TryAllreduceTree byte_size=8 count=1
[11:21:29] TryAllreduceTree byte_size=8 count=1
[11:21:29] TryAllreduceTree byte_size=8 count=1
[11:21:29] TryAllreduceTree ERROR read zero data from parent
[11:21:29] TryAllreduceTree ERROR read zero data from parent
[11:21:29] TryAllreduceTree ERROR read zero data from parent
[11:21:29] TryAllreduceTree ERROR read zero data from parent
[11:21:29] TryAllreduceTree ERROR read zero data from parent
[11:21:29] TryAllreduceTree byte_size=8 count=1
[11:21:29] TryAllreduceTree ERROR read zero data from parent
2023-04-28 11:21:30,490 - distributed.worker - WARNING - Compute Failed
Key:       dispatched_train-0733b1eb-a437-40a4-a8d3-c2e13b4d5c0f
Function:  dispatched_train
args:      ({'max_depth': 14, 'eta': 0.3, 'monotone_constraints': (1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), 'alpha': 0.0, 'reg_lambda': 1.0, 'gamma': 0.0, 'objective': 'rank:pairwise', 'scale_pos_weight': 1.0, 'colsample_bytree': 1, 'subsample': 1, 'min_child_weight': 1, 'booster': 'gbtree', 'tree_method': 'hist', 'max_bin': 256, 'seed': 42, 'nthread': 1, 'disable_default_eval_metric': 1, 'verbosity': 3}, {'DMLC_NUM_WORKER': 16, 'DMLC_
kwargs:    {}
Exception: "XGBoostError('[11:21:29] /home/focht/NOI/xgboost/rabit/include/rabit/internal/utils.h:86: Allreduce: boundary error c_void_p(46956676228976),  1,  7,  2')"

2023-04-28 11:21:30,490 - distributed.worker - WARNING - Compute Failed
Key:       dispatched_train-947ef6f6-81b6-4a15-8be2-3e56414211be
Function:  dispatched_train
args:      ({'max_depth': 14, 'eta': 0.3, 'monotone_constraints': (1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), 'alpha': 0.0, 'reg_lambda': 1.0, 'gamma': 0.0, 'objective': 'rank:pairwise', 'scale_pos_weight': 1.0, 'colsample_bytree': 1, 'subsample': 1, 'min_child_weight': 1, 'booster': 'gbtree', 'tree_method': 'hist', 'max_bin': 256, 'seed': 42, 'nthread': 1, 'disable_default_eval_metric': 1, 'verbosity': 3}, {'DMLC_NUM_WORKER': 16, 'DMLC_
kwargs:    {}
Exception: "XGBoostError('[11:21:29] /home/focht/NOI/xgboost/rabit/include/rabit/internal/utils.h:86: Allreduce failed c_void_p(47162700480048),  1,  7,  2')"

[...]
```

This doesn't happen with versions older than v1.7.0. The case works fine with v1.6.2 and v1.5.2.

Do you have any idea what could go wrong? Or what I could adjust to get this working again?

**Comment by trivialfis** [comment] 2023-04-28 10:57
Could you please share the worker log as well?

**Comment by efocht** [comment] 2023-04-28 11:19
Here it is:
[output.zip](https://github.com/dmlc/xgboost/files/11352959/output.zip)

**Comment by trivialfis** [comment] 2023-04-28 11:40
hmm .. there was shutdown signal before the error.

**Comment by trivialfis** [comment] 2023-04-28 12:23
That's what I'm suspecting. A worker shutdown before all the communications finished, hence the error. But I can't tell what's happening by looking in the log, dask sometimes hides errors due to different errors from different workers.

**Comment by efocht** [comment] 2023-04-28 13:52
I tried increasing the verbosity of the dask log by creating a file `~/.config/dask/logging.yaml`:
```
logging:
  distributed: info
  distributed.client: debug
  distributed.worker: debug
  distributed.scheduler: debug
  distributed.nanny: debug
  bokeh: warning
```

Still no trace of why the workers shut down:
```
D 28-04-23 15:04:39 root.accept_workers:375 Received start signal from 10.10.6.5; assign rank 0
D 28-04-23 15:04:39 root.accept_workers:375 Received start signal from 10.10.6.5; assign rank 1
D 28-04-23 15:04:39 root.accept_workers:375 Received start signal from 10.10.6.5; assign rank 2
D 28-04-23 15:04:39 root.accept_workers:375 Received start signal from 10.10.6.5; assign rank 3
D 28-04-23 15:04:39 root.accept_workers:375 Received start signal from 10.10.6.5; assign rank 4
D 28-04-23 15:04:39 root.accept_workers:375 Received start signal from 10.10.6.5; assign rank 5
D 28-04-23 15:04:40 root.accept_workers:375 Received start signal from 10.10.6.5; assign rank 6
D 28-04-23 15:04:40 root.accept_workers:375 Received start signal from 10.10.6.5; assign rank 7
I 28-04-23 15:04:40 root.accept_workers:382 @tracker All of 8 nodes getting started
D 28-04-23 15:34:52 root.accept_workers:345 Received shutdown signal from 2
D 28-04-23 15:34:52 root.accept_workers:345 Received shutdown signal from 1
D 28-04-23 15:34:52 root.accept_workers:345 Received shutdown signal from 4
D 28-04-23 15:34:52 root.accept_workers:345 Received shutdown signal from 0
D 28-04-23 15:34:52 root.accept_workers:345 Received shutdown signal from 7
D 28-04-23 15:34:52 root.accept_workers:345 Received shutdown signal from 6
D 28-04-23 15:34:52 root.accept_workers:345 Received shutdown signal from 5
D 28-04-23 15:34:53 distributed.scheduler.stimulus_task_erred:4694 Stimulus task erred dispatched_train-3f357b3d-97ea-4512-972e-a78ccd90df01, tcp://127.0.0.1:37604
D 28-04-23 15:34:53 distributed.scheduler.stimulus_task_erred:4694 Stimulus task erred dispatched_train-d453bfc1-3de8-443a-8a25-858b25fe9603, tcp://127.0.0.1:35246
D 28-04-23 15:34:53 distributed.scheduler.stimulus_task_erred:4694 Stimulus task erred dispatched_train-0a7e5c9b-6875-471e-9cf4-e2c19af9d543, tcp://127.0.0.1:34602
D 28-04-23 15:34:53 distributed.scheduler.stimulus_task_erred:4694 Stimulus task erred dispatched_train-4f2f3643-d7af-4619-ba13-43398f98c711, tcp://127.0.0.1:41988
D 28-04-23 15:34:53 distributed.scheduler.stimulus_task_erred:4694 Stimulus task erred dispatched_train-4e6f956f-634d-4c28-b97a-7210bdfa8541, tcp://127.0.0.1:46777
D 28-04-23 15:34:53 distributed.scheduler.stimulus_task_erred:4694 Stimulus task erred dispatched_train-f2600b9a-bbe7-415c-adb4-3bad2dcceaa0, tcp://127.0.0.1:35263
D 28-04-23 15:34:53 distributed.scheduler.stimulus_task_erred:4694 Stimulus task erred dispatched_train-21f06225-adaf-4063-8454-ba4fc4804f4d, tcp://127.0.0.1:41504
D 28-04-23 15:34:53 distributed.client._handle_report:1532 Client receives message {'op': 'task-erred', 'key': 'dispatched_train-3f357b3d-97ea-4512-972e-a78ccd90df01', 'exception': b'\x80\x05\x95\xe5\t\x00\x00\x00\x00\x00\x00\x8c\x16tblib.pickling_support\x94\x8c\x12unpickle_exception\x94\x93\x94(\x8c\x0cxgboost.core\x94\x8c\x0cXGBoostError\x94\x93\x94\x8c\x82[15:34:52] /xgboost/rabit/include/rabit/internal/utils.h:86: Allreduce failed c_void_p(140229280714480),  1,  7,  2\x94\x85\x94Nh\x00\x8c\x12unpickle_traceback\x94\x93\x94\x8c
```

**Comment by efocht** [comment] 2023-04-29 10:58
Thank you for caring, the details on the dataset will take a bit of time, let me see if I can create something random and similar.
I use local machines, run things inside a ubuntu 22.04 container. They're having 0.5 - 1TB RAM which the full dataset requires. For testing with the a fraction of the dataset things seem to fit into ~10GB RAM.
Dask version is 2023.3.1 (and xgboost 1.6.2 works fine with that).
Dask workers are not constrained regarding memory. In the small test they need at most 2-3 GB, in the full case more like 10-20GB.

**Comment by trivialfis** [comment] 2023-04-29 15:05
I will try to reproduce it, might take some time.

**Comment by trivialfis** [comment] 2023-04-29 15:56
Have you seen something like this in the log:
```
2023-04-29 23:54:29,506 - distributed.nanny.memory - WARNING - Worker tcp://127.0.0.1:34105 (pid=95229) exceeded 95% memory budget. Restarting...
```

**Comment by efocht** [comment] 2023-04-29 21:48
> 2023-04-29 23:54:29,506 - distributed.nanny.memory - WARNING - Worker tcp://127.0.0.1:34105 (pid=95229) exceeded 95% memory budget. Restarting...

No, that's not in the logs.

**Comment by efocht** [comment] 2023-05-01 21:44
The shape, btw, is 3000000,204, with most of the columns being "boolen" with values of 0 and 1, only. Everything is fp32.

But while I was trying to build a reproducer I noticed something odd: running the case interactively works fine!
Normally I run this in a slurm job. Inside the slurm job script I call something like
```
apptainer run ... my-ubuntu-22.04.sif bash <<EOF
. venv/bin/activate
./run_pipeline_including_xgboost
EOF
```
Doing the `apptainer` and following steps interactively, after having ssh'd to the target node works fine. Result okay, no allreduce error whatsoever.

Cross-check: if I login to the target node by `ssh -T` (interactively, but prohibiting pty allocation) it again ends up in the well known situation: the last allreduce calls are not issued by all dask workers!
```
[23:13:45] TryAllreduceRing byte_size=8 count=89152
[23:13:45] TryAllreduceRing byte_size=8 count=89152
[23:13:45] TryAllreduceRing byte_size=8 count=89152
[23:13:45] TryAllreduceRing byte_size=8 count=89152
[23:13:45] TryAllreduceRing byte_size=8 count=82784
[23:13:45] TryAllreduceRing byte_size=8 count=89152
[23:13:45] TryAllreduceRing byte_size=8 count=89152
[23:13:45] TryAllreduceRing byte_size=8 count=89152
[23:13:45] TryAllreduceTree byte_size=8 count=1
[23:13:45] TryAllreduceTree byte_size=8 count=1
[23:13:45] TryAllreduceTree byte_size=8 count=1
[23:13:45] TryAllreduceTree byte_size=8 count=1
[23:13:45] TryAllreduceTree byte_size=8 count=1
[23:13:45] TryAllreduceTree byte_size=8 count=1
[23:13:45] TryAllreduceTree byte_size=8 count=1
```
Only 7 `count=1` calls issued, before there were 8.

In the dask log I don't see that the workers were finishing at this moment. That is something I see when they time out, about 15-20 minutes later.

I updated dask to 2023.4.1 (latest released version), no change.

Does that ring a bell? Is there any component (or dependency) that might require a tty?

**Comment by trivialfis** [comment] 2023-05-02 09:57
count=1 can be explained by transmitting the size of a memory region (uint64_t, which has byte size = 8), or running allreduce to calculating the mean value of a single number, like the score returned by the metrics.

**Comment by trivialfis** [comment] 2023-05-02 10:05
I don't understand the cause at the moment. If it's any help, you can use `LOG(FATAL)` in the failed called to obtain a log of backtrace along with timestamp, which might make debugging easier. With a backtrace, you can check whether the content being transmitted makes sense, for instance, if the backtrace comes from Python custom metrics, then converting the transmitted to `double` should reveal a value that's close to the sum of values being calculated in Python functions in selected workers. If it's a network issue, it would look completely random.

**Comment by efocht** [comment] 2023-05-02 11:38
Here is a reproducer with random data. It locks up on my laptop with `cpus=2` already, but I've set the default to 4 CPUs (cores/workers). Before it starts fitting the program waits for input, this is the chance for attaching a debugger...

1) Create two virtual envs: one with xgboost-1.7.5 and one with xgboost-1.6.2
```
python3.10 -m venv venv-1.6.2
source venv-1.6.2/bin/activate
pip install dask[complete]==2023.4.1 xgboost==1.6.2
deactivate
```
```
python3.10 -m venv venv-1.7.5
source venv-1.7.5/bin/activate
pip install dask[complete]==2023.4.1 xgboost==1.7.5
deactivate
```

2) Run reproducer in venv-1.6.2
```
source venv-1.6.2/bin/activate
python3.10 dask_xgb_lockup.py
```
runs ... forever

3) Run reproducer in venv-1.7.5
```
source venv-1.7.5/bin/activate
python3.10 dask_xgb_lockup.py
```
locks up pretty early (seconds, few minutes). Try multiple times!


file:///home/focht/Projects/NOI/Issues/xgboost_allreduce/dask_xgb_lockup.py

**Comment by trivialfis** [comment] 2023-05-02 14:52
Interestingly, this is only reproducible with the latest dask.

**Comment by trivialfis** [comment] 2023-05-02 16:05
also, only reproducible on xgb 1.7 but not on master.

**Comment by efocht** [comment] 2023-05-02 23:10
I was eager to test, but, uh, small testcase works, but the full case dies with the nightly build of xgboost :-(
```
  File "/venv/lib/python3.9/site-packages/xgboost/core.py", line 608, in inner_f
    return func(**kwargs)
  File "/venv/lib/python3.9/site-packages/xgboost/dask.py", line 331, in __init__
    self._init = client.sync(
  File "/venv/lib/python3.9/site-packages/distributed/utils.py", line 351, in sync
    return sync(
  File "/venv/lib/python3.9/site-packages/distributed/utils.py", line 418, in sync
    raise exc.with_traceback(tb)
  File "/venv/lib/python3.9/site-packages/distributed/utils.py", line 391, in f
    result = yield future
  File "/venv/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
  File "/venv/lib/python3.9/site-packages/xgboost/dask.py", line 445, in _map_local_data
    await distributed.wait(fut_parts)  # async wait for parts to be computed
  File "/venv/lib/python3.9/site-packages/distributed/client.py", line 5151, in _wait
    raise CancelledError(cancelled)
```

**Comment by efocht** [comment] 2023-05-03 11:48
> Interestingly, this is only reproducible with the latest dask.

I tried to find a dask version that works with xgboost 1.7.5 on this reproducer and wonder what you might have used. For me:

2023.4.1 - lockup
2023.4.0 - lockup
2023.3.2 - lockup
2023.3.1 - lockup
2023.3.0 - lockup
2023.2.1 - lockup
2023.2.0 - lockup
2023.1.1 - crash
2023.1.0 - crash
2022.12.1 - crash

Tested with `cpus=4`.

**Comment by trivialfis** [comment] 2023-05-04 16:48
Yes, should be applicable to 1.7.x as well. 1.6.x however, I'm not sure, haven't tried it.

**Comment by efocht** [comment] 2023-05-04 21:37
Applied on top of 1.7.5 and running the reproducer:
```
Compute Failed
Key:       dispatched_train-64682233-2ac3-4dd0-9221-959163c61136
Function:  dispatched_train
args:      ({'max_depth': 14, 'eta': 0.3, 'alpha': 0.0, 'reg_lambda': 1.0, 'gamma': 0.0, 'objective': 'rank:pairwise', 'scale_pos_weight': 1.0, 'colsample_bytree': 1, 'subsample': 1, 'min_child_weight': 1, 'booster': 'gbtree', 'tree_method': 'hist', 'max_bin': 256, 'seed': 42, 'nthread': 1, 'disable_default_eval_metric': 1, 'verbosity': 3, 'monotone_constraints': (1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
kwargs:    {}
xgboost.core.XGBoostError: [23:28:05] /xgboost/src/tree/hist/../split_evaluator.h:51: Check failed: p.monotone_constraints.size() <= n_features (500000 vs. 50) : The size of monotone constraint should be less or equal to the number of features.
```
This doesn't solve the lockup.
It stops early, but I don't understand, why.

**Comment by efocht** [comment] 2023-05-04 21:53
Oops, sorry, my previous comment was wrong. The reproducer wrongly created a tuple of length N (instead of M) for the constraints.  I removed it. Looks like the wrong reproducer somehow pointed to the right direction.

Reproducer runs 1000 rounds with #9122 applied on top of v1.7.5! Would you consider creating a bug fix release 1.7.6?

Still, something is odd: the number of monotonic constraints was only 4, in a tuple of length 50000. The tuple length was wrong,  but number of monotonic constraints was actually smaller than the number of features.

**Comment by efocht** [comment] 2023-05-05 00:11
Looks like I have a different problem with the large cases (1.7.5 + #9122 patch):
```
Sending large graph of size 33.72 GiB.
This may cause some slowdown.
Consider scattering data ahead of time and using futures.
Sending large graph of size 41.04 MiB.
This may cause some slowdown.
Consider scattering data ahead of time and using futures.
```
and
```
C 05-05-23 01:41:27 distributed.protocol.core.dumps:113 Failed to Serialize
Traceback (most recent call last):
  File "/home/focht/NOI/amb-dask/venv/lib/python3.9/site-packages/distributed/protocol/core.py", line 109, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "/home/focht/NOI/amb-dask/venv/lib/python3.9/site-packages/msgpack/__init__.py", line 38, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 294, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 300, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 297, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 202, in msgpack._cmsgpack.Packer._pack
ValueError: bytes object is too large
```

IIUC the message `Consider scattering data ahead of time and using futures.` is from dask and the splitting into delayed work bits / building task graph is mostly happening inside DaskDMatrix and surroundings. Is there anything I can do to avoid transferring the huge task graphs and do it bit by bit? Or is this all managed in xgboost/dask.py?

**Comment by trivialfis** [comment] 2023-05-05 08:52
XGBoost doesn't move data between workers. I don't have access to your large case, but based on the reproducer you shared, I think you might be loading/generating data on the client using numpy and then sending them to workers.

If my guess is correct, then you should change that to use dask instead of numpy. See https://xgboost.readthedocs.io/en/stable/tutorials/dask.html#memory-usage for additional comments.

**Comment by efocht** [comment] 2023-05-05 10:39
Thanks, but the data preparation is a large task and only partially parallel. It is irritating, though, that this works fine with xgboost 1.5.2 and 1.6.2. Something must have changed drastically in the way xgboost is doing lazy computation.

Maybe this is a misuse of this issue and my questions should move to another one or the xgboost discussion forum?

**Comment by trivialfis** [comment] 2023-05-05 10:45
I don't think xgboost has changed "drastically" in the dask interface. The basic workflow is still the same, along with the principle that xgboost doesn't move data. Meaning, no data serialization and hence no message pack involvement inside the training task.

**Comment by trivialfis** [comment] 2023-05-05 10:49
You might want to inspect the webui from dask/distributed to check where is the serialization coming from.

**Comment by trivialfis** [comment] 2023-05-05 14:14
Dask DMatrix is just a reference to the action data, there's no construction for it.

**Comment by efocht** [comment] 2023-05-05 15:04
I meant this:
```
class DaskDMatrix:
    """DMatrix holding on references to Dask DataFrame or Dask Array.  Constructing a
    `DaskDMatrix` forces all lazy computation to be carried out.  Wait for the input data
    explicitly if you want to see actual computation of constructing `DaskDMatrix`.
```

**Comment by trivialfis** [comment] 2023-08-09 08:23
Closing since the original issue was resolved.

**Closed by trivialfis** 2023-08-09 08:23 UTC
Labels: type: bug, Blocking
