### ISSUE TITLE
[External Memory Version] Check failed: batch.index != nullptr

### ISSUE THREAD

**Issue by MonsieurWave** [dmlc/xgboost#3375] opened 2018-06-10 18:10 UTC
Using the external memory version of the python implementation, I ran into the above error while testing on a test dataset (sparse, but not empty, see below). 
Similar to #1827, but not on spark, so I opened a new issue. 

Full Error output:
```
raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: b'[19:54:41] src/data/././sparse_batch_page.h:88: Check failed: batch.index != nullptr \n
\nStack trace returned 10 entries:
\n[bt] (0) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost4data16SparsePageSource6CreateEPN4dmlc6ParserIjEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x318a) [0x7fd7521b74da]
\n[bt] (1) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost7DMatrix6CreateEPN4dmlc6ParserIjEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x20b) [0x7fd7521d368b]
\n[bt] (2) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost7DMatrix4LoadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbbS8_+0xe33) [0x7fd7521d4d43]
\n[bt] (3) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(XGDMatrixCreateFromFile+0x1d0) [0x7fd7522a3240]\n[bt] (4) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c) [0x7fd773e12ec0]
\n[bt] (5) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call+0x22d) [0x7fd773e1287d]
\n[bt] (6) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fd774027dee]
\n[bt] (7) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12825) [0x7fd774028825]
\n[bt] (8) python(_PyObject_FastCallDict+0x8b) [0x55e1af2c11bb]\n[bt] (9) python(+0x19cd3e) [0x55e1af34ed3e]\n'
```
For other similar datasets, everything seems to work fine, so I speculated this might be caused by the sparsity of this testing dataset. 

To check if the dataset is indeed not empty I did:

```
In [1]: ls
dtest.r0-1.cache.row.page  dtrain.r0-1.cache  dtrain.r0-1.cache.row.page  fold_4_test.txt  fold_4_train.txt
In [2]: from scipy import *
In [3]: from sklearn.datasets import load_svmlight_file
In [4]: data = load_svmlight_file("fold_4_test.txt")
In [5]: sum(data[0])
Out[5]: 1173221413.3337207
In [6]: sum(data[1])
Out[6]: 19627.0
In [7]: data[0].shape
Out[7]: (4150265, 108)
In [8]: data[1].shape
Out[8]: (4150265,)
```
## Environment info
Operating System: Ubuntu 16.04.4 LTS
Package used: python xgboost package, installed with pip, as available of June 2018
Python: 3.6.4

**Comment by hcho3** [comment] 2018-07-04 21:42
Can you post the dataset you used to train the model?

**Comment by MonsieurWave** [comment] 2018-07-05 16:58
This is the part of the dataset where the problem occurs:
https://www.dropbox.com/s/rhyno7kx9g2tok9/Login.txt?dl=0

**Comment by MonsieurWave** [comment] 2018-07-05 17:06
This is the part of the dataset that causes the problem:
https://www.dropbox.com/s/7vfnj6caoam7vf6/fold_4_train.txt?dl=0

**Comment by MonsieurWave** [comment] 2018-08-02 00:56
Any news on this issue?

**Comment by hcho3** [comment] 2018-08-05 03:09
I'll take a look at it this weekend.

**Comment by hcho3** [comment] 2018-08-05 08:55
@MonsieurWave So far I am unable to re-produce the issue. Can you post your training script as well?

Here is my attempt:
```python
import xgboost as xgb 

dtrain = xgb.DMatrix('./fold_4_train.txt#dtrain.cache')
param = {'max_depth':2, 'eta':1, 'silent':1, 'objective':'binary:logistic'}
watchlist = [(dtrain, 'train')]
num_round = 2 
bst = xgb.train(param, dtrain, num_round, watchlist)
```

**Comment by MonsieurWave** [comment] 2018-08-06 19:32
@hcho3 : Thank you for your help!
Here is the part of my script responsible for training and which fails:

```
import os
import xgboost as xgb

params = {
    'base_score': 0.5,
    'booster': 'gbtree',
    'colsample_bylevel': 1,
    'colsample_bytree': 1,
    'eval_metric': 'auc',
    'gamma': 0.84,
    'learning_rate': 0.4,
    'max_delta_step': 0,
    'max_depth': 1,
    'min_child_weight': 10.0,
    'n_estimators': 999,
    'n_jobs': -1,
    'objective': 'binary:logistic',
    'random_state': 0,
    'reg_alpha': 0.8671463346569078,
    'reg_lambda': 0.5916603334004378,
    'scale_pos_weight': 1,
    'silent': True,
    'subsample': 0.7925462136041614,
    'tree_method': 'hist'
}

n_estimators = params['n_estimators']

iteration_dir = './'
ext_mem_extension = '.txt'
fold = 'fold_1'

fold_dir = os.path.join(iteration_dir, fold)

dtrain = xgb.DMatrix(os.path.join(fold_dir, fold + '_train' + ext_mem_extension)
    + '#' + os.path.join(fold_dir, 'dtrain.cache'))
dtest = xgb.DMatrix(os.path.join(fold_dir, fold + '_test' + ext_mem_extension)
    + '#' + os.path.join(fold_dir, 'dtest.cache'))

trained_model = xgb.train(params, dtrain,
    num_boost_round = n_estimators,
    evals = [(dtest, 'Test')],
    early_stopping_rounds = 30,
    verbose_eval = False)
```

Here is the associated data again:
https://www.dropbox.com/sh/iu9evsluagxsu68/AABXOIqn8XrxepcKcacsPYxNa?dl=0

**Comment by hcho3** [comment] 2018-08-08 00:11
@MonsieurWave I was still unable to re-produce the error, even with your script.

**Comment by MonsieurWave** [comment] 2018-08-08 06:48
@hcho3 : That is strange.
I have reinstalled from source the latest master as specified [here](https://github.com/dmlc/xgboost/tree/master/python-package), however it is still failing with the same error, although the error output has changed slightly. 

Here is the full output upon execution of the script now:

```
python temp.py 
[08:43:42] 288958x109 matrix with 21589322 entries loaded from /home/user/data/working_data/saved_data/old_CV_10_folds/iteration_0/fold_1/fold_1_train.txt#/home/user/data/working_data/saved_data/old_CV_10_folds/iteration_0/fold_1/dtrain.cache
[08:43:47] Writing row.page to /home/user/data/working_data/saved_data/old_CV_10_folds/iteration_0/fold_1/dtest.cache in 14.1066 MB/s, 64 written
[08:43:52] Writing row.page to /home/user/data/working_data/saved_data/old_CV_10_folds/iteration_0/fold_1/dtest.cache in 16.8679 MB/s, 160 written
[08:43:55] Writing row.page to /home/user/data/working_data/saved_data/old_CV_10_folds/iteration_0/fold_1/dtest.cache in 17.3135 MB/s, 224 written
[08:44:02] SparsePage::Writer Finished writing to /home/user/data/working_data/saved_data/old_CV_10_folds/iteration_0/fold_1/dtest.cache.row.page
Traceback (most recent call last):
  File "temp.py", line 39, in <module>
    + '#' + os.path.join(fold_dir, 'dtest.cache'))
  File "/home/user/anaconda3/envs/stroke-predict/lib/python3.6/site-packages/xgboost-0.72-py3.6.egg/xgboost/core.py", line 357, in __init__
    ctypes.byref(self.handle)))
  File "/home/user/anaconda3/envs/stroke-predict/lib/python3.6/site-packages/xgboost-0.72-py3.6.egg/xgboost/core.py", line 151, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: b'[08:43:56] include/xgboost/data.h:205: Check failed: batch.index != nullptr \n\nStack trace returned 10 entries:\n[bt] (0) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/site-packages/xgboost-0.72-py3.6.egg/xgboost/./lib/libxgboost.so(dmlc::StackTrace[abi:cxx11]()+0x56) [0x7f4c925d75a6]\n[bt] (1) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/site-packages/xgboost-0.72-py3.6.egg/xgboost/./lib/libxgboost.so(xgboost::data::SparsePageSource::Create(dmlc::Parser<unsigned int, float>*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x1bd4) [0x7f4c926ad5f4]\n[bt] (2) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/site-packages/xgboost-0.72-py3.6.egg/xgboost/./lib/libxgboost.so(xgboost::DMatrix::Create(dmlc::Parser<unsigned int, float>*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x11b) [0x7f4c926ca41b]\n[bt] (3) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/site-packages/xgboost-0.72-py3.6.egg/xgboost/./lib/libxgboost.so(xgboost::DMatrix::Load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x883) [0x7f4c926cad43]\n[bt] (4) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/site-packages/xgboost-0.72-py3.6.egg/xgboost/./lib/libxgboost.so(XGDMatrixCreateFromFile+0x15e) [0x7f4c9277dcde]\n[bt] (5) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c) [0x7f4ca913eec0]\n[bt] (6) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call+0x22d) [0x7f4ca913e87d]\n[bt] (7) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7f4ca9353dee]\n[bt] (8) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12825) [0x7f4ca9354825]\n[bt] (9) python(_PyObject_FastCallDict+0x8b) [0x5612b07b41bb]\n\n'
Exception ignored in: <bound method DMatrix.__del__ of <xgboost.core.DMatrix object at 0x7f4ca957e048>>
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/stroke-predict/lib/python3.6/site-packages/xgboost-0.72-py3.6.egg/xgboost/core.py", line 483, in __del__
    _check_call(_LIB.XGDMatrixFree(self.handle))
  File "/home/user/anaconda3/envs/stroke-predict/lib/python3.6/site-packages/xgboost-0.72-py3.6.egg/xgboost/core.py", line 151, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: b'[08:44:02] src/c_api/c_api.cc:714: DMatrix/Booster has not been intialized or has already been disposed.\n\nStack trace returned 10 entries:\n[bt] (0) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/site-packages/xgboost-0.72-py3.6.egg/xgboost/./lib/libxgboost.so(dmlc::StackTrace[abi:cxx11]()+0x56) [0x7f4c925d75a6]\n[bt] (1) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/site-packages/xgboost-0.72-py3.6.egg/xgboost/./lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x28) [0x7f4c925d7cb8]\n[bt] (2) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/site-packages/xgboost-0.72-py3.6.egg/xgboost/./lib/libxgboost.so(XGDMatrixFree+0xf7) [0x7f4c92776787]\n[bt] (3) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c) [0x7f4ca913eec0]\n[bt] (4) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call+0x22d) [0x7f4ca913e87d]\n[bt] (5) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7f4ca9353dee]\n[bt] (6) /home/user/anaconda3/envs/stroke-predict/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12825) [0x7f4ca9354825]\n[bt] (7) python(_PyObject_FastCallDict+0x8b) [0x5612b07b41bb]\n[bt] (8) python(+0x19cd3e) [0x5612b0841d3e]\n[bt] (9) python(_PyEval_EvalFrameDefault+0x30a) [0x5612b086619a]\n\n'
```

Complete environment:
xgboost version : 0.72
Python 3.6.4 with Anaconda 3
OS: Ubuntu 16.04.4 LTS

**Comment by MonsieurWave** [comment] 2018-08-08 08:54
I have just tested on my local system, and it works fine there. Unfortunately running all the data locally is not an option for me...

xgboost version: 0.72
Python 3.6.4
OS: Mac OS X 10.13.6, Darwin Kernel Version 17.7.0

**Comment by MonsieurWave** [comment] 2018-08-08 22:27
Have just tried on an Arch machine, where the same error occurs:
xgboost version: 0.72.1
Python 3.6.5 with Anaconda3
OS Kernel: Linux 4.16.11-1-ARCH

**Comment by hcho3** [comment] 2018-08-09 21:51
@MonsieurWave I tried your script on an EC2 instance with Ubuntu 16.04 and I couldn't reproduce the error. Without re-producing the error on my end, I cannot fix it.

Can you create either a VM image (VirtualBox) or AMI (on EC2) where the error is triggered?

**Comment by hcho3** [comment] 2018-08-30 01:29
@MonsieurWave Any update on this?

**Comment by MonsieurWave** [comment] 2018-08-30 06:16
@hcho3 : I have not been able to reproduce the issue on a VMI launched from a local Mac, but the issue persists on all my linux servers. Will try to launch a VMI from there to see if it is hardware related.

**Comment by hcho3** [comment] 2018-09-23 06:39
@MonsieurWave Any update?

**Comment by hcho3** [comment] 2018-10-09 23:16
Closing for now. Re-open it if you have any update.

**Closed by hcho3** 2018-10-09 23:16 UTC
