### ISSUE TITLE
Pandas 0.24 sparse restructure breaking _maybe_pandas_data()

### ISSUE THREAD

**Issue by r-archer37** [dmlc/xgboost#4648] opened 2019-07-08 20:48 UTC
Background: https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.24.0.html#sparse-data-structure-refactor

Summary: As of 0.24 sparse datatypes in pandas dataframes are represented like Sparse[int64, 0], which xgboost does not recognize as numeric.

Detail: In core._maybe_pandas_data() there is a loop that checks whether each column's dtype.name is in a hardcoded set of dtypes ( https://github.com/dmlc/xgboost/blob/cd1526d3b1155432fca82e8b4895bc0b827b4d29/python-package/xgboost/core.py#L220 ). Because Pandas changed Sparse dtypes to have a name that doesn't match these, the check now fails on any sparse column. What is looked for is now represented in that column's dtype.subtype.

Possible solutions:
1 - Look at the dtype.name or dtype.subtype depending on whether the name starts with "Sparse"
2 - Instead of enumerating the acceptable datatypes, check each column with pd.api.types.is_numeric_dtype() and .is_bool_dtype()

**Comment by hcho3** [comment] 2019-07-24 17:17
@sriramch @rongou This may be related to why python-cpu tests are failing with
```
UnboundLocalError: local variable 'arith_flex' referenced before assignment
/opt/python/lib/python3.7/site-packages/pandas/core/ops/__init__.py:719: UnboundLocalError
```
https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-4697/3/pipeline

**Comment by sriramch** [comment] 2019-07-24 17:38
@hcho3 it looks like pandas 0.24 was released in jan, 2019. why are we seeing build breakages only now? isn't it possible to pin to a particular (stable) version of these dependent packages and only upgrade after we have tested with it?

**Comment by trivialfis** [comment] 2019-07-24 17:55
@sriramch We usually follows the upstream as we don't expect pip users to  handle dependencies themselves.

**Comment by rongou** [comment] 2019-07-24 18:13
@hcho3 hmm I cannot reproduce the error locally. Not sure how the CI machines are set up, could the `.pytest_cache` directory be messed up?

**Comment by hcho3** [comment] 2019-07-24 18:21
@rongou Try upgrading Pandas?

**Comment by trivialfis** [comment] 2019-07-24 18:30
Actually I can't reproduce it either.

**Comment by trivialfis** [comment] 2019-07-24 18:30
Error on test farm

**Comment by hcho3** [comment] 2019-07-24 18:35
Hmm, I cannot reproduce the error myself, even after upgrading Pandas. Let me look at the Docker container

**Comment by rongou** [comment] 2019-07-24 19:18
I ran it using docker with the ci command:
```
tests/ci_build/ci_build.sh cpu docker tests/ci_build/test_python.sh cpu
```

**Closed** 2020-03-20 13:40 UTC
