### ISSUE TITLE
Recipe for target 'lib/libxgboost.so' failed 

### ISSUE THREAD

**Issue by SachinKalsi** [dmlc/xgboost#3302] opened 2018-05-08 16:42 UTC
I am getting the following error. Please help

```
makefile:173: recipe for target 'xgboost' failed 
make: *** [xgboost] Error 1 
make: *** Waiting for unfinished jobs.... 
Makefile:164: recipe for target 'lib/libxgboost.so' failed
```

## Environment info
Operating System: Ubuntu 16.04

Compiler: gcc 5.4

Package used (python/R/jvm/C++): python

`xgboost` version used: 0.71

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`): b8a0d66fe6f9f8acc3b27afa81d2fc8ef074633d

. the gcc version and distribution: gcc 5.4

If you are using python package, please provide

1. The python version and distribution: 3.6.5 Anaconda
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1. git clone --recursive https://github.com/dmlc/xgboost
2. cd xgboost; make -j4

## What have you tried?

1. git clone --recursive https://github.com/dmlc/xgboost
2. cd xgboost; make -j4

**Comment by hcho3** [comment] 2018-05-10 22:18
Can you post the full compiler error? The message `recipe for target 'xgboost' failed` doesn't have enough information for us to act on it.

**Comment by hcho3** [comment] 2018-05-23 18:54
@SachinKalsi The `rabit` submodule ([dmlc/rabit](https://github.com/dmlc/rabit)) failed to compile because, on your system, the compiler flag `-msse2` is not supported. Are you using an ARM processor?

Currently, xgboost points to an old version of `rabit`, which had `-msse2` hard-coded in its build. Latest version of `rabit` does not have this problem. For now, you should update `rabit` by running
```
cd rabit
git pull origin master
```

**Comment by hcho3** [comment] 2018-05-23 18:56
Closing this as it is a duplicate of #3075, #3244.

**Closed by hcho3** 2018-05-23 18:56 UTC

**Comment by SachinKalsi** [comment] 2018-05-24 05:29
@hcho3 : No, I am using INTEL. I had to  remove `-msse2 ` option from the Makefile to make `xgboost` compile successfully. I also did try what you suggested & it was compiling successfully too.
Thanks for the heads up.
