### ISSUE TITLE
xgboost.core.XGBoostError: [17:36:22] C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:956: Check failed: header == serialisation_header_: 

### ISSUE THREAD

**Issue by 761100192** [dmlc/xgboost#7093] opened 2021-07-08 09:44 UTC
how can i solve this problem?
python version:3.7.6
xgboost version:1.4.2
platform version:windows 10

**Comment by trivialfis** [comment] 2021-07-08 11:33
Could you please provide a way for us to reproduce?  Or at least describe what you are trying to do, like where did you get the model and where are you loading it into?

**Comment by trivialfis** [comment] 2021-09-16 20:43
Closing as this likely caused by loading a pickle with `load_model`.  Feel free to reopen if there's a reproducible example.

**Closed by trivialfis** 2021-09-16 20:43 UTC
Labels: status: need update
