### ISSUE TITLE
[jvm-packages] xgboost saving model issue 

### ISSUE THREAD

**Issue by anayyar82** [dmlc/xgboost#4399] opened 2019-04-24 18:10 UTC
While doing `xgboostModel.write.overwrite().save(persistedModelPath)` with Spark 2.4, it;s throwing below error:

val xgbParam = Map("eta" -> 0.1,
                   "max_depth" -> 1,
                   "objective" -> "binary:logistic",
                   "scale_pos_weight" -> 1.0,
                   "subsample" -> 0.9,
                   "num_round" -> 1,
                   "num_workers" -> 10)

Although I have built new library from master. 

java.lang.NoSuchMethodError: org.json4s.jackson.JsonMethods$.parse(Lorg/json4s/JsonInput;Z)Lorg/json4s/JsonAST$JValue;
	at ml.dmlc.xgboost4j.scala.spark.params.DefaultXGBoostParamsWriter$$anonfun$1$$anonfun$3.apply(DefaultXGBoostParamsWriter.scala:73)
	at ml.dmlc.xgboost4j.scala.spark.params.DefaultXGBoostParamsWriter$$anonfun$1$$anonfun$3.apply(DefaultXGBoostParamsWriter.scala:71)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at ml.dmlc.xgboost4j.scala.spark.params.DefaultXGBoostParamsWriter$$anonfun$1.apply(DefaultXGBoostParamsWriter.scala:71)
	at ml.dmlc.xgboost4j.scala.spark.params.DefaultXGBoostParamsWriter$$anonfun$1.apply(DefaultXGBoostParamsWriter.scala:69)
	at scala.Option.getOrElse(Option.scala:121)
	at ml.dmlc.xgboost4j.scala.spark.params.DefaultXGBoostParamsWriter$.getMetadataToSave(DefaultXGBoostParamsWriter.scala:69)
	at ml.dmlc.xgboost4j.scala.spark.params.DefaultXGBoostParamsWriter$.saveMetadata(DefaultXGBoostParamsWriter.scala:51)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel$XGBoostClassificationModelWriter.saveImpl(XGBoostClassifier.scala:489)
	at org.apache.spark.ml.util.MLWriter.save(ReadWrite.scala:180)
	at line97b49585f2c44bcba235c0708311800a50.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4187162596918397:2)
	at line97b49585f2c44bcba235c0708311800a50.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-4187162596918397:56)
	at line97b49585f2c44bcba235c0708311800a50.$read$$iw$$iw$$iw$$iw.<init>(command-4187162596918397:58)
	at line97b49585f2c44bcba235c0708311800a50.$read$$iw$$iw$$iw.<init>(command-4187162596918397:60)
	at line97b49585f2c44bcba235c0708311800a50.$read$$iw$$iw.<init>(command-4187162596918397:62)
	at line97b49585f2c44bcba235c0708311800a50.$read$$iw.<init>(command-4187162596918397:64)

**Comment by hcho3** [comment] 2019-04-24 18:15
@anayyar82 It looks like your Java project is using a version of json4s that clashes with the json4s version used in Apache Spark. See json4s#212. Can you run `mvn dependency:tree -Dverbose` to see which versions of json4s is being used?

**Comment by CodingCat** [comment] 2019-04-24 18:17
And ensure that you’re using 2.4.1 to submit your xgboost application

**Comment by anayyar82** [comment] 2019-04-24 18:22
Sure trying it.

**Comment by anayyar82** [comment] 2019-04-24 18:26
With latest version xgboost, with spark 2.4.1 now it's failing with below exception while calling `fit` method.  It was working before and I did the test too. 

ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$postTrackerReturnProcessing(XGBoost.scala:573)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$2.apply(XGBoost.scala:450)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$2.apply(XGBoost.scala:426)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:425)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:198)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:48)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
	at linee556933e8282494a95d073010bf6bca850.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:1)
	at linee556933e8282494a95d073010bf6bca850.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:67)
	at linee556933e8282494a95d073010bf6bca850.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:69)
	at linee556933e8282494a95d073010bf6bca850.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:71)
	at linee556933e8282494a95d073010bf6bca850.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:73)
	at linee556933e8282494a95d073010bf6bca850.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:75)
	at linee556933e8282494a95d073010bf6bca850.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:77)
	at linee556933e8282494a95d073010bf6bca850.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:79)
	at linee556933e8282494a95d073010bf6bca850.$read$$iw$$iw$$iw$$iw.<init>(command-784893:81)
	at linee556933e8282494a95d073010bf6bca850.$read$$iw$$iw$$iw.<init>(command-784893:83)
	at linee556933e8282494a95d073010bf6bca850.$read$$iw$$iw.<init>(command-784893:85)
	at linee556933e8282494a95d073010bf6bca850.$read$$iw.<init>(command-784893:87)

**Comment by hcho3** [comment] 2019-04-24 18:30
> It was working before and I did the test too

What changed?

**Comment by anayyar82** [comment] 2019-04-24 18:59
Not sure, I just reran all and it's working but somehow in spark 2.4.1 while loading back it's giving same error. 

val reloadedModel = XGBoostClassifier.load(xgbClassificationModelPath)


java.lang.NoSuchMethodError: org.json4s.jackson.JsonMethods$.parse(Lorg/json4s/JsonInput;Z)Lorg/json4s/JsonAST$JValue;
	at ml.dmlc.xgboost4j.scala.spark.params.CustomObjParam.jsonDecode(CustomParams.scala:82)
	at ml.dmlc.xgboost4j.scala.spark.params.CustomObjParam.jsonDecode(CustomParams.scala:66)
	at org.apache.spark.ml.util.DefaultParamsReader$Metadata$$anonfun$setParams$1.apply(ReadWrite.scala:592)
	at org.apache.spark.ml.util.DefaultParamsReader$Metadata$$anonfun$setParams$1.apply(ReadWrite.scala:589)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.apache.spark.ml.util.DefaultParamsReader$Metadata.setParams(ReadWrite.scala:589)
	at org.apache.spark.ml.util.DefaultParamsReader$Metadata.getAndSetParams(ReadWrite.scala:577)
	at org.apache.spark.ml.util.DefaultParamsReader.load(ReadWrite.scala:497)
	at org.apache.spark.ml.util.MLReadable$class.load(ReadWrite.scala:380)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier$.load(XGBoostClassifier.scala:214)
	at line875d92e52099431d88ffb63bb452de1150.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4168297690318804:1)
	at line875d92e52099431d88ffb63bb452de1150.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4168297690318804:63)
	at line875d92e52099431d88ffb63bb452de1150.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4168297690318804:65)
	at line875d92e52099431d88ffb63bb452de1150.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4168297690318804:67)
	at line875d92e52099431d88ffb63bb452de1150.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4168297690318804:69)
	at line875d92e52099431d88ffb63bb452de1150.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4168297690318804:71)
	at line875d92e52099431d88ffb63bb452de1150.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4168297690318804:73)
	at line875d92e52099431d88ffb63bb452de1150.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-4168297690318804:75)
	at line875d92e52099431d88ffb63bb452de1150.$read$$iw$$iw$$iw$$iw.<init>(command-4168297690318804:77)
	at line875d92e52099431d88ffb63bb452de1150.$read$$iw$$iw$$iw.<init>(command-4168297690318804:79)
	at line875d92e52099431d88ffb63bb452de1150.$read$$iw$$iw.<init>(command-4168297690318804:81)
	at line875d92e52099431d88ffb63bb452de1150.$read$$iw.<init>(command-4168297690318804:83)
	at line875d92e52099431d88ffb63bb452de1150.$read.<init>(command-4168297690318804:85)
	at line875d92e52099431d88ffb63bb452de1150.$read$.<init>(command-4168297690318804:89)
	at line875d92e52099431d88ffb63bb452de1150.$read$.<clinit>(command-4168297690318804)
	at line875d92e52099431d88ffb63bb452de1150.$eval$.$print$lzycompute(<notebook>:7)
	at line875d92e52099431d88ffb63bb452de1150.$eval$.$print(<notebook>:6)
	at line875d92e52099431d88ffb63bb452de1150.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:199)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply$mcV$sp(ScalaDriverLocal.scala:190)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:190)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:190)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:590)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:545)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:190)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:323)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:303)
	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:235)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:230)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:47)
	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:268)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:47)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:303)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:591)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:591)
	at scala.util.Try$.apply(Try.scala:192)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:586)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:477)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:544)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:383)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:330)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:216)
	at java.lang.Thread.run(Thread.java:748)

**Comment by anayyar82** [comment] 2019-04-24 19:00
Can we update the pom file or build file to use old JSON

**Comment by hcho3** [comment] 2019-04-24 19:04
@anayyar82 Did you run `mvn dependency:tree -Dverbose`?

**Comment by anayyar82** [comment] 2019-04-24 20:34
Yes, here is the output


[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ xgboost4j ---
[INFO] ml.dmlc:xgboost4j:jar:0.83-SNAPSHOT
[INFO] +- junit:junit:jar:4.11:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- com.typesafe.akka:akka-actor_2.11:jar:2.3.11:compile
[INFO] |  +- (org.scala-lang:scala-library:jar:2.11.5:compile - omitted for conflict with 2.11.12)
[INFO] |  \- com.typesafe:config:jar:1.2.1:compile
[INFO] +- com.typesafe.akka:akka-testkit_2.11:jar:2.3.11:test
[INFO] |  +- (org.scala-lang:scala-library:jar:2.11.5:test - omitted for duplicate)
[INFO] |  \- (com.typesafe.akka:akka-actor_2.11:jar:2.3.11:test - omitted for duplicate)
[INFO] +- com.esotericsoftware.kryo:kryo:jar:2.21:compile
[INFO] |  +- com.esotericsoftware.reflectasm:reflectasm:jar:shaded:1.07:compile
[INFO] |  |  \- org.ow2.asm:asm:jar:4.0:compile
[INFO] |  +- com.esotericsoftware.minlog:minlog:jar:1.2:compile
[INFO] |  \- org.objenesis:objenesis:jar:1.2:compile
[INFO] +- org.scala-lang:scala-compiler:jar:2.11.12:compile
[INFO] |  +- (org.scala-lang:scala-library:jar:2.11.12:compile - omitted for conflict with 2.11.5)
[INFO] |  +- (org.scala-lang:scala-reflect:jar:2.11.12:compile - omitted for duplicate)
[INFO] |  +- org.scala-lang.modules:scala-xml_2.11:jar:1.0.5:compile
[INFO] |  |  \- (org.scala-lang:scala-library:jar:2.11.7:compile - omitted for conflict with 2.11.5)
[INFO] |  \- org.scala-lang.modules:scala-parser-combinators_2.11:jar:1.0.4:compile
[INFO] |     \- (org.scala-lang:scala-library:jar:2.11.6:compile - omitted for conflict with 2.11.5)
[INFO] +- org.scala-lang:scala-reflect:jar:2.11.12:compile
[INFO] |  \- (org.scala-lang:scala-library:jar:2.11.12:compile - omitted for conflict with 2.11.5)
[INFO] +- org.scala-lang:scala-library:jar:2.11.12:compile
[INFO] +- commons-logging:commons-logging:jar:1.2:compile
[INFO] \- org.scalatest:scalatest_2.11:jar:3.0.0:test
[INFO]    +- (org.scala-lang:scala-library:jar:2.11.8:test - omitted for conflict with 2.11.12)
[INFO]    +- org.scalactic:scalactic_2.11:jar:3.0.0:test
[INFO]    |  +- (org.scala-lang:scala-library:jar:2.11.8:test - omitted for conflict with 2.11.12)
[INFO]    |  \- (org.scala-lang:scala-reflect:jar:2.11.8:test - omitted for conflict with 2.11.12)
[INFO]    +- (org.scala-lang:scala-reflect:jar:2.11.8:test - omitted for conflict with 2.11.12)
[INFO]    +- (org.scala-lang.modules:scala-xml_2.11:jar:1.0.5:test - omitted for duplicate)
[INFO]    \- (org.scala-lang.modules:scala-parser-combinators_2.11:jar:1.0.4:test - omitted for duplicate)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.044 s
[INFO] Finished at: 2019-04-24T20:33:44Z
[INFO] ------------------------------------------------------------------------

**Comment by anayyar82** [comment] 2019-04-24 20:54
@hcho3 I am pretty sure we have an issue with `xgboost4j-spark-0.83-SNAPSHOT.jar`

As I do see below issue many times it's throwing randomly. Nothing changed and rebuilt twice. 

`val xgbClassificationModel = xgbClassifier.fit(xgbInput)`


ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$postTrackerReturnProcessing(XGBoost.scala:573)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$2.apply(XGBoost.scala:450)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$2.apply(XGBoost.scala:426)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:425)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:198)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:48)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
	at line70541e7ef73146f88133381836b3a6bd50.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:1)
	at line70541e7ef73146f88133381836b3a6bd50.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:67)
	at line70541e7ef73146f88133381836b3a6bd50.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:69)
	at line70541e7ef73146f88133381836b3a6bd50.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:71)
	at line70541e7ef73146f88133381836b3a6bd50.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:73)
	at line70541e7ef73146f88133381836b3a6bd50.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:75)
	at line70541e7ef73146f88133381836b3a6bd50.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:77)
	at line70541e7ef73146f88133381836b3a6bd50.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:79)
	at line70541e7ef73146f88133381836b3a6bd50.$read$$iw$$iw$$iw$$iw.<init>(command-784893:81)
	at line70541e7ef73146f88133381836b3a6bd50.$read$$iw$$iw$$iw.<init>(command-784893:83)

**Comment by anayyar82** [comment] 2019-04-24 20:54
the same code is working in 0.82 but not working with the latest build.

**Comment by hcho3** [comment] 2019-04-24 22:36
@anayyar82 Can you try this JAR? [xgboost4j-spark-0.83-SNAPSHOT.jar.zip](https://github.com/dmlc/xgboost/files/3114418/xgboost4j-spark-0.83-SNAPSHOT.jar.zip)
I built it as part of my work in #4380.

**Comment by anayyar82** [comment] 2019-04-24 22:41
Of Course

**Comment by hcho3** [comment] 2019-04-24 22:43
Just in case, I'm uploading all JARs files I built: [jars.zip](https://github.com/dmlc/xgboost/files/3114432/jars.zip)

**Comment by anayyar82** [comment] 2019-04-24 22:47
@hcho3 it failed with same error..

Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=10.205.254.245, DMLC_TRACKER_PORT=9091, DMLC_NUM_WORKER=1}
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$postTrackerReturnProcessing(XGBoost.scala:573)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$2.apply(XGBoost.scala:450)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$2.apply(XGBoost.scala:426)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:425)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:198)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:48)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
	at line516db36797d5452fba417ee43cf4fc6048.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:1)
	at line516db36797d5452fba417ee43cf4fc6048.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:67)
	at line516db36797d5452fba417ee43cf4fc6048.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:69)
	at line516db36797d5452fba417ee43cf4fc6048.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:71)
	at line516db36797d5452fba417ee43cf4fc6048.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:73)
	at line516db36797d5452fba417ee43cf4fc6048.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:75)
	at line516db36797d5452fba417ee43cf4fc6048.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:77)
	at line516db36797d5452fba417ee43cf4fc6048.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-784893:79)
	at line516db36797d5452fba417ee43cf4fc6048.$read$$iw$$iw$$iw$$iw.<init>(command-784893:81)
	at line516db36797d5452fba417ee43cf4fc6048.$read$$iw$$iw$$iw.<init>(command-784893:83)
	at line516db36797d5452fba417ee43cf4fc6048.$read$$iw$$iw.<init>(command-784893:85)
	at line516db36797d5452fba417ee43cf4fc6048.$read$$iw.<init>(command-784893:87)
	at line516db36797d5452fba417ee43cf4fc6048.$read.<init>(command-784893:89)
	at line516db36797d5452fba417ee43cf4fc6048.$read$.<init>(command-784893:93)
	at line516db36797d5452fba417ee43cf4fc6048.$read$.<clinit>(command-784893)
	at line516db36797d5452fba417ee43cf4fc6048.$eval$.$print$lzycompute(<notebook>:7)
	at line516db36797d5452fba417ee43cf4fc6048.$eval$.$print(<notebook>:6)
	at line516db36797d5452fba417ee43cf4fc6048.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:199)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply$mcV$sp(ScalaDriverLocal.scala:190)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:190)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:190)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:590)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:545)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:190)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:323)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:303)
	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:235)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:230)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:47)
	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:268)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:47)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:303)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:591)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:591)
	at scala.util.Try$.apply(Try.scala:192)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:586)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:477)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:544)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:383)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:330)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:216)
	at java.lang.Thread.run(Thread.java:748)

**Comment by hcho3** [comment] 2019-04-24 22:48
@CodingCat Have you seen this error before? I have no idea.

**Comment by CodingCat** [comment] 2019-04-25 00:10
cannot reproduce ...and please try to get rid of databricks wrapper and use spark-submit to test,

**Comment by anayyar82** [comment] 2019-04-29 15:44
Thanks @hcho3 , it's working fine now. 

I can save and load it with Spark 2.4 without any issue. 

The new issue is when I want to do reload and use the transform method, it says 


val reloadedModel = XGBoostClassifier.load(xgbClassificationModelPath)
reloadedModel.transform(xgbInput.select("features"))

**error: value transform is not a member of ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier**

Any idea why it so?

**Comment by hcho3** [comment] 2019-04-30 16:34
@anayyar82 Did you follow instructions at https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html#model-and-pipeline-persistence ?

**Comment by hcho3** [comment] 2019-05-06 18:31
Closing for now

**Closed by hcho3** 2019-05-06 18:31 UTC

**Comment by agiulietti** [comment] 2019-05-15 11:12
Hi, it is not clear for me how the issue was resolved. I've got the same problem when trying to save the xgboost4j model using Scala 2.11 and Spark 2.4.0: 

**java.lang.NoSuchMethodError: org.json4s.jackson.JsonMethods$.parse(Lorg/json4s/JsonInput;Z)Lorg/json4s/JsonAST$JValue**

When trying to use either the 0.83 or 0.82 JAR snapshots provided (thanks) I get an error when trying to create the classifier:

**java.lang.NoClassDefFoundError: ml/dmlc/xgboost4j/scala/ObjectiveTrait**

Any help would be much appreciated.

**Comment by CodingCat** [comment] 2019-05-16 02:03
For all class not found error, check if you messed up scala 2.11/2.12

For all jackson related thing, 2.4 spark is not supported in any way
