### ISSUE TITLE
Why does loading another model require reloading DMatrix ???

### ISSUE THREAD

**Issue by calvin89029** [dmlc/xgboost#8899] opened 2023-03-11 04:11 UTC
I'm using `xgboost 1.7.1` and the source code is as follows. The performance of the model is exactly the same before and after loading another model. 

```python
import xgboost as xgb
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import top_k_accuracy_score

data = load_digits()
X_train, X_val, y_train, y_val = train_test_split(data['data'], data['target'], test_size=.3)

dtrain = xgb.DMatrix(X_train, y_train)
dval = xgb.DMatrix(X_val)

param = {
        "objective": "multi:softprob",
        "eta": 0.1,
        "max_depth": 8,
        "nthread": 16,
        "num_parallel_tree": 1,
        "subsample": 1,
        "tree_method": "hist",
        "num_class":10
    }
num_local_round = 1
                 
bst = xgb.train(param, dtrain, num_boost_round=1)

y = bst.predict(dval)
print (top_k_accuracy_score(y_val, y, k=1)). #0.822222

bst.load_model("another_model.json")
y = bst.predict(dval)
print (top_k_accuracy_score(y_val, y, k=1)) #0.82222 Always the same as the previous
```

However, if I add one line `dval = xgb.DMatrix(X_val)`  to reload `dval` from `X_val` between the first `predict` and the second `predict`. The output change?
```python
bst = xgb.train(param, dtrain, num_boost_round=1)

y = bst.predict(dval)
print (top_k_accuracy_score(y_val, y, k=1)). #0.822222

dval = xgb.DMatrix(X_val) # <--- add this line
bst.load_model("another_model.json")
y = bst.predict(dval)
print (top_k_accuracy_score(y_val, y, k=1)) #0.866666 Different now
```
I don't understand why there is a difference between the above two, did I misunderstand something?

**Comment by trivialfis** [comment] 2023-03-11 07:50
This is probably caused by running prediction on histogram index where some of the values got assigned to the minimum bins. Will look into it.

**Comment by trivialfis** [comment] 2023-03-11 16:53
Hi, could you please specify the `random_state` for the `train_test_split` and make sure it's consistent across multiple runs?

**Comment by calvin89029** [comment] 2023-03-12 01:55
Hi @trivialfis , both experiments were indeed run on the same random_state.
I rerun the experiment on random_state=0. The values are 0.86296, 0.86296 and 0.86296, 0.91481.
Same result!

**Comment by trivialfis** [comment] 2023-03-12 07:03
Thank you for sharing. For now, please recreate the booster object before calling load model.

**Comment by calvin89029** [comment] 2023-03-12 10:32
@trivialfis Recreate booster avoids the issue 0.86296, 0.91481.

**Comment by trivialfis** [comment] 2023-03-12 10:51
Thank you for confirming. The prediction result is cached within the booster, but a loading model from file doesn't clear the cache. I need to figure out a way to bound the life time of this cache.

**Closed** 2023-03-14 14:09 UTC
Labels: type: bug
