### ISSUE TITLE
Non-default eval metrics and multi-output with the Python sklearn API

### ISSUE THREAD

**Issue by PepppoVal** [dmlc/xgboost#8473] opened 2022-11-18 14:25 UTC
BUG REPORT:
I am using XGBoost multi-output feature with v.1.7.1 of the python package.
It works just fine when I run the following:

```
clf = xgb.XGBClassifier(tree_method="hist", enable_categorical=True, n_estimators=500,
                        verbosity = 1, early_stopping_rounds=10,
                        importance_type='gain', 
                        # eval_metric=hamming_loss
                       )
clf.fit(ml_X_train, ml_y_train, eval_set=[(ml_X_val, ml_y_val)])

```
The above runs and does early stopping beautifully, all the while showing  **logloss** decreasing (the default metric, I assume)
BUT as soon as I try to use another metric, within the `sklearn.metric` package, such as `hamming_loss`
or `accuracy_score`, which are supposedly good and valid for evaluating multi-output algorithms, I get the following error:
**ValueError: Found input variables with inconsistent numbers of samples: [1877576, 234697]**
which is thrown by **sklearn** in file **validation.py**

**Note that 1877576 = 234697 * 8** 
and that `ml_y_val` passed into the `eval_set` above contains exactly 234697 rows and 8 columns (8 labels for my multi-output classification task)
My best guess is that the data is passed into the sklearn code for evaluating the metric somehow in an incorrect way. 

I see that there is a caveat on the multi-output tutorial saying that the support for metrics is still incomplete, but I would like nevertheless to point this out. Thanks for your attention

**Comment by trivialfis** [comment] 2022-11-21 07:29
Thank you for raising the issue. We are aware of the limitation, this error is caused by the `get_label` function from `DMatrix`, which doesn't support matrix label yet.

**Comment by trivialfis** [comment] 2022-11-21 09:01
We are still planning for some of the new features regarding multi-target. For instance, the label can be sparse for multi-label classification, we need to pen out a new set of API functions to handle these new data types.

**Comment by trivialfis** [comment] 2022-11-24 04:06
I will close this issue for now as we are still working on the roadmap for full multi-target support. It's much more complicated than one might expect with new probabilistic forecasting algorithms emerging.

**Closed by trivialfis** 2022-11-24 04:06 UTC
Labels: feature-request
