### ISSUE TITLE
MAPE metric gives NaN when estimating zero loss residuals on a value of zero

### ISSUE THREAD

**Issue by outdoteth** [dmlc/xgboost#7586] opened 2022-01-20 17:54 UTC
I am getting this error:

```WARNING:root:NaN or Inf found in input tensor.``` 

along with no output on tensorboard for MAPE:

![screenshot_964](https://user-images.githubusercontent.com/37438950/150393970-89ceb8d2-2bc8-4578-9dd4-c61a5e00f781.png)

I suspect the issue is on this line: https://github.com/dmlc/xgboost/blob/master/src/metric/elementwise_metric.cu#L183

Because in this scenario:

```
label: 0
pred: 0
```

Then the MAPE calculation will give NaN

```
abs(0 - 0) / 0 == NaN
```

Solution: Add a check to see if both the residual and the label equal 0 before returning.

```javascript
let residual = pred - label 
return (residual == 0 && label == 0) ? 0 : abs(residual) / label
```

**Comment by trivialfis** [comment] 2022-01-20 18:29
Thanks for raising the issue.  It's not clear to me why do you need to check the residual?  We can avoid 0 division by checking only the label right?

Would you like to open a PR?

**Comment by outdoteth** [comment] 2022-01-20 18:49
Hm, I think I'm wrong in even using MAPE when the value can be zero:

https://stackoverflow.com/questions/41571215/forecasr-accuracy-mape-and-zero-values

e.g. if the residual is 3 and the label is 0 then 3 / 0 == Infinity

Maybe it doesn't make sense to fix this

**Comment by trivialfis** [comment] 2022-01-21 06:57
Yeah, returning 0 doesn't make sense.  But sometimes we add a small constant to let it approach infinite instead of having 0 division.

**Comment by trivialfis** [comment] 2022-01-26 11:37
Closing as this the issue is inherited from the definition of the metric.  Thank you for sharing the details!

**Closed by trivialfis** 2022-01-26 11:37 UTC
