### ISSUE TITLE
restoring xgboost 0.82.1 version models (in R) with xgboost 1.1.1.1 or 1.2.01 still failing ?

### ISSUE THREAD

**Issue by nirguk** [dmlc/xgboost#6509] opened 2020-12-15 22:52 UTC
I am trying to adapt my workflow to later versions of xgboost, however earlier fitted models are causing me grief... I had hoped that the following comments indicated that a new compatability layer would solve this issue, however it seems not ?

>#5794 has been addressed by #5940, and in the upcoming XGBoost version, you can read models from old RDS models again.
>_Originally posted by @hcho3 in https://github.com/dmlc/xgboost/issues/5815#issuecomment-663975193_

I provide a reprex here:
https://github.com/nirguk/xgboost_versions

for example sake, I fit an xgb model on Titanic data with binary:logitraw as objective.
I save this with xgb.save and then
I try to load this in 1.1.1.1 and also in 1.2.0.1  with xgb.load, but receive error:
```
Error in xgb.Booster.handle(modelfile = modelfile) : 
  [22:52:10] amalgamation/../src/objective/./regression_loss.h:89: Check failed: base_score > 0.0f && base_score < 1.0f: base_score must be in (0,1) for logistic loss, got: -0
```

**Comment by hcho3** [comment] 2020-12-15 23:12
@nirguk Your issue is not related to the RDS compatibility issue mentioned in #5794, as you are using `xgb.load`. I will take a look and see if it can be fixed in the upcoming patch release.

**Comment by nirguk** [comment] 2020-12-15 23:13
Thanks  for the speedy response, does that imply I might have success saving and loading as RDS ? I will experiment with that in my reprex.

**Comment by hcho3** [comment] 2020-12-15 23:15
@nirguk Probably not. The issue appears to be in the core module of XGBoost, and using RDS would not fix the issue. Besides, we do not recommend the use of RDS for model archival: https://www.rdocumentation.org/packages/xgboost/versions/1.2.0.1/topics/a-compatibility-note-for-saveRDS-save

**Comment by hcho3** [comment] 2020-12-16 12:44
@nirguk Hello, I ran the script you provide and reproduced the same error. I am now investigating a possible fix.

**Comment by hcho3** [comment] 2020-12-16 12:44
Oops accidentally closed the issue. The issue is still being investigated.

**Comment by nir4most** [comment] 2020-12-16 12:47
Thanks hcho3, this would be extremely useful !

**Comment by hcho3** [comment] 2020-12-16 12:51
Update: I verified that the use of `objective='binary:logitraw'` is causing the compatibility problem. If the objective is changed to `binary:logistic`, the 0.82 model can now be read into 1.2.0.

**Comment by hcho3** [comment] 2020-12-16 20:26
It turns out the issue also exists in Python as well, so it's not specific to the R package.

**Comment by trivialfis** [comment] 2020-12-16 20:49
@hcho3 We need to fill in an independent `ProbToMargin` for logistic raw to avoid inheriting it from logistic.

**Comment by hcho3** [comment] 2020-12-16 21:01
I submitted #6517 which works around the issue. Let me see if I can write a separate `ProbToMargin` function for `binary:logitraw`.

**Closed** 2020-12-17 00:53 UTC
Labels: type: bug

**Comment by hcho3** [comment] 2020-12-17 01:01
@nirguk @nir4most Hello, the bug was fixed in #6517. The bug fix will be part of the upcoming patch release 1.3.1. Subscribe to #6518 to keep track of the progress for 1.3.1 release.

**Comment by nir4most** [comment] 2020-12-17 08:07
Superb,  thanks a million 😀

**Comment by hcho3** [comment] 2020-12-17 08:15
@nir4most If you'd like to try it out now, you can follow [the instructions](https://xgboost.readthedocs.io/en/latest/build.html#installing-the-development-version-linux-mac-osx) to install XGBoost from the latest source.
