### ISSUE TITLE
Error from updating R package: xgb.iter.update(bst$handle, dtrain, i - 1, obj) :    AssertError:inconsistent col data

### ISSUE THREAD

**Issue by jibao** [dmlc/xgboost#355] opened 2015-06-15 15:20 UTC
Hi, 

I encountered with a problem that after updating the xgboost R package, my codes that previously successfully ran now returned with the error:
Error in xgb.iter.update(bst$handle, dtrain, i - 1, obj) :    AssertError:inconsistent col data
it's the same as this one: https://www.kaggle.com/interesting/digit-recognizer/xg-boost-script 

I ran the same code on my old xgboost package again and it still works well. but on the latest one, it always returns with this error.

**Comment by tqchen** [comment] 2015-06-15 16:24
thanks for reporting the problem. This is fixed in newest commit

**Comment by jibao** [comment] 2015-06-15 17:42
Thanks for quick reply. The first problem has been solved.

but when I use objective = "count:poisson", the returned error is shown as below although all of my labels are positive:
Error in xgb.iter.update(bst$handle, dtrain, i - 1, obj) : 
  PoissonRegression: label must be nonnegative

**Comment by tqchen** [comment] 2015-06-16 02:22
I cannot reproduce what you described on my linux machine, the error checking code was here https://github.com/dmlc/xgboost/blob/master/src/learner/objective-inl.hpp#L210

**Closed** 2015-06-24 15:57 UTC
