### ISSUE TITLE
xgboost4j spark

### ISSUE THREAD

**Issue by zyq11223** [dmlc/xgboost#4187] opened 2019-02-27 11:02 UTC
how to incremental training xgboost4j  spark model  with an existed xgboost classification model ？
Does the XGBModel.booster.update(DMatrix, Iteration ) mean that ?

**Comment by zyq11223** [comment] 2019-02-27 11:03
謝謝

**Comment by hcho3** [comment] 2019-02-27 18:41
Closing as duplicate of #4188

**Closed by hcho3** 2019-02-27 18:41 UTC
