### ISSUE TITLE
[jvm-packages] Java Implementation : java.lang.UnsatisfiedLinkError when using DMatrix

### ISSUE THREAD

**Issue by dnkamila** [dmlc/xgboost#1011] opened 2016-03-18 17:11 UTC
I'm using eclipse luna with maven plugin in Windows 8.1. I've already put xgboost4j.dll (renaming libxgboost.dll which is produced from running "make" in xgboost folder) in xgboost4j/src/main/resources/lib/xgboost4j.dll by running create_Jni.bat. When I'm running BasicWalkThrough.java in example package, it output the following error

Exception in thread "main" java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromFile(Ljava/lang/String;I[J)I
	at ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromFile(Native Method)
	at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:83)
	at ml.dmlc.xgboost4j.java.example.BasicWalkThrough.main(BasicWalkThrough.java:52)

Please let me know what am I doing wrong.

Thanks in advance.

**Comment by CodingCat** [comment] 2016-03-18 22:05
Hi, @dnkamila ,  I do not think `libxgboost.dll` contains JNI implementation of XGBoost , instead `..\windows\x64\Release\xgboost4j.dll` is the right resource ....

@tqchen , is there any place containing XGBoost windows installation document?

**Comment by tqchen** [comment] 2016-03-18 22:07
The MSVC build was removed and not yet been added back

**Comment by dnkamila** [comment] 2016-03-19 00:05
@CodingCat @tqchen , So if MSVC build is added back, when I run "make" in xgboost folder, it will produce "xgboost\windows\x64\Release\xgboost4j.dll"? What should I do in order to use xgboost in Java?

**Comment by CodingCat** [comment] 2016-03-19 01:07
for your question, yes, 


xgboost4j JNI implementation is a native lib which is built by calling xgboost APIs...so they are not the same

**Comment by dnkamila** [comment] 2016-03-19 01:10
Hum, so what should I do in order to use xgboost in Java? Should I wait untill MSVC build is added back? Btw, thanks for fast response..

**Comment by CodingCat** [comment] 2016-03-19 01:12
I think so?@tqchen

**Comment by dnkamila** [comment] 2016-03-19 01:51
I'm trying to install it on ubuntu, when I'm running create_jni.sh, there is no file 'lib/libxgboost4j.so'. So, the problem happens to jvm-packages for windows and ubuntu because "MSVC build"?

**Comment by CodingCat** [comment] 2016-03-19 01:52
what do you mean by ` there is no file 'lib/libxgboost4j.so'.`, would you please post the screenshot of your terminal?

**Comment by dnkamila** [comment] 2016-03-19 03:58
Here is screenshot of my terminal (I'm already run "make -j4")

![screenshot from 2016-03-19 10 43 33](https://cloud.githubusercontent.com/assets/6870963/13896543/88e6a176-edc1-11e5-84e9-7749d2502273.png)

**Comment by CodingCat** [comment] 2016-03-19 12:03
so, here the problem is that you didn't properly define your JAVA_HOME to your JDK directory 


![image](https://cloud.githubusercontent.com/assets/678008/13898495/0d831054-eda9-11e5-9566-6246c106a1c7.png)


you can observe that in the inline containing `<jni.h>`


just do that...and everything will be OK

**Comment by dnkamila** [comment] 2016-03-19 13:47
Hum, I'm already setting my JAVA_HOME

![screenshot from 2016-03-19 20 46 24](https://cloud.githubusercontent.com/assets/6870963/13898922/c8837da2-ee13-11e5-98a3-990a85474ddb.png)

**Comment by dnkamila** [comment] 2016-03-19 14:32
Thanks, after I set my JAVA_HOME in .bashrc instead of in /etc/environment, it works fine (produce libxgboost4g.so)

In issue #998 you said 

> FYI, now, it only requires to run mvn package under jvm-packages directory to build XGBoost4J....

I'm trying running "mvn package" and get error when building "xgboost4j-example-0.5-jar-with-dependencies.jar". It works fine when import xgboost4j-0.5-jar-with-dependencies.jar but not when import xgboost4j-example-0.5-jar-with-dependencies.jar. It's good so far because I'm not using example jar yet.

I'm waiting for your "instruction in the installation part to explain what create_jni.sh does" ^^ Because I'm confused why you need create_jni.sh to get libxgboost4g.so when you have mvn package to get jar file that you can import directly to your java project.

**Comment by CodingCat** [comment] 2016-03-19 15:08
@dnkamila would you post what your OS says when you got error while building "xgboost4j-example-0.5-jar-with-dependencies.jar"

now, create_jni.sh is more like an internal use script, which will be called by mvn, to compile native library , copy the generated lib to resource directory and include that in the jar file

**Comment by CodingCat** [comment] 2016-03-19 15:11
so...we are not going to explain which create_jni.sh does, because the user only needs to call mvn package....

**Comment by dnkamila** [comment] 2016-03-19 15:25
Here the following error, it said gc overhead limit exceeded

![screenshot from 2016-03-19 12 32 28](https://cloud.githubusercontent.com/assets/6870963/13899463/3d0d3fa2-ee21-11e5-83ab-148b973dbde9.png)

**Comment by CodingCat** [comment] 2016-03-19 15:39
it seems that you have limited memory space in your ubuntu machine

try to run `export MAVEN_OPTS="-Xmx2g -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=512m"` before `mvn package`

**Comment by CodingCat** [comment] 2016-03-19 15:40
of course, if your memory is less than 2g, e.g. in a VM instance...you may want to assign more memory to it

**Comment by dnkamila** [comment] 2016-03-19 15:57
Finally it works fine @CodingCat ^^ btw can I use jar file that I have now from one laptop (ubuntu 14) to another laptop (debian 8)?

**Comment by CodingCat** [comment] 2016-03-19 16:22
As long as you have compatible libstdc++ , I think it shall be fine

**Comment by dnkamila** [comment] 2016-03-19 16:25
Thanks for your help @CodingCat ^^ I just have to wait for MSVC build to be added back (for using in windows)..

**Comment by CodingCat** [comment] 2016-03-19 16:32
With my pleasure, and i will close this one

**Closed by CodingCat** 2016-03-19 16:32 UTC

**Comment by tqchen** [comment] 2016-03-19 16:38
seems the java_home is also another common problem, let us add it to a trouble shooting section @CodingCat each time a common issue is solved

**Comment by CodingCat** [comment] 2016-03-19 16:41
Yeah, it has been added, see the latest commit

**Comment by venut202** [comment] 2016-05-28 18:23
Hi,
I'm trying to build jvm-packages. But i'm running into UnsatisfiedLink ERROR in tests. I have set JAVA_HOME. I can see it is failing to load native library but i have set JAVA_HOME properly. I'm not sure whether to create an issue or not for this. That is why posting it here. Can someone please tell me what is the issue here.

Below the maven build log.


jvm-packages]$ ~/apache-maven-3.3.9/bin/mvn -Dspark.version=1.6.0 package
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for ml.dmlc:xgboost4j:jar:0.5
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:exec-maven-plugin is missing. @ line 32, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] xgboost-jvm
[INFO] xgboost4j
[INFO] xgboost4j-spark
[INFO] xgboost4j-flink
[INFO] xgboost4j-example
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building xgboost-jvm 0.5
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- scalastyle-maven-plugin:0.8.0:check (checkstyle) @ xgboost-jvm ---
[WARNING] sourceDirectory is not specified or does not exist value=/home/venugopalt/xgboost/xgboost/jvm-packages/src/main/scala
[WARNING] testSourceDirectory is not specified or does not exist value=/home/venugopalt/xgboost/xgboost/jvm-packages/src/test/scala
Processed 0 file(s)
Found 0 errors
Found 0 warnings
Found 0 infos
Finished in 124 ms
[INFO]
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ xgboost-jvm ---
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (default) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost-jvm:0.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-compiler:2.10.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-reflect:2.10.5 requires scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost-jvm:0.5 requires scala version: 2.10.5
[WARNING]  org.scalatest:scalatest_2.10:2.2.6 requires scala version: 2.10.6
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (compile) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost-jvm:0.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-compiler:2.10.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-reflect:2.10.5 requires scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost-jvm:0.5 requires scala version: 2.10.5
[WARNING]  org.scalatest:scalatest_2.10:2.2.6 requires scala version: 2.10.6
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:testCompile (test-compile) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost-jvm:0.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-compiler:2.10.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-reflect:2.10.5 requires scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost-jvm:0.5 requires scala version: 2.10.5
[WARNING]  org.scalatest:scalatest_2.10:2.2.6 requires scala version: 2.10.6
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO]
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ xgboost-jvm ---
Discovery starting.
Discovery completed in 63 milliseconds.
Run starting. Expected test count is: 0
DiscoverySuite:
Run completed in 175 milliseconds.
Total number of tests run: 0
Suites: completed 1, aborted 0
Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
No tests were executed.
[INFO]
[INFO] --- maven-assembly-plugin:2.6:single (make-assembly) @ xgboost-jvm ---
[INFO] Assemblies have been skipped per configuration of the skipAssembly parameter.
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building xgboost4j 0.5
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- scalastyle-maven-plugin:0.8.0:check (checkstyle) @ xgboost4j ---
Processed 7 file(s)
Found 0 errors
Found 0 warnings
Found 0 infos
Finished in 917 ms
[INFO]
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ xgboost4j ---
[INFO]
[INFO] --- exec-maven-plugin:1.5.0:exec (native) @ xgboost4j ---
build java wrapper
Makefile:29: dmlc-core/make/dmlc.mk: No such file or directory
make: *** No rule to make target `dmlc-core/make/dmlc.mk'.  Stop.
move native lib
mv: cannot stat ‘lib/libxgboost4j.so’: No such file or directory
cp: cannot stat ‘../dmlc-core/tracker/dmlc_tracker/tracker.py’: No such file or directory
complete
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ xgboost4j ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (default) @ xgboost4j ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost4j:0.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-compiler:2.10.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-reflect:2.10.5 requires scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost4j:0.5 requires scala version: 2.10.5
[WARNING]  org.scalatest:scalatest_2.10:2.2.6 requires scala version: 2.10.6
[WARNING] Multiple versions of scala libraries detected!
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ xgboost4j ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (compile) @ xgboost4j ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost4j:0.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-compiler:2.10.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-reflect:2.10.5 requires scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost4j:0.5 requires scala version: 2.10.5
[WARNING]  org.scalatest:scalatest_2.10:2.2.6 requires scala version: 2.10.6
[WARNING] Multiple versions of scala libraries detected!
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ xgboost4j ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/venugopalt/xgboost/xgboost/jvm-packages/xgboost4j/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ xgboost4j ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:testCompile (test-compile) @ xgboost4j ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost4j:0.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-compiler:2.10.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-reflect:2.10.5 requires scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost4j:0.5 requires scala version: 2.10.5
[WARNING]  org.scalatest:scalatest_2.10:2.2.6 requires scala version: 2.10.6
[WARNING] Multiple versions of scala libraries detected!
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ xgboost4j ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running ml.dmlc.xgboost4j.java.DMatrixTest
May 28, 2016 6:12:42 PM ml.dmlc.xgboost4j.java.NativeLibLoader smartLoad
SEVERE: failed to load library from both native path and jar
May 28, 2016 6:12:42 PM ml.dmlc.xgboost4j.java.DMatrix <clinit>
SEVERE: load native library failed.
May 28, 2016 6:12:42 PM ml.dmlc.xgboost4j.java.DMatrix <clinit>
SEVERE: java.io.FileNotFoundException: File /lib/libxgboost4j.so was not found inside JAR.
Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.097 sec <<< FAILURE! - in ml.dmlc.xgboost4j.java.DMatrixTest
testCreateFromFile(ml.dmlc.xgboost4j.java.DMatrixTest)  Time elapsed: 0.062 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromFile(Ljava/lang/String;I[J)I
        at ml.dmlc.xgboost4j.java.DMatrixTest.testCreateFromFile(DMatrixTest.java:60)

testCreateFromDataIterator(ml.dmlc.xgboost4j.java.DMatrixTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromDataIter(Ljava/util/Iterator;Ljava/lang/String;[J)I
        at ml.dmlc.xgboost4j.java.DMatrixTest.testCreateFromDataIterator(DMatrixTest.java:49)

testCreateFromDenseMatrix(ml.dmlc.xgboost4j.java.DMatrixTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromMat([FIIF[J)I
        at ml.dmlc.xgboost4j.java.DMatrixTest.testCreateFromDenseMatrix(DMatrixTest.java:112)

testCreateFromCSR(ml.dmlc.xgboost4j.java.DMatrixTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromCSR([J[I[F[J)I
        at ml.dmlc.xgboost4j.java.DMatrixTest.testCreateFromCSR(DMatrixTest.java:84)

Running ml.dmlc.xgboost4j.java.BoosterImplTest
Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0 sec <<< FAILURE! - in ml.dmlc.xgboost4j.java.BoosterImplTest
saveLoadModelWithPath(ml.dmlc.xgboost4j.java.BoosterImplTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromFile(Ljava/lang/String;I[J)I
        at ml.dmlc.xgboost4j.java.BoosterImplTest.saveLoadModelWithPath(BoosterImplTest.java:119)

testCV(ml.dmlc.xgboost4j.java.BoosterImplTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromFile(Ljava/lang/String;I[J)I
        at ml.dmlc.xgboost4j.java.BoosterImplTest.testCV(BoosterImplTest.java:162)

testBoosterBasic(ml.dmlc.xgboost4j.java.BoosterImplTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromFile(Ljava/lang/String;I[J)I
        at ml.dmlc.xgboost4j.java.BoosterImplTest.testBoosterBasic(BoosterImplTest.java:103)

saveLoadModelWithStream(ml.dmlc.xgboost4j.java.BoosterImplTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromFile(Ljava/lang/String;I[J)I
        at ml.dmlc.xgboost4j.java.BoosterImplTest.saveLoadModelWithStream(BoosterImplTest.java:137)


Results :

Tests in error:
  BoosterImplTest.saveLoadModelWithPath:119 » UnsatisfiedLink ml.dmlc.xgboost4j....
  BoosterImplTest.saveLoadModelWithStream:137 » UnsatisfiedLink ml.dmlc.xgboost4...
  BoosterImplTest.testBoosterBasic:103 » UnsatisfiedLink ml.dmlc.xgboost4j.java....
  BoosterImplTest.testCV:162 » UnsatisfiedLink ml.dmlc.xgboost4j.java.XGBoostJNI...
  DMatrixTest.testCreateFromCSR:84 » UnsatisfiedLink ml.dmlc.xgboost4j.java.XGBo...
  DMatrixTest.testCreateFromDataIterator:49 » UnsatisfiedLink ml.dmlc.xgboost4j....
  DMatrixTest.testCreateFromDenseMatrix:112 » UnsatisfiedLink ml.dmlc.xgboost4j....
  DMatrixTest.testCreateFromFile:60 » UnsatisfiedLink ml.dmlc.xgboost4j.java.XGB...

Tests run: 8, Failures: 0, Errors: 8, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] xgboost-jvm ........................................ SUCCESS [  4.177 s]
[INFO] xgboost4j .......................................... FAILURE [  2.826 s]
[INFO] xgboost4j-spark .................................... SKIPPED
[INFO] xgboost4j-flink .................................... SKIPPED
[INFO] xgboost4j-example .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.162 s
[INFO] Finished at: 2016-05-28T18:12:43+00:00
[INFO] Final Memory: 25M/496M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project xgboost4j: There are test failures.
[ERROR]
[ERROR] Please refer to /home/venugopalt/xgboost/xgboost/jvm-packages/xgboost4j/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :xgboost4j
