### ISSUE TITLE
External Memory Usage with GPU - "Invalid Resource Handle" Error

### ISSUE THREAD

**Issue by talipini** [dmlc/xgboost#6167] opened 2020-09-25 13:29 UTC
Running xgboost on external memory causes "invalid resource handle" error with GPU.

I have a large dataset that doesn't fit into memory and I was hoping to use external memory to train as explained in https://xgboost.readthedocs.io/en/latest/tutorials/external_memory.html. CPU version seems to work fine but using "gpu_hist" causes this error.  

**terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: invalid resource handle**

Here is the sample code. create_samples creates a naive dummy 2M samples with 500 features each. Our dataset is much larger but this sample serves the purpose to recreate the error.  

```
import xgboost
import pandas as pd
import numpy as np
import pathlib

def create_samples(sample_file):
    with open(sample_file, 'a') as f:
        for i in range(0,20):
            print(f'Writing chunk - {i}')
            chunk = 100000
            sample_df = pd.DataFrame(np.random.uniform(low=-1.0, high=5, size=(chunk,500)))
            y = np.random.randint(low=1, high=11, size=chunk)
            sample_df.insert(0, column='y',value=y)
            sample_df.to_csv(f,index=False, header=False)

    print(f'Finished creating sample file at {sample_file}')


def run_xgboost(data_file):
    dtrain = xgboost.DMatrix(f"{data_file}?format=csv&label_column=0#traincache")
    params = {
        'objective':'multi:softmax', 
        "num_class": 11,             
        'eval_metric':'merror',
        'nthread': 1,
        'tree_method':'gpu_hist',  
        'sampling_method': 'gradient_based',
    }

    bst = xgboost.train(
        params=params,
        dtrain=dtrain,
        num_boost_round=3
    )
    print("Finished training. ")



if __name__ == '__main__':

    sample_file = "sample.csv" 
    #create dummy sample, if it doesn't exist
    if not pathlib.Path(sample_file).is_file():
        create_samples(sample_file) 
    
    run_xgboost(sample_file)
```

XGBoost Version - 1.3.0-SNAPSHOT (latest nightly build)
GPU: RTX 2080 Ti
Driver: 440.82
CUDA: 10.2

**Comment by jamescolless** [comment] 2020-10-05 14:53
I'm not sure how to extract a particular error message, but I'm having the same issue with version 1.2.0. A large-ish data set which trains fine using CPU on external memory, but fails when I switch to gpu_hist.

**Comment by talipini** [comment] 2020-10-05 17:30
I am seeing this issue when we are using dask as well. If anyone knows any workarounds, really appreciate it. Kinda held up here.

**Comment by trivialfis** [comment] 2020-10-08 02:28
Actually I have never seen it before.  Could you check whether it's working correctly with a small dataset first?

**Comment by talipini** [comment] 2020-10-08 02:53
Yes, smaller sample works fine. If we change the size of the sample in the above code, it runs fine. (change the for loop range in  create_samples to 1). It probably defeats the purpose of using external memory but serves as a test. Something is going on when the size of dataset exceeds a certain threshold. Pretty much the same issue when we use dask to utilize multiple gpus with a larger dataset.

**Comment by trivialfis** [comment] 2020-10-08 04:53
Thanks for the reply.  Here are some follow up questions for dask:

- Are you using `xgboost.dask` module?
  - If not, are you using external memory with dask?
  - If yes, could you please provide the related snippet for your training code?  With comment of input type (backend of dask).

**Comment by jamescolless** [comment] 2020-10-08 07:53
In my case I am using external memory without dask, very similar to the originally posted section of code. I think dask is probably a red herring as the problem is fully reproducible without using dask as the above example shows.

**Comment by trivialfis** [comment] 2020-10-08 09:42
The GPU implementation of out of core training is different and bested used with gradient based sampling.  It doesn't load data by batches like the CPU version does, as copying N batches of data from disk to system memory then to GPU memory for everything tree node is unacceptably slow.  So for scaling GPU training, you should use dask or gradient based sampling + external memory.

**Comment by talipini** [comment] 2020-10-08 11:27
In the above sample code, we have set 'sampling_method': 'gradient_based' - is there anything else we need to do? 

Keeping Dask apart, I think there is an underlying issue when data is loaded with external memory. For instance, the above code  works without an issue on the GPU if we load it straight up into the memory i.e. without external memory usage. But doesn't work if we load it via external memory. In the example above, we do set gradient based sampling. 

For distributed/scaling with multiple GPUs, we are using xgboost.dask. We are not using external memory with dask. I can create another sample with dask setup but as jamescolless said, the above code is in its simplest form recreates the issue. I will get the dask sample as well.

For your questions - 
- Are you using xgboost.dask module? - **Yes**
-     If not, are you using external memory with dask?  **Right now, no.**
-     If yes, could you please provide the related snippet for your training code? With comment of input type (backend of dask). **Let me work on creating a reproducible sample with dask.**

**Comment by trivialfis** [comment] 2020-10-08 12:45
> is there anything else we need to do?

The parameter `subsample` for sampling rate. ;-)

>  I think there is an underlying issue when data is loaded with external memory. For instance, the above code works without an issue on the GPU if we load it straight up into the memory

One last question about this, what platform are you running on?  Windows or Linux?

**Comment by trivialfis** [comment] 2020-10-08 12:46
> If yes, could you please provide the related snippet for your training code? With comment of input type (backend of dask). Let me work on creating a reproducible sample with dask.

That would be great!

**Comment by jamescolless** [comment] 2020-10-08 12:57
I'm running on windows and I was using the subsample parameter (made no difference to whether I had the error or not).

**Comment by trivialfis** [comment] 2020-10-08 13:17
That make sense.  There are some progress on making the Windows pipeline more robust.  dask interface doesn't work on Windows at all until very recently.

**Comment by talipini** [comment] 2020-10-08 13:36
We are running on Linux. Even with subsample 0.1, I am getting the same error.

**Comment by talipini** [comment] 2020-10-08 13:51
Just to add some more color, loading data with external memory option, results in "**invalid resource handle**" error while loading the data directly results in "**out of memory**" error. 

For discussion sake, we increased the data size and loaded the data into a machine with significantly higher RAM without using external memory option. Training on the GPU with subsample 0.1 and gradient sampling results in "out of memory error" as below. 

```
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: invalid resource handle
Aborted (core dumped)

```
But when the data is loaded via external memory option, then the error changes to this. 

```
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: invalid resource handle
Aborted (core dumped)
```

**Comment by talipini** [comment] 2020-10-08 14:01
There are multiple things going on so perhaps isolating to simpler problem might help us. These are few unanswered questions from me.

1. With enough RAM on the machine to load the full dataset into memory, we get the "out of memory" error after the training starts. I think this is where the GPU memory is getting maxed out. Using gradient_based and subsample rate of 0.1 doesn't help. 
2. If the data is too large to load into RAM and using external memory mode, creates "invalid resource handle" error after the training starts. 
3. Using Dask, doesn't really solve these problems as the underlying GPU utilization is causing the issue. Using dask to add more GPUs increases the threshold on the dataset size above which  this error happens.

**Comment by jamescolless** [comment] 2020-10-08 14:56
I just managed to get this working *on linux* with the same code that crashes for me on windows.

**Comment by talipini** [comment] 2020-10-08 15:03
Could you share your linux config? And can you try with a larger dataset? Above code creates 2M samples. May be with 4M?

**Comment by trivialfis** [comment] 2020-10-08 15:07
Thanks for the detailed report.

- The GPU utilization ratio is not satisfying.  This depends on lots of factors, but we do have plans on improving it on some cases, particularly on multi-class case (your script), stay tuned.
- External memory is not robust enough.  This is a known issue and it's marked as beta.  We drafted some plans regarding external memory, but as it's just too slow so we never prioritize it.

**Comment by jamescolless** [comment] 2020-10-09 09:22
The following works fine on Linux but not windows:

Xgboost 1.20
Cuda 10.0
Ubuntu 18.04

```
import os
import numpy as np
from sklearn.datasets import make_regression

df_train = make_regression(n_samples=10000000, n_features=100)
np.savetxt('dummy_txt.train', np.hstack([df_train[1].reshape(-1,1), df_train[0]]), delimiter=',')

dtrain = xgb.DMatrix('dummy_txt.train?format=csv&label_column=0#dtrain.cache')

param = {'tree_method' : 'gpu_hist', 'subsample' : 0.2, 'sampling_method' : 'gradient_based'}

num_round = 5
bst = xgb.train(param, dtrain, num_round

```
Apologies for any typos.

**Comment by CalebEverett** [comment] 2020-12-03 21:36
Hi, I was having a fail on external memory  use as well trying to train on csv with 30M rows and 50 columns.

These seem to be the operative error messages:

```
Dec 3, 2020, 1:28:46 PM | WARNING | what(): parallel_for failed: invalid resource handle
-- | -- | --
Dec 3, 2020, 1:28:46 PM | WARNING | terminate called after throwing an instance of 'thrust::system::system_error'
```

Here is a colab that reproduces the error. 

https://colab.research.google.com/drive/1vXq9xdVXCqvnyHavuNL_2rECGH_ISeYb?usp=sharing

For what it's worth, it worked with 20M rows.

**Comment by trivialfis** [comment] 2021-07-22 07:21
Please try to use the new iterator interface.  :-)

**Closed by trivialfis** 2021-07-22 07:21 UTC
Labels: type: bug
