### ISSUE TITLE
Is “gpu_hist” only supported by GPU-enabled machine?

### ISSUE THREAD

**Issue by zzheng93** [dmlc/xgboost#4199] opened 2019-03-03 16:17 UTC
Hi folks,
I just trained a model (XGBRegressor) using “gpu_hist” tree method on a GPU-enabled machine.
I used pickle.dump(…) to store the model.
I want to load and apply this model on a machine without any GPU. I am wondering if it is feasible?

What I am doing currently is to use pickle.load(…) to load the model. For example, XGBreg_load = pickle.load(…)
The "xgb.plot_importance(...)" still works and is reproducible.
**However, when I use XGBreg.predict(…) to make the prediction, the results are not correct.**
I am wondering if it is possible to make it correct on a machine without any GPU?

**Comment by hcho3** [comment] 2019-03-03 16:42
Can you post a small script to reproduce the issue?

**Comment by zzheng93** [comment] 2019-03-03 18:52
> Can you post a small script to reproduce the issue?

Sure.  @hcho3 
**On the GPU-enabled machine (where I got and saved the model):**
`XGBreg = pickle.load(open("./mode_XGB.dat","rb"))`
[18:45:07] /workspace/src/learner.cc:362: Parameter 'predictor' has been recovered from the saved model. It will be set to 'gpu_predictor' for prediction. To override the predictor behavior, explicitly set 'predictor' parameter as follows:
  * Python package: bst.set_param('predictor', [new value])
  * R package:      xgb.parameters(bst) <- list(predictor = [new value])
  * JVM packages:   bst.setParam("predictor", [new value])

`XGBreg.predict(df[vari_ls])`
array([286.47766, 286.54575, 287.41147, ..., 274.29263, 273.1712 ,
       275.02548], dtype=float32)
`type(XGBreg)`
xgboost.sklearn.XGBRegressor



**One the machine without GPU**
`XGBreg = pickle.load(open("./mode_XGB.dat","rb"))`
[11:46:23] /workspace/src/learner.cc:362: Parameter 'predictor' has been recovered from the saved model. It will be set to 'gpu_predictor' for prediction. To override the predictor behavior, explicitly set 'predictor' parameter as follows:
  * Python package: bst.set_param('predictor', [new value])
  * R package:      xgb.parameters(bst) <- list(predictor = [new value])
  * JVM packages:   bst.setParam("predictor", [new value])

`XGBreg.predict(df[vari_ls])`
array([0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5], dtype=float32)
`type(XGBreg)`
xgboost.sklearn.XGBRegressor

**I am wondering how to modify the `bst.set_param('predictor', [new value]` for "gpu_hist" on the machine without GPU?**

**Comment by hcho3** [comment] 2019-03-08 05:08
@zzheng93 Did you try using `save_model()` / `load_model()` instead?

**Comment by zzheng93** [comment] 2019-03-12 02:29
@hcho3 Yes. I tried. 
`XGBreg = XGBRegressor(tree_method = 'gpu_hist',seed=66)` 
`XGBreg.load_model("...l")`
`XGBreg.predict(df[vari_ls])`

Same code, but different results on different machines. 

I am wondering how to deal with the following hints?

[20:22:16] /workspace/src/learner.cc:362: Parameter 'predictor' has been recovered from the saved model. It will be set to 'gpu_predictor' for prediction. To override the predictor behavior, explicitly set 'predictor' parameter as follows:
  * Python package: bst.set_param('predictor', [new value])
  * R package:      xgb.parameters(bst) <- list(predictor = [new value])
  * JVM packages:   bst.setParam("predictor", [new value])

I got the following error
`AttributeError: 'XGBRegressor' object has no attribute 'set_param'`

**Comment by ihopethiswillfi** [comment] 2019-03-22 06:43
This works for me on an XGBRegressor:
```model.set_params(tree_method='hist')```

**Comment by zzheng93** [comment] 2019-04-25 03:52
> Could you try:
> `model.set_params(tree_method='hist')`

Hi,
I tried with CPU. Still gives a wrong result.

**Comment by hcho3** [comment] 2019-05-31 22:58
@zzheng93 I think #4454 may have address this issue. Can you try with latest code?

**Comment by trivialfis** [comment] 2019-06-25 18:24
I believe it's fixed in #4516.  Feel free to reopen if the problem persists.

**Closed by trivialfis** 2019-06-25 18:24 UTC
