### ISSUE TITLE
(python) input_split_base.cc:190: file offset not calculated correctly

### ISSUE THREAD

**Issue by bbbxixixixi** [dmlc/xgboost#3277] opened 2018-04-27 09:22 UTC
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
windows 7 64bit

Compiler:

Package used (python/R/jvm/C++): python3.5

`xgboost` version used: 
latest version downloaded on 2018-04-24

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
c2b647f26e3b9a870969043fbe2100008d4fb7e1
2. Logs will be helpful (If logs are large, please upload as attachment).
[16:29:10] src/io/input_split_base.cc:182: curr=3828361971,begin=0,end=18446744073242946291,fileptr=0,fileoffset=18446744073242946291
[16:29:10] dmlc-core/include/dmlc/./logging.h:300: [16:29:10] src/io/input_split_base.cc:190: file offset not calculated correctly
Traceback (most recent call last):
  File "D:\pythonCode\contestXgboost.py", line 9, in <module>
    dtrain = xgb.DMatrix('D:/contest/preliminary_contest_data/xgboost/trainAll.svm.txt')
  File "D:\ProgramFiles\Python\Python35\lib\site-packages\xgboost-0.71-py3.5.egg\xgboost\core.py", line 272, in __init__
    ctypes.byref(self.handle)))
  File "D:\ProgramFiles\Python\Python35\lib\site-packages\xgboost-0.71-py3.5.egg\xgboost\core.py", line 130, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: b'[16:29:10] src/io/input_split_base.cc:190: file offset not calculated correctly'

If you are using python package, please provide

1. The python version and distribution
3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1. I generate libsvm file from train data. like this,
-1 1:687 5:1.0 12:1.0 25:1.0 38:1.0 63:1.0 73:1.0 120:1.0 388:0.002505107798730011 389:0.00572696921777924 403:1.0 408:0.02236179789284618 409:0.02236179789284618 411:59 421:1.0 704:1.0
The size of the data is about 3.7GB. When I load the data using
dtrain = xgb.DMatrix('D:/contest/preliminary_contest_data/xgboost/trainAll.svm.txt')
it reports errors. I once thought there are incorrect data in it, I split them into 10 chunks. All chunks are loaded OK. When the chunk size exceeds 2G(2.1G or so), the error occurs. Computer memory is 16GB and no restrictions on python.
Similar bug is reported here, https://github.com/dmlc/xgboost/issues/1390

## What have you tried?

1. I adjust the file size to find some clues. 2G is some kind of threshold. Since all chunks are generated by the same method ( java bufferedwriter ), the data format is correct. Windows task manager showed python memory increased properly during loading. It can exceeds to 4G or higher. I also check the source code of input_split_base.cc, it seems that when the data is about to finished loading, offset_curr_ does not equal file_offset_(the error info curr=3828361971 is more or less the size of the data measured by byte )
2.
3.

Thanks

**Comment by hcho3** [comment] 2018-05-09 21:58
Could you post the script you used to generate the libsvm file? I wonder if the issue is specific to Windows or also applicable to Mac and Linux.

**Comment by hcho3** [comment] 2018-05-23 19:19
Closing for now. When you get a chance to follow up, feel free to re-open it.

**Closed by hcho3** 2018-05-23 19:19 UTC
