### ISSUE TITLE
xgboost.core.XGBoostError: [15:49:05] C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:567: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?

### ISSUE THREAD

**Issue by sofiavlachou28** [dmlc/xgboost#7444] opened 2021-11-16 14:16 UTC
Hello to everyone!!

I am new to Python and Iam getting this error when running xgBoost: `xgboost.core.XGBoostError: [15:49:05] C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:567: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?`

I tried to search for this error, could not find much useful resources. 

I guess the error occurs in the prediction stage. But I'm not sure about that. 
Μy dataset consists of two columns: [`"Posts Frequency","Likes Count"]` as seen below. 

**Here's my code:** 
```
# Load Dependencies
import pandas as pd
from numpy import where
import matplotlib.pyplot as plt
import numpy as np
from numpy import unique
from sklearn import metrics
import warnings
warnings.filterwarnings('ignore')


#  Load the Data
# Define Columns
names = ["Posts Frequency","Likes Count"]


data = pd.read_csv("RANKING TEST (1).csv", encoding="utf-8", sep=";", delimiter=None,
                 names=names, delim_whitespace=False,
                 header=0, engine="python")
X = data.values[:,0:1]
y = data.values[:,1]



# Training 
from sklearn.model_selection import GroupShuffleSplit

gss = GroupShuffleSplit(test_size=.20, n_splits=1, random_state = 7).split(data, groups=data['Posts Frequency'])

X_train_inds, X_test_inds = next(gss)

train_data= data.iloc[X_train_inds]
X_train = train_data.loc[:, ~train_data.columns.isin(['Posts Frequency','Likes Count'])]
y_train = train_data.loc[:, train_data.columns.isin(['Likes Count'])]

test_data= data.iloc[X_test_inds]


X_test = test_data.loc[:, ~test_data.columns.isin(['Likes Count'])]
y_test = test_data.loc[:, test_data.columns.isin(['Likes Count'])]



from sklearn.model_selection import GroupShuffleSplit

gss = GroupShuffleSplit(test_size=.20, n_splits=1, random_state = 7).split(data, groups=data['Posts Frequency'])

X_train_inds, X_test_inds = next(gss)

train_data= data.iloc[X_train_inds]
X_train = train_data.loc[:, ~train_data.columns.isin(['Posts Frequency','Likes Count'])]
y_train = train_data.loc[:, train_data.columns.isin(['Likes Count'])]

groups = train_data.groupby('Posts Frequency').size().to_frame('size')['size'].to_numpy()

test_data= data.iloc[X_test_inds]


X_test = test_data.loc[:, ~test_data.columns.isin(['Likes Count'])]
y_test = test_data.loc[:, test_data.columns.isin([' Likes Count'])]





import xgboost as xgb

model = xgb.XGBRanker(
    tree_method='gpu_hist',
    booster='gbtree',
    objective='rank:pairwise',
    random_state=42,
    learning_rate=0.1,
    colsample_bytree=0.9,
    eta=0.05,
    max_depth=6,
    n_estimators=110,
    subsample=0.75
    )

model.fit(X_train, y_train, group=groups, verbose=True)


# make predictions
def predict(model, data):
    return model.predict( data.loc[:, ~data.columns.isin( ['Posts Frequency'] )] )


predictions = (data.groupby( 'Posts Frequency' )
               .apply( lambda x: predict( model, x ) ))
```

Can anyone help me??

Thank you in advance !!

Sofia

**Comment by trivialfis** [comment] 2021-11-16 14:48
Hi, could you please share the `RANKING TEST (1).csv` file so that I can run the script?

**Comment by sofiavlachou28** [comment] 2021-11-16 15:21
> Hi, could you please share the `RANKING TEST (1).csv` file so that I can run the script?

@trivialfis Yes! How can I upload it here?

**Comment by sofiavlachou28** [comment] 2021-11-16 15:25
@trivialfis  Done! 
@trivialfis  Done!
[RANKING TEST (1).csv](https://github.com/dmlc/xgboost/files/7547657/RANKING.TEST.1.csv)

I will be grateful if you can help me! :)

**Comment by trivialfis** [comment] 2021-11-16 17:08
I printed the data shape before calling `fit` method of `XGBRanker`:
``` python
print("X_train.shape:", X_train.shape, X_train.size)
```
and it's 
```
X_train.shape: (84, 0) 0
```

So you have generated an empty dataset somewhere in your script.

**Comment by sofiavlachou28** [comment] 2021-11-16 17:20
> I printed the data shape before calling `fit` method of `XGBRanker`:
> 
> ```python
> print("X_train.shape:", X_train.shape, X_train.size)
> model.fit(X_train, y_train, group=groups, verbose=True)
> ```
> 
> and it's
> 
> ```
> X_train.shape: (84, 0) 0
> ```
> 
> So you have generated an empty dataset somewhere in your script.

I can't print that. the error still occures... 
I can't understand what happens!

**Comment by sofiavlachou28** [comment] 2021-11-16 17:32
> So, if you put a zero-size dataset into xgboost, then xgboost doesn't know how many columns it has, which leads to `mparam_.num_feature != 0 ` error.
> 
> You need to make sure your dataset has non-trivial size: `X_train.size != 0`.

I set it, but unfortunately it doesn't run...

**Comment by trivialfis** [comment] 2021-11-16 17:39
You need to debug your code and your dataset.  Your dataset has total 2 columns, this line returns an empty dataframe as `X_train` due to the negation operator:

``` python
X_train = train_data.loc[
    :, ~train_data.columns.isin(["Posts Frequency", "Likes Count"])
]
```

I'm afraid I can't help you with data preprocessing.

**Comment by sofiavlachou28** [comment] 2021-11-16 17:43
> You need to debug your code and your dataset. Your dataset has total 2 columns, this line returns an empty dataframe as `X_train` due to the negation operator:
> 
> ```python
> X_train = train_data.loc[
>     :, ~train_data.columns.isin(["Posts Frequency", "Likes Count"])
> ]
> ```
> 
> I'm afraid I can't help you with data preprocessing.

doesν't matter ! I will expand my data. I will add two columns! Maybe it works better..!

**Comment by trivialfis** [comment] 2021-11-19 08:58
I will close this now since the cause is in preprocessing.  Feel free to reopen if there are further issues.

**Closed by trivialfis** 2021-11-19 08:58 UTC
Labels: status: need update

**Comment by lakeshkhatri** [comment] 2022-02-12 10:28
if you have python 3.7 version so you should install xgboost == 0.18. I have solved that problem through this method.

**Comment by sofiavlachou28** [comment] 2022-02-18 09:30
> if you have python 3.7 version so you should install xgboost == 0.18. I have solved that problem through this method.

@lakeshkhatri Could not find a version that satisfies the requirement xgboost==0.18 (from versions: [)](https://pypi.org/project/xgboost/1.5.0/#history)

There isn't 0.18 version. 

which other solves the error? 

Thank you!

**Comment by lakeshkhatri** [comment] 2022-02-18 09:41
You should try to install xgboost ==0.80

**Comment by sofiavlachou28** [comment] 2022-02-18 10:06
I have also changed my data and now I have 6 columns 

["label","id","comments","likes","artist frequency","artwork frequency"]

nothing changed in the error !

**Comment by realBagher** [comment] 2023-03-11 08:36
any luck on this issue ? 
facing the same problem nothing works so far

**Comment by yaozhang2016** [comment] 2023-07-12 15:14
I got a very similar error as below: 

I failed to load new xgboost booster with old spark, here is my details:

- booster train by python xgboost 1.6.2
** using on GPU with “reg:pseudohubererror”
** mod=xgb.dask.DaskXGBRegressor().fit
** saved by mod.get_booster().save_model(bst_path)

- loader for production by scala(2.11) spark(2.4.0) xgboost(1.1.1)
** load method is through standard way at https://github.com/dmlc/xgboost/issues/3689
** it first failed due to "Unknown objective function: reg:pseudohubererror" - well understood because 1.1.1 has no this objective
** then I modified booster in python training env by: booster.set_param(‘objective’, ‘reg:squarederror’) and booster.save_model; now model is load without any issue, but failed at actual scoring (mod.transform(df)) time with error:
Caused by: ml.dmlc.xgboost4j.java.XGBoostError: [10:39:43] /xgboost/src/learner.cc:946: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied. Are you using raw Booster interface?

I am sure my data is correct,
Any help to solve this is highly appreciated? Or this version back compatibility is impossible?

**Comment by Hafiz8823** [comment] 2023-08-01 20:25
Hello every one I am also facing same kind of error 

xgboost.core.XGBoostError: [00:11:36] C:/Users/administrator/workspace/xgboost-win64_release_1.6.0/src/common/io.cc:102: Opening xgb_model.json failed: No such file or directory

Can anyone please help me on this

**Comment by trivialfis** [comment] 2025-04-23 09:47
You passed an empty `DMatrix` to XGBoost and XGBoost doesn't know how to construct a model from empty set.

**Comment by GloC99** [comment] 2025-04-23 16:05
Hello, thank you for your response! 

I believe this should be highlighted in the documentation, as it's a crashing error. If the developer is not aware, they may not guard against it. 
 
Alternatively, this could fail, but cause a warning instead of a crash?

**Comment by lakeshkhatri** [comment] 2025-04-23 16:24
Hi,

you change your python version. I worked python 3.12. I think that you use same version then your problem will solve.
