### ISSUE TITLE
[jvm-packages] race-condition when using useExternalMemory for XGBoost4J-Spark

### ISSUE THREAD

**Issue by weitian** [dmlc/xgboost#3633] opened 2018-08-24 17:39 UTC
Spark executor runs within a container (YARN container, or docker container, etc.).
With useExternalMemory, XGBoost writes cache files into the local disk of the container.

It clears the cache file after training is done: https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala#L145

I run into a race condition if some containers (not all) was destroyed by Spark before the deleting cache files done.
This did not break the spark job, but you can see the exception in spark log:

Container exited with a non-zero exit code 255

18/08/24 10:24:37 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 3.0 (TID 534, rd17d01ls-geo0227.geo.apple.com, executor 22): ExecutorLostFailure (executor 22 exited caused by one of the running tasks) Reason: Container marked as failed: container_e03_1524081805147_39200_01_000023 on host: rd17d01ls-geo0227.geo.apple.com. Exit status: 255. Diagnostics: Exception from container-launch.
Container id: container_e03_1524081805147_39200_01_000023
Exit code: 255
Stack trace: ExitCodeException exitCode=255:
        at org.apache.hadoop.util.Shell.runCommand(Shell.java:604)
        at org.apache.hadoop.util.Shell.run(Shell.java:507)
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:789)
        at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:213)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

This reproducible whenever I turn useExternalMemory to true.

**Comment by weitian** [comment] 2018-08-24 17:40
Maybe there is no need to delete the cache files since they are always gone automatically when container is destroyed anyway.

**Comment by CodingCat** [comment] 2018-08-24 20:38
https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala#L145 is async method?

**Comment by weitian** [comment] 2018-08-24 21:19
Maybe the IO ops: https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala#L302 is async.

If I commented out the delete part, no exceptions in the log.

**Comment by CodingCat** [comment] 2018-08-26 05:13
https://stackoverflow.com/questions/10111372/do-the-methods-in-apaches-fileutils-peform-synchronous-blocking-i-o it doesn't look like an async method

the reason we have to delete files is that in local running, we need to clean those files for tests

**Comment by weitian** [comment] 2018-08-27 23:15
I am pretty sure the delete files causes for spark exception.
I will try to debug it later to see what exactly the root cause of that.

**Comment by hcho3** [comment] 2019-03-08 01:31
@CodingCat Was this issue solved?

**Comment by CodingCat** [comment] 2019-03-08 01:34
I cannot reproduce it actually

**Comment by hcho3** [comment] 2019-03-08 01:34
Okay, closing it for now

**Closed by hcho3** 2019-03-08 01:34 UTC
