### ISSUE TITLE
[Discussion] XGBoost Predict is not threadsafe

### ISSUE THREAD

**Issue by kylejn27** [dmlc/xgboost#5339] opened 2020-02-21 19:12 UTC
I would like to start a formal discussion on potential fixes for the thread safety issue of the xgboost predict method. It is noted in a few places that the predict method is not thread safe [ [in this issue](https://github.com/dmlc/xgboost/issues/3371) and [in the Python API](https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/core.py#L1349-L1366) and [in the C++ API](https://github.com/dmlc/xgboost/blob/master/include/xgboost/predictor.h#L132-L147) ]

A group of my colleagues at Capital One (@ahmadia, @gforsyth, @mmccarty, @stephenpardy) has come together and looked into a few possible suggested changes for this problem and would like to kick off a greater discussion on how best to improve user experience.

The best way to go about doing this would be to dive into the C++ layer and make the underlying methods thread safe. If anybody wishes to take this on, this would be the ideal change. However, this would be an intrusive set of code changes and a less intrusive just as effective change can be implemented at the Python layer. 

We propose the following:
- add a lock to the existing ctypes API call so that the predict method *cannot* be called in a multithreaded manner unintentionally. This prevents users from shooting themselves in the foot.
- build a new, threadsafe predict method or object. This method or object will use `threading.local` memory to store a copy of the booster object. The primary booster object should be automatically copied into thread local memory upon fork.

**Comment by kylejn27** [comment] 2020-02-21 19:14
Just as a heads up, I'll be unresponsive for about a week but the others that I mentioned will be able to respond. I figured I'd kick off this discussion now though.

**Comment by trivialfis** [comment] 2020-02-21 19:16
Personally I prefer changing the code in C++ to make it thread safe.  To provide some information about the subject, the problem is in our prediction cache.  If we can the this cache thread local then rest should be easy.

**Comment by trivialfis** [comment] 2020-02-21 20:23
For discussion purpose, would you like to share some context about usage of thread safe prediction?  

For example if you are using a thread management framework to handle incoming prediction queries, then there's no need for using a cache as once the prediction is done, the data is no longer useful for XGBoost.

But if you are doing incremental prediction, like first predict the first 4 trees then obtain the prediction from 8 trees to observe the difference, then the cache is still useful.

**Comment by RAMitchell** [comment] 2020-02-22 00:14
We will absolutely support contributions to fix this problem. Let us know what you propose in c++ layer and we can help work out a solution.

**Comment by trivialfis** [comment] 2020-02-22 07:33
@RAMitchell Actually I spent 10 minutes or so hacked together a thread safe CPU prediction.  GPU Prediction should not to any more difficult.

**Comment by sandys** [comment] 2020-02-23 05:40
i have an alternate suggestion - have you used the high performance onnxruntime ? 
it is threadsafe by design on both CPU and GPU - https://github.com/microsoft/onnxruntime/issues/114

you can convert an xgboost model to ONNX  format officially here - https://github.com/onnx/onnxmltools/blob/master/tests/xgboost/test_xgboost_converters.py

**Comment by trivialfis** [comment] 2020-02-23 06:31
Sure.  Onnx is a great format.  PRs are welcomed. :-)

**Comment by trivialfis** [comment] 2020-02-24 09:48
Will wait until DMatrix refactoring is done.  I had an experimental implementation for in-place prediction, which is thread safe.

**Comment by mmccarty** [comment] 2020-02-24 13:54
@trivialfis Thank you for the quick replies. We would be happy to contribute to a solution once a clear path forward is determined. Here is a minimum example to reproduce the problem that will hopefully provide context.

```
import copy
import concurrent.futures

import numpy as np
from sklearn.datasets import make_classification

from xgboost import XGBClassifier

X, y = make_classification(n_samples=5000, n_informative=10)

# get baseline model and predictions
threaded_model = XGBClassifier(n_estimators=250, max_depth=5, n_jobs=2, nthread=2, seed=0)
threaded_model.fit(X, y)

original_predictions = threaded_model.predict_proba(X)[:, 1]

def predict(model, data):
    return model.predict_proba(data)[:, 1]

# with threaded model - no copy
n_threads = 10

with concurrent.futures.ThreadPoolExecutor() as executor:
    threads = {
        executor.submit(predict, threaded_model, X): i_thread for i_thread in range(n_threads)
    }

    total_differences = 0

    for future in concurrent.futures.as_completed(threads):
        i_thread = threads[future]
        result = future.result()
        diffs = np.sum(result != original_predictions)
        total_differences += diffs
        print(f"Thread {i_thread} has {diffs} differences")   

    assert total_differences == 0, f"{total_differences} differences across {n_threads} threads"
```

**Comment by kylejn27** [comment] 2020-03-05 15:46
While #5389 is in progress, ONNX is something that we're interested in. Is there any reason to _not_ use it or anything that we should look out for, problems with it, etc?

**Comment by trivialfis** [comment] 2020-03-06 03:56
No.  It's definitely an interesting option.  I tested the regression model myself but that's all I know right now.  Maybe in long term we can have a native exporter for it so we can have more testings done.  But feel free to evaluate both options.

**Comment by sandys** [comment] 2020-03-06 04:00
The ONNX project itself is willing to add/modify to support the full
Xgboost usecase

https://github.com/onnx/onnx/issues/2621

**Comment by trivialfis** [comment] 2020-03-06 04:09
Yup.  That's great news.  I need the inplace prediction to help accelerating grid searching in dask ml(and any other similar libraries).  Let me know if there's anything I can help with the onnx model converter.

**Comment by trivialfis** [comment] 2020-03-30 07:36
Merged https://github.com/dmlc/xgboost/pull/5389

**Closed** 2020-03-30 07:36 UTC
Labels: feature-request

**Comment by kylejn27** [comment] 2020-03-30 14:19
@trivialfis thanks! I'm seeing this issue fixed on our end from your PR

**Comment by trivialfis** [comment] 2020-03-30 15:07
Happy to help here. :-)
