### ISSUE TITLE
[CI] Tests with external memory sometimes fail because of left-over temporary files

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#5580] opened 2020-04-21 22:59 UTC
https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-5577/1/pipeline#step-266-log-1952

"/workspace/src/data/./sparse_page_source.h:124: Cache file tmptmp_.row.page exists already; Is there another DMatrix with the same cache prefix? Otherwise please remove it manually."

Right now, I have to re-create workers from scratch to recover from this error.

**Comment by hcho3** [comment] 2020-05-26 07:09
Often this error occurs together with error
```
[06:11:34] /workspace/dmlc-core/src/data/csv_parser.h:130: Delimiter 'num_feature' is
  not found in the line. Expected 'num_feature' as the delimiter to separate fields.
```

**Comment by wilsoncwj** [comment] 2020-07-22 15:49
I am currently also experiencing this issue as well:

`Cache file dtrain.cache exists already; Is there another DMatrix with the same cache prefix? Otherwise please remove it manually.`

I'm not exactly sure where to find and delete this cache file. Running the code in a docker container with a mounted local drive.

**Comment by trivialfis** [comment] 2020-10-19 11:58
The issue is unrelated to left over files.  Closing.  As for the error:

```
Cache file dtrain.cache exists already; Is there another DMatrix with the same cache prefix? Otherwise please remove it manually.
```

It might be caused by some other errors and the process is not correctly terminated.  Please open a new issue when there's a reproducible example.

**Closed by trivialfis** 2020-10-19 11:58 UTC
Labels: CI, type: bug
