### ISSUE TITLE
Visual Studio 2017 LNK1181 error.

### ISSUE THREAD

**Issue by saeed-abdul-rahim** [dmlc/xgboost#2720] opened 2017-09-18 06:59 UTC
I'm a newbie.
I used this code for cmake:
     cmake .. -G "Visual Studio 15 2017 Win64" -DUSE_CUDA=ON
When I'm building xgboost.sln file, I'm getting an error:
     LNK1181	cannot open input file 'Release\gpuxgboost.lib'
OS : Windows 10 64bit
GPU : Nvidia Geforce 930M
Any help is appreciated. Thank you.

**Comment by RAMitchell** [comment] 2017-09-18 10:26
It would probably be safest to use Visual Studio 2015 as this is the only version it is being tested on. I will make a note in the documentation.

**Comment by putsandcalls** [comment] 2017-10-01 11:46
Hi I am compiling on VS 2015 and am having the same trouble. Please help with this

**Comment by betterze** [comment] 2017-10-01 22:38
I also meet this problem, help some one can answer it

**Comment by varneyo** [comment] 2018-02-09 13:09
Did anyone find a solution for this. Tried various approaches and still coming up short.

**Comment by khotilov** [comment] 2018-02-09 16:11
Please provide a full log.

**Comment by varneyo** [comment] 2018-02-09 16:20
Hi Khotilov, 

I am trying to get XGBoost running with GPU support.
It seems like I have tried everything but I probably have missed something silly. 
I have followed the steps:
1. git clone --recursive https://github.com/dmlc/xgboost 
2. mkdir build 
3. cd build
4. cmake .. -G"Visual Studio 14 2015 Win64" -DUSE_CUDA=ON
5. Build solution in Visual Studio (tried both VS 2015 and 2017)

I have successfully built the project without the DUSE_CUDA=ON parameter but my builds fail when this parameter is added. I have tried multiple versions of the CUDA toolkit. I have a GTX 1070. 

I keep seeing this:
fatal error LNK1181: cannot open input file 'Release\gpuxgboost.lib'

[Visual_Studios_Build_log.txt](https://github.com/dmlc/xgboost/files/1711635/Visual_Studios_Build_log.txt)

Any help would be greatly appreciated.

**Comment by khotilov** [comment] 2018-02-09 16:31
The library is not built because there are compilation errors, e.g. `C:/Users/olive/xgboost/src/objective/regression_obj_gpu.cu(46): error : identifier "uint" is undefined`
Those were fixed in #3051, so I think it was a while since you did git clone.

**Comment by varneyo** [comment] 2018-02-09 17:24
Cleared all my directories and started from scratch and it has worked this time. Not sure if I had the latest update as you suggest. Thanks for the help

**Closed** 2018-02-09 18:02 UTC
