### ISSUE TITLE
cannot import name 'lazy_isinstance' from 'xgboost.compat'

### ISSUE THREAD

**Issue by s0810110** [dmlc/xgboost#7797] opened 2022-04-11 15:10 UTC
This issue has been found when importing xgboost in jupyter lab. I have tried using Xgboost versions 1.5.1 and 1.5.2 and the same error occurs. I have also tried deleting and re-installing Xgboost. Changing to version 1.0.1 did not resolve the issue. 

![image](https://user-images.githubusercontent.com/10169207/162769616-9e064883-2a81-4f11-986e-46e8b32552a8.png)

Solving this issue would benefit the Xgboost user community!

**Comment by trivialfis** [comment] 2022-04-12 03:54
How did you install XGBoost?

**Comment by s0810110** [comment] 2022-04-12 11:06
@trivialfis. I had used pip install Xgboost==1.5.2 within jupyter lab

**Comment by trivialfis** [comment] 2022-04-13 06:40
I can't reproduce this.  Please start a fresh Python environment and try again.  I suspect there are some errors in the installation.

**Comment by s0810110** [comment] 2022-04-13 12:25
when I remove manually references to lazy, the package worked. Is there any negative effects from doing this? How do you means starting a fresh environment in practical terms, do you mean restart the jupyter session?

**Comment by trivialfis** [comment] 2022-04-13 13:39
> Is there any negative effects from doing this?

Yes. Any section of code that uses this function will stop working.

> How do you means starting a fresh environment in practical terms, do you mean restart the jupyter session?

Apologies for the ambiguity. I meant recreating the Python environment like virtualenv or conda env, so that we can reinstall the packages without conflicts.

**Comment by trivialfis** [comment] 2022-04-16 04:49
Closing as I don't think this is a bug in XGBoost.  If importing somehow breaks there's a deeper issue in the Python environment.

**Closed by trivialfis** 2022-04-16 04:49 UTC
Labels: status: need update
