### ISSUE TITLE
plot_tree for multiclass crashed

### ISSUE THREAD

**Issue by aleixrvr** [dmlc/xgboost#9646] opened 2023-10-09 10:37 UTC
I'm using the new v2.0 xgboost for multiclass regression and the function plot_tree crashes. 

This is an example inspired in the documentation https://xgboost.readthedocs.io/en/stable/python/examples/multioutput_regression.html

### Example

```
import numpy as np
import xgboost as xgb

rng = np.random.RandomState(1994)
X = np.sort(200 * rng.rand(100, 1) - 100, axis=0)
y = np.array([np.pi * np.sin(X).ravel(), np.pi * np.cos(X).ravel()]).T
y[::5, :] += 0.5 - rng.rand(20, 2)
y = y - y.min()
y = y / y.max()

reg = xgb.XGBRegressor(
    tree_method="hist",
    n_estimators=128,
    n_jobs=16,
    max_depth=8,
    multi_strategy="multi_output_tree",
    subsample=0.6,
)
reg.fit(X, y, eval_set=[(X, y)])

xgb.plot_tree(reg)
```

**Comment by trivialfis** [comment] 2023-10-09 11:50
It's a highly experimental feature as noted in the demo. Anything not shown in that demo can be assumed to be not yet supported.

**Comment by trivialfis** [comment] 2023-10-11 07:54
Closing in favor of https://github.com/dmlc/xgboost/issues/9043 .

**Comment by trivialfis** [comment] 2023-10-11 07:54
Just to clarify, xgboost works with classification since day 1. The issue here is using regression with `multi_output_tree`.

**Closed by trivialfis** 2023-10-11 07:54 UTC

**Comment by aleixrvr** [comment] 2023-10-11 12:29
Ok, thanks! I will wait until it is implemented!
