### ISSUE TITLE
[jvm-packages] Updated code now complains labels must be integers between 0 and 100

### ISSUE THREAD

**Issue by obones** [dmlc/xgboost#10830] opened 2024-09-19 14:32 UTC
Hello,

I'm sorry for creating an issue here, but I never received the activation email for the forum, despite using two totally unrelated emails.

Back in 2017 I wrote code using xgboost to train models with the following Scala code in a Spark environment:

```scala
import ml.dmlc.xgboost4j.scala.spark.{TrackerConf, XGBoost, XGBoostModel, XGBoostRegressionModel}

  val xgModel = XGBoost.trainWithDataFrame(
    sourceData,
    paramMap,
    round = numRound,
    nWorkers = numWorkers,
    useExternalMemory = true,
    labelCol = labelColName)
```

This has been running just fine but there is a need to update Spark / Scala and xgboost so as not to trail so far away behind the current versions.

I understand that `trainWithDataFrame` has been deprecated for quite a while now and looking at diffs on code samples in this project, I came up with this replacement code:

```scala
import ml.dmlc.xgboost4j.scala.spark.{TrackerConf, XGBoost, XGBoostClassifier, XGBoostRegressionModel}

  val xgModel = new XGBoostClassifier(paramMap)
    .setLabelCol(labelColName)
    .setUseExternalMemory(true)
    .setNumRound(numRound)
    .setNumWorkers(numWorkers)
    .fit(sourceData)
```

While this compile, I get these two kind of errors when running it:

```
Labels MUST be Integers, but got 0.025167444248986596
Labels MUST be in [0, 100), but got 117.31
```

I must have missed something here as this was not an issue in the past.

I tried replacing `XGBoostClassifier` with `XGBoostRegressor` and while it does not complain about the values, it still fails with this error:

```
ml.dmlc.xgboost4j.java.XGBoostError: [16:22:59] D:\a\xgboost\xgboost\src\collective\socket.cc:29: Failed to get addr info for: scala, error: Hôte inconnu.
        at ml.dmlc.xgboost4j.java.XGBoostJNI.checkCall(XGBoostJNI.java:48)
        at ml.dmlc.xgboost4j.java.RabitTracker.<init>(RabitTracker.java:50)
        at ml.dmlc.xgboost4j.scala.spark.XGBoost$.withTracker(XGBoost.scala:462)
        at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:501)
        at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.train(XGBoostRegressor.scala:198)
        at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.train(XGBoostRegressor.scala:36)
        at org.apache.spark.ml.Predictor.fit(Predictor.scala:114)
        at com.mycompany.MyTest.xgboost_issue(MyTest.scala:105)
```

Seems to be quite unrelated, I'll dig into this direction as well, but I'd really like to have an opinion on my updated code presented above.

Thanks a lot for your help and patience

**Comment by obones** [comment] 2024-09-19 15:34
> Seems to be quite unrelated, I'll dig into this direction as well, [...]

Well, it is indeed, as I was giving a `tracker_conf` parameter that was set to this: `new TrackerConf(0, "scala")`.
Removing it altogether makes the training start, but it never ends, staying there eating 2 CPUs which is utterly surprising to me as the source data is read from a CSV file that only has 21100 rows even filtered down to 6270 (as given by the `train.count()` method call)

**Comment by trivialfis** [comment] 2024-09-19 18:17
cc @wbo4958 .

**Comment by wbo4958** [comment] 2024-09-20 02:38
Hi @obones, This is the correct place to file issues. 

So do you have a sample code and sample dataset to repro it.

I never saw "Labels MUST" in the codebase of xgboost. But it's good to repro it if possible. Thx

**Comment by obones** [comment] 2024-09-20 09:02
Here is the sample code. Note that it's not really clean with special options as I'm running with Java 11 under Windows, but it shows the issue every time.

```scala
    def xgboost_issue(): Unit = {
      System.setProperty("hadoop.home.dir", "D:\\Spark\\hadoop-winutils\\hadoop-3.3.6")
      val conf = new SparkConf()
        .setAppName("TestApp")
        .set("spark.driver.memory", "8g")
        .set("spark.executor.memory", "8g")
        .set("spark.network.timeout", "120s")
        .set("spark.sql.warehouse.dir", "D:\\Spark\\warehouse")
      val sc = SparkContext.getOrCreate(conf.setMaster("local[8]"))
      val session  = new SparkSession.Builder().getOrCreate()
      val sqlContext = session.sqlContext
      sc.setCheckpointDir("d:\\Spark\\Checkpoints")
      import session.implicits._

      var sourceData = session.read.format("csv").
        option("header", "true").
        option("delimiter", ";").
        option("inferSchema", "true").
        load("D:\\Spark\\Damage.csv")

      val name_out = "Claim_cost"
      val names_inp = Array("Age","Area","color","Fuel","Garage","Gender","Marital","Region","Vehicle")
      val names_inp_indexed = Array("Age","Area_Indexed","color_Indexed","Fuel_Indexed","Garage_Indexed","Gender_Indexed","Marital_Indexed","Region_Indexed","Vehicle_Indexed")

      sourceData = new StringIndexer().setInputCol("Area").setOutputCol("Area_Indexed").fit(sourceData).transform(sourceData)
      sourceData = new StringIndexer().setInputCol("color").setOutputCol("color_Indexed").fit(sourceData).transform(sourceData)
      sourceData = new StringIndexer().setInputCol("Fuel").setOutputCol("Fuel_Indexed").fit(sourceData).transform(sourceData)
      sourceData = new StringIndexer().setInputCol("Garage").setOutputCol("Garage_Indexed").fit(sourceData).transform(sourceData)
      sourceData = new StringIndexer().setInputCol("Gender").setOutputCol("Gender_Indexed").fit(sourceData).transform(sourceData)
      sourceData = new StringIndexer().setInputCol("Marital").setOutputCol("Marital_Indexed").fit(sourceData).transform(sourceData)
      sourceData = new StringIndexer().setInputCol("Region").setOutputCol("Region_Indexed").fit(sourceData).transform(sourceData)
      sourceData = new StringIndexer().setInputCol("Vehicle").setOutputCol("Vehicle_Indexed").fit(sourceData).transform(sourceData)

      val assembler = new VectorAssembler()
        .setInputCols(Array("Age","Area_Indexed","color_Indexed","Fuel_Indexed","Garage_Indexed","Gender_Indexed","Marital_Indexed","Region_Indexed","Vehicle_Indexed"))
        .setOutputCol("features")
        .setHandleInvalid("keep")

      val Data = assembler.transform(sourceData)
      Console.println("Data count = " + Data.count())

      val train = Data.where($"Sample" < 0.7)
      Console.println("train count = " + train.count())

      val test = Data.where($"Sample" > 0.7)
      Console.println("data size = " + test.count())

      val trackerConf = new TrackerConf(10) //, "scala")
      val numRound = 1
      val paramMap = List(
         "tracker_conf" -> trackerConf,
          "max_depth" -> 1,
          "eta" -> 1.0,
          "subsample" -> 1.0,
          "objective" -> "reg:linear").toMap

      val xgboostModel = new XGBoostClassifier(paramMap)
          .setLabelCol(name_out)
          .setUseExternalMemory(true)
          .setNumRound(numRound)
          .setNumWorkers(8)
          .fit(train)

      val yhat = xgboostModel.transform(test)

      yhat.select("prediction").show(40)
    }
```

The `hadoop-winutils` folder is a checkout of https://github.com/cdarlint/winutils.git
And the csv file is this one:

[Damage.zip](https://github.com/user-attachments/files/17072565/Damage.zip)

If I run with the code above I get the errors mentioning issues with label values.

If I replace `XGBoostClassifier` with `XGBoostRegressor` the above code never ends and at first I did not have any error message.
But I added `` to the list of dependencies in the POM file and now I see this:

```
ERROR DataBatch: java.lang.RuntimeException: you can only specify missing value as 0.0 (the currently set value NaN) when you have SparseVector or Empty vector as your feature format. If you didn't use Spark's VectorAssembler class to build your feature vector but instead did so in a way that preserves zeros in your feature vector you can avoid this check by using the 'allow_non_zero_for_missing parameter' (only use if you know what you are doing)
```

But I'm not sure what to do of it, and even then, I don't know why it never stops despite the errors.

Some details about the environment:

IDE: VSCode
Build: maven
Java: 11
OS: Windows 10/Windows 11
Dependencies:
org.scala-lang:scala-library:2.13.11
org.apache.spark:spark-core_2.13:3.5.2
org.apache.spark:spark-sql_2.13:3.5.2
org.apache.spark:spark-mllib_2.13:3.5.2
ml.dmlc:xgboost4j_2.13:2.1.1
ml.dmlc:xgboost4j-spark_2.13:2.1.1
org.slf4j:slf4j-simple:2.0.16

**Comment by wbo4958** [comment] 2024-09-23 02:26
Hi @obones, Looks like it's the regression case instead of classification. Please double check the label `Claim_cost` column.

If so, please change XGBoostClassifier to XGBoostRegressor. Please remove the "val trackerConf = new TrackerConf(10) //, "scala")"  to try.

**Comment by obones** [comment] 2024-09-23 06:48
Thanks for your reply, you are indeed correct, this is a regression case.

But when I replace XGBoostClassifier with XGBoostRegressor the above code never ends, it sits there consuming two CPUs.
There is this error message in the log though:

```
ERROR DataBatch: java.lang.RuntimeException: you can only specify missing value as 0.0 (the currently set value NaN) when you have SparseVector or Empty vector as your feature format. If you didn't use Spark's VectorAssembler class to build your feature vector but instead did so in a way that preserves zeros in your feature vector you can avoid this check by using the 'allow_non_zero_for_missing parameter' (only use if you know what you are doing)
```

I'm not sure what to make of this as I'm using the VectorAssembler.

**Comment by wbo4958** [comment] 2024-09-23 10:10
please set `allow_non_zero_for_missing=true`

**Comment by obones** [comment] 2024-09-23 14:37
Ah ! This made it !
Thanks a lot for your help.

So to sum up, remove the `TrackerConf` instance and add the `allow_non_zero_for_missing` value inside `ParamMap`.

**Comment by wbo4958** [comment] 2024-09-23 23:13
Glad to hear that it worked for you. Please close this issue if possible.

**Closed** 2024-09-24 06:42 UTC
