### ISSUE TITLE
xgboost 1.4.1 osx build failure on Mojave

### ISSUE THREAD

**Issue by chenrui333** [dmlc/xgboost#6890] opened 2021-04-21 22:51 UTC
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>build failure on 10.14</summary>

```
[ 90%] Building CXX object src/CMakeFiles/objxgboost.dir/tree/updater_refresh.cc.o
cd /tmp/xgboost-20210420-54288-x2xcx8/build/src && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DDMLC_CORE_USE_CMAKE -DDMLC_LOG_CUSTOMIZE=1 -DDMLC_USE_CXX11=1 -DXGBOOST_BUILTIN_PREFETCH_PRESENT=1 -DXGBOOST_MM_PREFETCH_PRESENT=1 -D_MWAITXINTRIN_H_INCLUDED -D__USE_XOPEN2K8 -I/tmp/xgboost-20210420-54288-x2xcx8/include -I/tmp/xgboost-20210420-54288-x2xcx8/dmlc-core/include -I/tmp/xgboost-20210420-54288-x2xcx8/rabit/include -I/tmp/xgboost-20210420-54288-x2xcx8/build/dmlc-core/include -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fPIC -funroll-loops -Xclang -fopenmp -std=gnu++14 -MD -MT src/CMakeFiles/objxgboost.dir/tree/updater_refresh.cc.o -MF CMakeFiles/objxgboost.dir/tree/updater_refresh.cc.o.d -o CMakeFiles/objxgboost.dir/tree/updater_refresh.cc.o -c /tmp/xgboost-20210420-54288-x2xcx8/src/tree/updater_refresh.cc
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
[ 91%] Building CXX object src/CMakeFiles/objxgboost.dir/tree/updater_sync.cc.o
cd /tmp/xgboost-20210420-54288-x2xcx8/build/src && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DDMLC_CORE_USE_CMAKE -DDMLC_LOG_CUSTOMIZE=1 -DDMLC_USE_CXX11=1 -DXGBOOST_BUILTIN_PREFETCH_PRESENT=1 -DXGBOOST_MM_PREFETCH_PRESENT=1 -D_MWAITXINTRIN_H_INCLUDED -D__USE_XOPEN2K8 -I/tmp/xgboost-20210420-54288-x2xcx8/include -I/tmp/xgboost-20210420-54288-x2xcx8/dmlc-core/include -I/tmp/xgboost-20210420-54288-x2xcx8/rabit/include -I/tmp/xgboost-20210420-54288-x2xcx8/build/dmlc-core/include -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fPIC -funroll-loops -Xclang -fopenmp -std=gnu++14 -MD -MT src/CMakeFiles/objxgboost.dir/tree/updater_sync.cc.o -MF CMakeFiles/objxgboost.dir/tree/updater_sync.cc.o.d -o CMakeFiles/objxgboost.dir/tree/updater_sync.cc.o -c /tmp/xgboost-20210420-54288-x2xcx8/src/tree/updater_sync.cc
clang: note: diagnostic msg:
```

</details>

Full build log is in here, https://github.com/Homebrew/homebrew-core/runs/2388620981
relates to https://github.com/Homebrew/homebrew-core/pull/75561

**Comment by hcho3** [comment] 2021-04-21 23:01
It appears that the problem is specific to Apple Clang 11. The build is successful with Apple Clang 10 + MacOS Mojave: https://travis-ci.org/github/dmlc/xgboost/jobs/767905619

**Comment by trivialfis** [comment] 2022-10-10 05:27
@hcho3 Do you know the current status of building xgboost on latest macos?

**Comment by hcho3** [comment] 2022-10-10 05:33
It's been fixed now. https://github.com/Homebrew/homebrew-core/commit/d0a9a865eac6ae4fa90ae33b24657933a097c84a

**Closed** 2022-10-10 05:33 UTC
Labels: status: help wanted
