### ISSUE TITLE
xgboost on spark version 0.9 got Exception (java.util.NoSuchElementException,key not found: train)

### ISSUE THREAD

**Issue by liuyonglang** [dmlc/xgboost#6806] opened 2021-03-30 02:59 UTC
FYI，when i use xgboost on spark 0.9 version to fit a model ,wo get this Exception(java.util.NoSuchElementException,key not found: train)。what condition can lead to the problem?  Thanks for your attention
follow is my paramters:

XGBoostSpark: Running XGBoost 0.90 with parameters:
alpha -> 0.29174557458107453
min_child_weight -> 2.7498486288961455
sample_type -> uniform
base_score -> 0.5
colsample_bylevel -> 0.7423861022776388
grow_policy -> lossguide
skip_drop -> 0.0
lambda_bias -> 0.20602638227615486
silent -> 0
scale_pos_weight -> 1.0
seed -> 12345
cache_training_set -> false
features_col -> importance_vec
num_early_stopping_rounds -> 0
label_col -> C25
num_workers -> 2
subsample -> 1.0
lambda -> 1.0
max_depth -> 4
probability_col -> probability
raw_prediction_col -> rawPrediction
tree_limit -> 0
custom_eval -> null
rate_drop -> 0.0
max_bin -> 16
train_test_ratio -> 0.9
use_external_memory -> false
objective -> binary:logistic
eval_metric -> logloss
num_round -> 23
timeout_request_workers -> 1800000
missing -> 0.0
checkpoint_path -> 
tracker_conf -> TrackerConf(0,python)
tree_method -> hist
max_delta_step -> 0.0
eta -> 0.001200144733197779
verbosity -> 1
colsample_bytree -> 0.6367027366379028
normalize_type -> tree
custom_obj -> null
gamma -> 0.0
sketch_eps -> 0.03
nthread -> 1
prediction_col -> prediction
checkpoint_interval -> -1

**Comment by trivialfis** [comment] 2021-03-30 03:45
Could you please provide a reproducible example?

**Comment by liuyonglang** [comment] 2021-03-30 06:08
> Could you please provide a reproducible example?

it is like this:
https://github.com/dmlc/xgboost/pull/4380#issuecomment-486047797.
but I dont found what the solution finally.

**Comment by wbo4958** [comment] 2021-04-06 01:15
@liuyonglang Can you try the latest xgboost release and see if the issue is still there, if yes, pls provide your reproducible sample. thx

**Comment by liuyonglang** [comment] 2021-04-08 06:48
> @liuyonglang Can you try the latest xgboost release and see if the issue is still there, if yes, pls provide your reproducible sample. thx

Thanks for you reply. Because I use spark 2.4.3, so I cannot change to the latest xgboost release. But when I dont set the parameter (num_workers) ,this problem disappear.

**Comment by liuyonglang** [comment] 2021-04-08 06:51
> > @liuyonglang Can you try the latest xgboost release and see if the issue is still there, if yes, pls provide your reproducible sample. thx
> 
> Thanks for you reply. Because I use spark 2.4.3, so I cannot change to the latest xgboost release. But when I dont set the parameter (num_workers) ,this problem disappear.

So, I gusses there are some confict between xgbbost's num_workers and spark's executor or something else.

**Comment by wbo4958** [comment] 2021-04-11 01:02
@liuyonglang  there is an empty dataset in your partition, which didn't be handled very well. It is supposed to throw an exception.

**Comment by liuyonglang** [comment] 2021-04-16 01:39
> @liuyonglang there is an empty dataset in your partition, which didn't be handled very well. It is supposed to throw an exception.

yeah, I got it.thanks very well.

**Comment by wbo4958** [comment] 2021-04-19 22:56
PR merged. @liuyonglang Could you pls close this issue?

**Comment by trivialfis** [comment] 2021-04-20 00:57
@wbo4958 Thanks for the fix!

**Closed by trivialfis** 2021-04-20 00:57 UTC

**Comment by liuyonglang** [comment] 2021-04-21 09:31
> PR merged. @liuyonglang Could you pls close this issue?

OK, thanks for you propse.
