### ISSUE TITLE
GPU initialization error on multiprocessing

### ISSUE THREAD

**Issue by colinfang** [dmlc/xgboost#6899] opened 2021-04-23 01:51 UTC
v1.3.3 on linux

```python
from multiprocessing.pool import Pool
import numpy as np
import xgboost as xgb


def worker():
    rng = np.random.default_rng(1)
    data = rng.random((100, 2))
    label = rng.integers(2, size=100)
    # It only works if `nthread = 1`
    dtrain = xgb.DMatrix(data, label=label, nthread=1)
    param = {'objective': 'binary:logistic', 'eval_metric': 'logloss', 'nthread': 1}
    param['gpu_id'] = 0
    bst = xgb.train(param, dtrain, 2, [])

def main():
    pool = Pool(1)
    r = pool.apply_async(worker)
    r.get()
    pool.close()
    pool.join()
    worker()

if __name__ == '__main__':
    main()
    # The 2nd time it deadlock
    main()
    print('done')
```

This shows

```
xgboost.core.XGBoostError: [01:50:07] ../src/c_api/../data/../common/common.h:44: ../src/common/host_device_vector.cu: 259: initialization error
```

**Comment by trivialfis** [comment] 2021-04-23 03:20
This is a limitation in CUDA runtime, similar to the openmp issue you posted.  Another similar issue is https://github.com/dmlc/xgboost/issues/4246 .

**Comment by trivialfis** [comment] 2021-04-28 17:29
Closing as the issue is in underlying runtime instead of xgboost.

**Closed by trivialfis** 2021-04-28 17:29 UTC
