### ISSUE TITLE
Scala's XGBoost.train throws an exception even though the model training completes successfully 

### ISSUE THREAD

**Issue by ypopkov** [dmlc/xgboost#940] opened 2016-03-08 16:34 UTC
I've been playing with the new scala API and I've noticed that XGBoost.train throws an exception which results in the returned model being null (but the training completes successfully nevertheless). This with the latest spark 1.6 and xgboost code. #884 #935

Any ideas? 

```
macos$ spark-shell --driver-memory 2g --executor-memory 8g --master local[2] --jars /path/to/xgboost/jvm-packages/xgboost4j-spark/target/xgboost4j-spark-0.5-jar-with-dependencies.jar 
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 1.6.1
      /_/

Using Scala version 2.10.5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_45)
Type in expressions to have them evaluated.
Type :help for more information.
Spark context available as sc.
SQL context available as sqlContext.

scala> import org.apache.spark.mllib.util.MLUtils
scala> import ml.dmlc.xgboost4j.scala.spark.XGBoost
iscala> import ml.dmlc.xgboost4j.scala.DMatrix
scala> val trainRDD = MLUtils.loadLibSVMFile(sc, "my_libsvm_data.txt", 1967)
trainRDD: org.apache.spark.rdd.RDD[org.apache.spark.mllib.regression.LabeledPoint] = MapPartitionsRDD[5] at map at MLUtils.scala:108
scala> trainRDD.partitions.size
res1: Int = 2
scala> trainRDD.count
res0: Long = 35970
scala> val model = XGBoost.train(trainRDD,  Map("eta" -> 0.1, "max_depth" -> 5, "objective" -> "binary:logistic", "silent" -> 1), 200)
model: ml.dmlc.xgboost4j.scala.spark.XGBoostModel = null

scala> Exception in thread "Thread-64" java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.spark.scheduler.JobWaiter.awaitResult(JobWaiter.scala:73)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:612)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1832)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1845)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1858)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1929)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:920)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:918)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:918)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anon$2.run(XGBoost.scala:72)
[Stage 1:>                                                          (0 + 2) / 2][0]	train-error:0.047871
[0]	train-error:0.048265
[Stage 2:>                                                          (0 + 2) / 2][1]	train-error:0.048204
[1]	train-error:0.047598
[2]	train-error:0.046925
[2]	train-error:0.047209
[3]	train-error:0.047148
[3]	train-error:0.046875
[4]	train-error:0.047148
[4]	train-error:0.046541
...
[190]	train-error:0.029081
[193]	train-error:0.029078
[191]	train-error:0.029026
[194]	train-error:0.029023
[195]	train-error:0.028911
[192]	train-error:0.028915
[196]	train-error:0.028800
[193]	train-error:0.028748
[197]	train-error:0.028800
[194]	train-error:0.028748
[195]	train-error:0.028692
[198]	train-error:0.028856
[196]	train-error:0.028637
[199]	train-error:0.028689
[Stage 2:=============================>                             (1 + 1) / 2][197]	train-error:0.028637
[198]	train-error:0.028581
[199]	train-error:0.028637
```

**Comment by CodingCat** [comment] 2016-03-08 16:53
would you please set silent as "0" and check what it says

**Comment by ypopkov** [comment] 2016-03-08 16:57
Thanks for looking into this!
```
scala> val model = XGBoost.train(trainRDD,  Map("eta" -> 0.1, "max_depth" -> 5, "objective" -> "binary:logistic", "silent" -> 0), 200)
model: ml.dmlc.xgboost4j.scala.spark.XGBoostModel = null

scala> Exception in thread "Thread-64" java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.spark.scheduler.JobWaiter.awaitResult(JobWaiter.scala:73)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:612)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1832)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1845)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1858)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1929)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:920)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:918)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:918)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anon$2.run(XGBoost.scala:72)
[Stage 2:>                                                          (0 + 2) / 2][11:55:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 58 extra nodes, 0 pruned nodes, max_depth=5
[11:55:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 58 extra nodes, 0 pruned nodes, max_depth=5
[0]	train-error:0.048265
[0]	train-error:0.047871
[11:55:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 62 extra nodes, 0 pruned nodes, max_depth=5
[11:55:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 58 extra nodes, 0 pruned nodes, max_depth=5
[1]	train-error:0.047598
[1]	train-error:0.048204
[11:55:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 60 extra nodes, 0 pruned nodes, max_depth=5
[2]	train-error:0.047209
[11:55:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 60 extra nodes, 0 pruned nodes, max_depth=5
[2]	train-error:0.046925
[11:55:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 62 extra nodes, 0 pruned nodes, max_depth=5
[11:55:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 62 extra nodes, 0 pruned nodes, max_depth=5
[3]	train-error:0.047148
[3]	train-error:0.046875
[11:55:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 62 extra nodes, 0 pruned nodes, max_depth=5
[4]	train-error:0.047148
[11:55:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 60 extra nodes, 0 pruned nodes, max_depth=5
[4]	train-error:0.046541
[11:55:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 62 extra nodes, 0 pruned nodes, max_depth=5
[5]	train-error:0.047037
[11:55:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 60 extra nodes, 0 pruned nodes, max_depth=5
[5]	train-error:0.046041
...
[193]	train-error:0.028748
[11:55:27] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 22 extra nodes, 0 pruned nodes, max_depth=5
[194]	train-error:0.028748
[11:55:27] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 16 extra nodes, 0 pruned nodes, max_depth=5
[198]	train-error:0.028856
[11:55:27] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 18 extra nodes, 0 pruned nodes, max_depth=5
[195]	train-error:0.028692
[11:55:27] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 32 extra nodes, 0 pruned nodes, max_depth=5
[199]	train-error:0.028689
[11:55:27] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 24 extra nodes, 0 pruned nodes, max_depth=5
[196]	train-error:0.028637
[Stage 2:=============================>                             (1 + 1) / 2][11:55:27] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 20 extra nodes, 0 pruned nodes, max_depth=5
[197]	train-error:0.028637
[11:55:27] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 30 extra nodes, 0 pruned nodes, max_depth=5
[198]	train-error:0.028581
[11:55:27] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 20 extra nodes, 0 pruned nodes, max_depth=5
[199]	train-error:0.028637
```

**Comment by CodingCat** [comment] 2016-03-08 17:14
OK, I will try to reproduce what happened here this evening, it seems that the RabitTracker ends with a non-zero code, and we intentionally terminate the spark training job....

**Comment by CodingCat** [comment] 2016-03-08 23:09
hey, @ypopkov , I tried to reproduce this in my side, but no luck 

can you enable more logs in your spark configuration (set to INFO) and post the complete log trace here, I think your rabit tracker is failed to start for some reason....

**Comment by ypopkov** [comment] 2016-03-08 23:17
you are right, I am getting a socket error - thanks for the pointer! I will try to figure out what's going on here.

'''
scala> val model = XGBoost.train(trainRDD,  Map("eta" -> 0.1, "max_depth" -> 5, "objective" -> "binary:logistic", "silent" -> 0), 200)
16/03/08 18:14:38 INFO RabitTracker$TrackerProcessLogger: Traceback (most recent call last):
16/03/08 18:14:38 INFO RabitTracker$TrackerProcessLogger:   File "/var/folders/zp/h3dbffp54l7_yynrvt37yn_w0000gn/T/tracker7160282413333118290.py", line 474, in <module>
16/03/08 18:14:38 INFO RabitTracker$TrackerProcessLogger:     main()
16/03/08 18:14:38 INFO RabitTracker$TrackerProcessLogger:   File "/var/folders/zp/h3dbffp54l7_yynrvt37yn_w0000gn/T/tracker7160282413333118290.py", line 469, in main
16/03/08 18:14:38 INFO RabitTracker$TrackerProcessLogger:     start_rabit_tracker(args)
16/03/08 18:14:38 INFO RabitTracker$TrackerProcessLogger:   File "/var/folders/zp/h3dbffp54l7_yynrvt37yn_w0000gn/T/tracker7160282413333118290.py", line 431, in start_rabit_tracker
16/03/08 18:14:38 INFO RabitTracker$TrackerProcessLogger:     rabit = RabitTracker(hostIP=get_host_ip(args.host_ip), nslave=args.num_workers)
16/03/08 18:14:38 INFO RabitTracker$TrackerProcessLogger:   File "/var/folders/zp/h3dbffp54l7_yynrvt37yn_w0000gn/T/tracker7160282413333118290.py", line 145, in __init__
16/03/08 18:14:38 INFO RabitTracker$TrackerProcessLogger:     sock.bind((hostIP, port))
16/03/08 18:14:38 INFO RabitTracker$TrackerProcessLogger:   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
16/03/08 18:14:38 INFO RabitTracker$TrackerProcessLogger:     return getattr(self._sock,name)(*args)
16/03/08 18:14:38 INFO RabitTracker$TrackerProcessLogger: socket.error: [Errno 48] Address already in use
16/03/08 18:14:38 INFO RabitTracker$TrackerProcessLogger: Exception AttributeError: "'RabitTracker' object has no attribute 'sock'" in <bound method RabitTracker.__del__ of <__main__.RabitTracker object at 0x10913ce50>> ignored
16/03/08 18:14:38 INFO RabitTracker$TrackerProcessLogger: Tracker Process ends with exit code 1
16/03/08 18:14:38 INFO RabitTracker: Tracker Process ends with exit code 1
16/03/08 18:14:38 INFO XGBoostSpark: Rabit returns with exit code 1
model: ml.dmlc.xgboost4j.scala.spark.XGBoostModel = null
'''

**Comment by tqchen** [comment] 2016-03-08 23:59
seems that rabit tries to bind a address that is already occupied. To give you more information, what happens in tracker.start() is that it calls python tracker script to start listen on the driver. Though it should try multiple ports before it successffuly grab one.

You can also try to start the tracker manually via 
```
python dmlc-core/tracker/dmlc_tracker/tracker.py
```

**Comment by CodingCat** [comment] 2016-03-09 11:14
I think we can close this one?

**Comment by ypopkov** [comment] 2016-03-09 13:19
yes, thanks for you help! Switching to ```localhost``` for rabit solved the issue on local:

```
$ python dmlc-core/tracker/dmlc_tracker/tracker.py --num-workers 1
Traceback (most recent call last):
  File "dmlc-core/tracker/dmlc_tracker/tracker.py", line 474, in <module>
    main()
  File "dmlc-core/tracker/dmlc_tracker/tracker.py", line 469, in main
    start_rabit_tracker(args)
  File "dmlc-core/tracker/dmlc_tracker/tracker.py", line 431, in start_rabit_tracker
    rabit = RabitTracker(hostIP=get_host_ip(args.host_ip), nslave=args.num_workers)
  File "dmlc-core/tracker/dmlc_tracker/tracker.py", line 145, in __init__
    sock.bind((hostIP, port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 48] Address already in use
Exception AttributeError: "'RabitTracker' object has no attribute 'sock'" in <bound method RabitTracker.__del__ of <__main__.RabitTracker object at 0x10afe1dd0>> ignored
$ python dmlc-core/tracker/dmlc_tracker/tracker.py --num-workers 1 --host-ip localhost
2016-03-09 08:17:02,768 INFO start listen on localhost:9091
DMLC_TRACKER_ENV_START
DMLC_TRACKER_URI=localhost
DMLC_NUM_SERVER=0
DMLC_TRACKER_PORT=9091
DMLC_NUM_WORKER=1
DMLC_TRACKER_ENV_END
```

**Comment by ypopkov** [comment] 2016-03-09 14:58
Actually, a quick unrelated question for you guys: is it possible to score ```ml.dmlc.xgboost4j.scala.spark.XGBoostModel``` using test data as ```RDD[LabeledPoint]```? I only see ```predict(testSet: Vector]``` and ```predict(testSet: DMatrix)``` methods in that class..

**Comment by CodingCat** [comment] 2016-03-09 15:32
Hi, @ypopkov , thanks for asking 

We currently provide predict(testSet:RDD[Vector]) for batch prediction to 

* keep consistent with mllib's API (as it is xgboost4j-`spark`)

* avoid complexity to deal with JVM's type erasure in the early version of xgboost4j

If we see great demanding for such an API, we may add it later....

**Comment by ypopkov** [comment] 2016-03-09 15:35
that works, thanks!

**Comment by tqchen** [comment] 2016-03-09 17:53
@ypopkov  Since rabit is used without localhost argument in the JVM and the default code does not work in your machine. It would be great if you can find a way to fix the current tracker code to behave smartly in your case and help us to improve the tracker code 

Thanks!

**Comment by ypopkov** [comment] 2016-03-09 22:54
I will poke around but my c/c++ is a bit rusty..

**Comment by tqchen** [comment] 2016-03-09 23:21
It has nothing to do with c++ just the tracker.py in the tracker folder

**Comment by CodingCat** [comment] 2016-03-10 12:09
seems that we have located the problem in local rabit side, I will close this one

**Closed by CodingCat** 2016-03-10 12:09 UTC

**Comment by Earthson** [comment] 2016-07-15 06:22
I have a similar problem. here is the log:

```
WhaleWeb: 2016-07-15 14:18:27,382 WARNING gethostbyname(socket.getfqdn()) failed... trying on hostname() 
WhaleWeb: Traceback (most recent call last): 
WhaleWeb:   File "/var/folders/0d/3mztrjr17md3g_gxqxkyj0680000gn/T/tracker6385215584284864342.py", line 475, in <module> 
WhaleWeb:     main() 
WhaleWeb:   File "/var/folders/0d/3mztrjr17md3g_gxqxkyj0680000gn/T/tracker6385215584284864342.py", line 470, in main 
WhaleWeb:     start_rabit_tracker(args) 
WhaleWeb:   File "/var/folders/0d/3mztrjr17md3g_gxqxkyj0680000gn/T/tracker6385215584284864342.py", line 432, in start_rabit_tracker 
WhaleWeb:     rabit = RabitTracker(hostIP=get_host_ip(args.host_ip), nslave=args.num_workers) 
WhaleWeb:   File "/var/folders/0d/3mztrjr17md3g_gxqxkyj0680000gn/T/tracker6385215584284864342.py", line 396, in get_host_ip 
WhaleWeb:     s.connect(('10.255.255.255', 0)) 
WhaleWeb: OSError: [Errno 49] Can't assign requested address 
WhaleWeb: Tracker Process ends with exit code 1 
WhaleWeb: Tracker Process ends with exit code 1 
WhaleWeb: Rabit returns with exit code 1 
```
