### ISSUE TITLE
Error when using client for DaskXGBClassifier

### ISSUE THREAD

**Issue by mariaangelesjs** [dmlc/xgboost#7546] opened 2022-01-09 15:05 UTC
Hi,
I've ran into a problem when I was trying to use XGBClassifier for dask within a Docker image:
Using:
```
`client = Client(n_workers=4, threads_per_worker=1, processes=False,
                memory_limit='16GB', scheduler_port=0,
                silence_logs=False, diagnostics_port=0)`
And after fitting with:
`model.fit(X_t, y_t, eval_set=(X_e, y_e))`
I get:
` model.fit(
  File "/usr/local/lib/python3.8/dist-packages/xgboost/dask.py", line 1817, in fit
    return self._client_sync(self._fit_async, **args)
  File "/usr/local/lib/python3.8/dist-packages/xgboost/dask.py", line 1617, in _client_sync
    with distributed.worker_client() as client:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/dist-packages/distributed/worker_client.py", line 55, in worker_client
    duration = time() - thread_state.start_time
AttributeError: '_thread._local' object has no attribute 'start_time'
distributed.worker - INFO - Stopping worker at inproc://172.17.0.2/1/5
distributed.worker - INFO - Stopping worker at inproc://172.17.0.2/1/4
distributed.worker - INFO - Stopping worker at inproc://172.17.0.2/1/6
distributed.worker - INFO - Stopping worker at inproc://172.17.0.2/1/7
distributed.scheduler - INFO - Remove worker <WorkerState 'inproc://172.17.0.2/1/5', name: 0, status: closing, memory: 0, processing: 0>
distributed.core - INFO - Removing comms to inproc://172.17.0.2/1/5
distributed.scheduler - INFO - Remove worker <WorkerState 'inproc://172.17.0.2/1/4', name: 1, status: closing, memory: 0, processing: 0>
distributed.core - INFO - Removing comms to inproc://172.17.0.2/1/4
distributed.scheduler - INFO - Remove worker <WorkerState 'inproc://172.17.0.2/1/6', name: 2, status: closing, memory: 0, processing: 0>
distributed.core - INFO - Removing comms to inproc://172.17.0.2/1/6
distributed.scheduler - INFO - Remove worker <WorkerState 'inproc://172.17.0.2/1/7', name: 3, status: closing, memory: 0, processing: 0>
distributed.core - INFO - Removing comms to inproc://172.17.0.2/1/7
distributed.scheduler - INFO - Lost all workers
distributed.scheduler - INFO - Scheduler closing...
distributed.scheduler - INFO - Scheduler closing all comms`
```

**Comment by trivialfis** [comment] 2022-01-09 16:22
Hi, could you please open an issue in https://github.com/dask/distributed and provide a reproducible example?  The error seems to be coming from dask.

**Comment by trivialfis** [comment] 2022-01-10 17:53
Thanks for opening an issue on distributed.  Will close this one now.

BTW, I think it's best if you can have a reproducible example that others can run on their own machines.  ;-)

**Closed by trivialfis** 2022-01-10 17:53 UTC
Labels: status: need update
