### ISSUE TITLE
 Socket Connect Error:Connection refused

### ISSUE THREAD

**Issue by kitty-eu-org** [dmlc/xgboost#7484] opened 2021-11-25 05:00 UTC
### error
`When I was using spark xgboost, an error occurred：
  retry connect to ip(retry time 1): [ip]
  retry connect to ip(retry time 1): [ip]
  retry connect to ip(retry time 1): [ip]
  retry connect to ip(retry time 1): [ip]
  retry connect to ip(retry time 1): [ip]
  retry connect to ip(retry time 1): [ip]
  retry connect to ip(retry time 1): [ip]
  retry connect to ip(retry time 1): [ip]
  retry connect to ip(retry time 1): [ip]
  retry connect to ip(retry time 1): [ip]
  retry connect to ip(retry time 2): [ip]
  retry connect to ip(retry time 2): [ip]
  retry connect to ip(retry time 2): [ip]
  retry connect to ip(retry time 2): [ip]
  retry connect to ip(retry time 2): [ip]
  retry connect to ip(retry time 2): [ip]
  retry connect to ip(retry time 2): [ip]
  retry connect to ip(retry time 2): [ip]
  retry connect to ip(retry time 2): [ip]
  retry connect to ip(retry time 2): [ip]
  retry connect to ip(retry time 3): [ip]
  retry connect to ip(retry time 3): [ip]
  retry connect to ip(retry time 3): [ip]
  retry connect to ip(retry time 3): [ip]
  retry connect to ip(retry time 3): [ip]
  retry connect to ip(retry time 3): [ip]
  retry connect to ip(retry time 3): [ip]
  retry connect to ip(retry time 3): [ip]
  retry connect to ip(retry time 3): [ip]
  retry connect to ip(retry time 3): [ip]
  retry connect to ip(retry time 4): [ip]
  retry connect to ip(retry time 4): [ip]
  retry connect to ip(retry time 4): [ip]
  retry connect to ip(retry time 4): [ip]
  retry connect to ip(retry time 4): [ip]
  retry connect to ip(retry time 4): [ip]
  retry connect to ip(retry time 4): [ip]
  retry connect to ip(retry time 4): [ip]
  retry connect to ip(retry time 4): [ip]
  retry connect to ip(retry time 4): [ip]
  connect to (failed): [ip]
  connect to (failed): [ip]
  Socket Connect Error:Connection refused
  Socket Connect Error:Connection refused`
### env
- ubuntu
- spark2.3.1
- scala2.11
- xgboost realease0.9.0
- Firewall off
- port 9091 is not occupied
I found a solution to it, can I mention a pr ? I think this is a bug, because even tasks that are already training are still affected by this error

**Comment by trivialfis** [comment] 2021-11-27 11:31
The tracker was down for some reason.  Please upgrade to latest xgboost and open a new issue if the problem persists, preferably with a reproducible example

**Comment by hezhaozhao-git** [comment] 2021-11-27 11:49
The latest version of xgboost will still have the same problem. Because of tracker.py, it is very simple to reproduce it. You only need to turn on the tracker service, and then use the telnet ip port, and enter the request to reproduce it. This is not essentially It's a bug, but the prompt information is really not friendly. In addition, the task being trained relies on tracker communication. If someone randomly sends a tacp request to the tracker port of the cluster machine, the ongoing training task will be terminated. I think this is undesirable and uncomfortable. I encountered this problem when using xgboost-spark. It was really distressing. In the end, I had to read most of the source code to solve this problem. I have seen similar questions on github and stackoverflow, but no one has given a solution

**Comment by hezhaozhao-git** [comment] 2021-11-27 11:51
@trivialfis hello,first trunk your reply， the latest version of xgboost will still have the same problem. Because of tracker.py, it is very simple to reproduce it. You only need to turn on the tracker service, and then use the telnet ip port, and enter the request to reproduce it. This is not essentially It's a bug, but the prompt information is really not friendly. In addition, the task being trained relies on tracker communication. If someone randomly sends a tacp request to the tracker port of the cluster machine, the ongoing training task will be terminated. I think this is undesirable and uncomfortable. I encountered this problem when using xgboost-spark. It was really distressing. In the end, I had to read most of the source code to solve this problem. I have seen similar questions on github and stackoverflow, but no one has given a solution

**Comment by hezhaozhao-git** [comment] 2021-12-02 10:05
@trivialfis I made some changes to the fock code, and added a friendly reminder that the tracker process has died and possible problem reminders. I hope you can consider my ideas, then I would be very grateful:
1. The [tacker.py](https://github.com/hezhaozhao-git/dmlc-core/blob/main/tracker/dmlc_tracker/tracker.py) modified by the [dmlc-core](https://github.com/hezhaozhao-git/dmlc-core) project fixes the tracker process exit problem caused by other programs accessing the port occupied by the tracker, and changes it to a more friendly prompt, allowing users to better troubleshoot.
2. [xgboost](https://github.com/dmlc/xgboost) has changed [RabitTracker.java](https://github.com/hezhaozhao-git/xgboost/blob/master/jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/RabitTracker.java) . I think that once the tracker server process dies, the entire java program should also die, because all subsequent calculations depend on the tacker process.

**Comment by trivialfis** [comment] 2021-12-02 14:31
Thanks for the detailed suggtestions.

@wbo4958 Could you please help take a look into this?

**Comment by wbo4958** [comment] 2021-12-03 03:43
@hezhaozhao-git Could you put up a PR for you fix?

**Comment by hezhaozhao-git** [comment] 2021-12-03 04:10
@wbo4958 Thank you for your reply, I have created pr and look forward to merging.

**Comment by hezhaozhao-git** [comment] 2021-12-03 04:11
> @hezhaozhao-git Could you put up a PR for you fix?

@wbo4958 Thank you for your reply, I have created pr and look forward to merging.

**Comment by trivialfis** [comment] 2024-08-16 11:56
Closing as the python tracker was removed in 2.1.

**Closed by trivialfis** 2024-08-16 11:56 UTC
Labels: feature-request
