### ISSUE TITLE
Parallelization issue in xgboost.cv with eval_metric='auc'

### ISSUE THREAD

**Issue by quadrakadabrasim** [dmlc/xgboost#6483] opened 2020-12-09 15:12 UTC
Hi there, I recently ran into an unexpected problem after upgrading from xgboost version 1.0.0 to 1.2.1.

When running the following code in a clean environment (Python 3.7.9) with only scikit-learn (0.23.2) and xgboost (1.0.0) installed, everything is just fine. However, using the same code with xgboost (1.2.1) the runtime increases by a factor of ~30.

This is only the case when eval_metric='auc'. If the default eval_metric is used, the runtime for both versions is approximately equal.
It appears to be a parallelization problem, as setting nthread=1 results in approximately the same runtime for both xgboost versions, too.
To sum up, just with the combination of eval_metric='auc', nthread=6, and xgboost version 1.2.1, the code becomes really slow.

```
import xgboost as xgb
from sklearn.datasets import load_breast_cancer

X, y = load_breast_cancer(return_X_y=True)

params = dict(
    booster='gbtree',
    objective='binary:logistic',
    eval_metric='auc',         # if this is commented out, parallelization works fine for both versions
    nthread=6,                 # if this is set to 1, runtime is approximately the same for both versions
    tree_method='hist',
)

dmatrix = xgb.DMatrix(X, y)

cv_results = xgb.cv(params=params,
                    dtrain=dmatrix,
                    early_stopping_rounds=20,
                    num_boost_round=1000)
```

Has somebody any idea why this happens?

**Comment by trivialfis** [comment] 2021-01-04 17:46
Is there any reason for closing?

**Comment by trivialfis** [comment] 2021-03-30 20:38
Looked into this, seems we need to balance the threads across folds.

**Comment by trivialfis** [comment] 2021-10-18 11:54
AUC for CPU binary classification is single-threaded.  Tested with larger dataset and couldn't reproduce the issue in latest release.

**Closed by trivialfis** 2021-10-18 11:54 UTC
