### ISSUE TITLE
Loading XGB models from absolute paths fails inside docker containers

### ISSUE THREAD

**Issue by ketronium** [dmlc/xgboost#5645] opened 2020-05-07 21:54 UTC
I can successfully load a previously trained model inside a Nvidia docker container as:
```python
bst = xgb.Booster()
bst.load_model('relative/path/pre_trained.model')
```
but when I try and load from absolute path as
```python
bst.load_model('/absolute/path/pre_trained.model')
```
I get the following error:
```python
XGBoostError: [20:44:39] /workspace/dmlc-core/src/io/local_filesys.cc:209: Check failed: allow_null:  LocalFileSystem::Open "pre_trained.model": No such file or directory
Stack trace:
  [bt] (0) /usr/local/lib/python3.6/dist-packages/xgboost/./lib/libxgboost.so(dmlc::io::LocalFileSystem::Open(dmlc::io::URI const&, char const*, bool)+0x506) [0x7fd3cc2639d6]
  [bt] (1) /usr/local/lib/python3.6/dist-packages/xgboost/./lib/libxgboost.so(dmlc::Stream::Create(char const*, char const*, bool)+0x39) [0x7fd3cc23aed9]
  [bt] (2) /usr/local/lib/python3.6/dist-packages/xgboost/./lib/libxgboost.so(XGBoosterLoadModel+0x8a3) [0x7fd3cbf0eb03]
  [bt] (3) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fd3e95f4dae]
  [bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7fd3e95f471f]
  [bt] (5) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2b4) [0x7fd4080845c4]
  [bt] (6) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x11c33) [0x7fd408084c33]
  [bt] (7) /usr/bin/python3(_PyObject_FastCallKeywords+0x19c) [0x5a9cbc]
  [bt] (8) /usr/bin/python3() [0x50a5c3]
```
I'm running `xgboost==1.0.2` and `scikit-learn==0.22.2.post1`.
 
Dockerfile in question:
```
FROM nvidia/cuda:10.0-base-ubuntu18.04

ENV NCCL_VERSION=2.4.2-1+cuda10.0
ENV CUDNN_VERSION=7.4.2.24-1+cuda10.0  

RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        cuda-command-line-tools-10-0 \
        cuda-cublas-10-0 \
        cuda-cufft-10-0 \
        cuda-curand-10-0 \
        cuda-cusolver-10-0 \
        cuda-cusparse-10-0 \
        libcudnn7=${CUDNN_VERSION} \
        libnccl2=${NCCL_VERSION} \
        libgomp1 \
        curl

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
    ca-certificates \
    # Libs required by opencv and other pip deps.
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    curl \
    gcc \
    build-essential \
    git \
    unzip \
    protobuf-compiler

RUN apt-get update \
    && apt-get install -y tar git curl nano wget dialog net-tools build-essential \
    && apt-get install --no-install-recommends -y -q python3 python3-pip python3-dev \
    && apt-get install -y libxml2-dev libxslt-dev python-dev zlib1g-dev

RUN pip3 install -U pip
RUN pip install --upgrade setuptools wheel
RUN pip install opencv-python fonts ipdb datetime imageio \
    boto3 xgboost pandas pyaml font-source-sans-pro scikit-image numba \
    scikit-learn filterpy s3fs pyarrow
```

**Comment by hcho3** [comment] 2020-05-10 00:19
@ketronium I just tried your Docker image and could not reproduce the issue. I ran the following Python script inside the Docker image:
```python
import xgboost
from sklearn.datasets import load_wine

dtrain = xgboost.DMatrix(X, label=y)
params = {'objective': 'multi:softprob', 'num_class':3}
bst = xgboost.train(params, dtrain, 10, [(dtrain, 'train')])
bst.save_model('/root/my.model')

bst2 = xgboost.Booster()
bst2.load_model('/root/my.model')
```

Can you double-check if the path you used was valid?

**Comment by hcho3** [comment] 2020-05-20 04:14
Closing for now. Feel free to re-open if the problem persists.

**Closed by hcho3** 2020-05-20 04:14 UTC
Labels: status: need update, type: bug
