### ISSUE TITLE
Support GPU arrays as input to inplace_predict when using gpu_predictor

### ISSUE THREAD

**Issue by beckernick** [dmlc/xgboost#6958] opened 2021-05-12 16:54 UTC
I'd like to use the `gpu_predictor` to use the GPU for predicting. My current understanding is that using `predict` on a DMatrix will return the result in CPU memory, causing a potentially unnecessary device to host transfer. `inplace_predict` can accept a numpy array as input when using the CPU predictor, but cannot accept either a CPU or GPU array as input when using the gpu_predictor.

```python
import xgboost as xgb
import cupy as cp
​
X = cp.arange(100).reshape(50, 2)
y = cp.arange(50)
​
dmat = xgb.DMatrix(X, y)
bst = xgb.train({"tree_method": "gpu_hist"}, dmat, 100)
bst.set_param({'predictor': 'gpu_predictor'})
type(bst.predict(dmat)) # numpy array
bst.inplace_predict(X)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-bc4e13033d42> in <module>
      9 bst.set_param({'predictor': 'gpu_predictor'})
     10 type(bst.predict(dmat))
---> 11 bst.inplace_predict(X)

/raid/nicholasb/miniconda3/envs/rapids-0.20/lib/python3.8/site-packages/xgboost/core.py in inplace_predict(self, data, iteration_range, predict_type, missing, validate_features, base_margin, strict_shape)
   1909             return _prediction_output(shape, dims, preds, True)
   1910 
-> 1911         raise TypeError(
   1912             "Data type:" + str(type(data)) + " not supported by inplace prediction."
   1913         )

TypeError: Data type:<class 'cupy._core.core.ndarray'> not supported by inplace prediction.
```

```
conda list | grep "xgboost\|cupy\|numpy"
cupy                      9.0.0            py38hc350bd8_1    conda-forge
libxgboost                1.4.0dev.rapidsai0.20      cuda11.0_0    rapidsai-nightly
numpy                     1.20.2           py38h9894fe3_0    conda-forge
py-xgboost                1.4.0dev.rapidsai0.20  cuda11.0py38_0    rapidsai-nightly
rapids-xgboost            0.20.0a210507   cuda11.0_py38_g24174d4_329    rapidsai-nightly
xgboost                   1.4.0dev.rapidsai0.20  cuda11.0py38_0    rapidsai-nightly
```

**Comment by hcho3** [comment] 2021-05-12 20:33
@beckernick Failure is not expected, since we have code specifically to handle cuPy arrays in `inplace_predict()`:
https://github.com/dmlc/xgboost/blob/2a9979e256bbead2f364ac8698a890ba9a1e004a/python-package/xgboost/core.py#L1945-L1966

We will investigate.

**Comment by beckernick** [comment] 2021-05-12 20:52
Thanks Philip! I'm happy to help triage as well

**Comment by trivialfis** [comment] 2021-05-13 04:33
It's fixed in latest 1.4 branch.  This is caused by updated cupy.

**Closed by trivialfis** 2021-05-13 04:33 UTC

**Comment by hcho3** [comment] 2021-05-13 05:13
@trivialfis Ah didn't notice it was a new addition after the 1.4.0 release. So cuPy 9.0.0 isn't supported by XGBoost 1.4.0 (+ cuML 0.19)?

**Comment by trivialfis** [comment] 2021-05-13 08:41
No.  But 1.4.2 should be fine.

**Comment by beckernick** [comment] 2021-05-13 13:17
Perfect, thanks all!
