### ISSUE TITLE
Categorical CUDA fails on a data validation check if there's a float column that contains all NAs

### ISSUE THREAD

**Issue by wwang-walleye** [dmlc/xgboost#9408] opened 2023-07-21 20:25 UTC
Hi, I found a bug with the categorical max value check if a float column contains all NAs. Code to reproduce below:

```

params <- list(
    tree_method="hist",
    device="cuda",
    eta=0.01,
    max_cat_to_onehot=1,
    max_cat_threshold=5
)

n <- 1e4
k <- 10
j <- 1
X <- cbind(
    matrix(rnorm(k * n), ncol=k),
    NA_real_ * matrix(rnorm(j * n), ncol=j),
    round(30*runif(n))
)

dtype <- c(rep("q", j+k), "c")
y <- rnorm(n)
wt <- runif(n)
dmat <- xgb.DMatrix(X, label=y, weight=wt, feature_type=dtype)
bst <- xgb.train(params, dmat, nround=10, watchlist=list(train=dmat), verbose=TRUE, print_every_n=1)
```

The error message is:

```
Error in xgb.iter.update(bst$handle, dtrain, iteration - 1, obj) : 
  [16:23:59] ../src/tree/updater_gpu_hist.cu:800: Exception in gpu_hist: [16:23:59] ../src/common/categorical.h:82: Check failed: max_cat + 1 >= n_categories (1 vs. 31) : Maximum cateogry should not be lesser than the total number of categories.
```

This is straightforward enough to work around, obviously, but worth flagging in case there's other errors. This was on the nightly 2.0 release. Thanks!

**Comment by trivialfis** [comment] 2023-08-08 08:21
We don't have full support for categorical feature in R yet. The issue is related to data format. We should natively support categorical data in R, which can store meta information like number of categories.

**Comment by wwang-walleye** [comment] 2023-08-08 22:49
Thanks, agreed that having something built in to store and sync  the factor to ordinal conversation inside dmatrix would be really valuable!

**Comment by trivialfis** [comment] 2023-08-11 10:10
Closing in favor of https://github.com/dmlc/xgboost/issues/7899 . For now, please use the Python binding for categorical features.

**Closed by trivialfis** 2023-08-11 10:10 UTC
Labels: type: bug
