### ISSUE TITLE
very low GPU usage when gpu model predicts

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#6405] opened 2020-11-19 01:22 UTC
I've been noticing that fit on bigger data is nice and quick and uses lots of GPU, but the predict does not.  This is true for dask and non-dask models.

```python
import pandas as pd
import dask.dataframe as dd
import xgboost as xgb
from dask_cuda import LocalCUDACluster


def main1(X, y):
    from dask.distributed import Client
    with LocalCUDACluster() as cluster:
        with Client(cluster) as client:
            params = {
                'tree_method': 'gpu_hist',
                'n_estimators': 2,
                'objective': 'binary:logistic'
            }

            model = xgb.dask.DaskXGBClassifier(**params)

            chunksize = 50000
            dX = dd.from_pandas(X, chunksize=chunksize)
            dy = dd.from_pandas(y, chunksize=chunksize)

            print("Done getting data into dask")
            model.fit(dX, dy)
            print("Done with fit")
            dX_inflated = dd.concat([dX for i in range(0, 10)])
            preds = model.predict(dX_inflated)
            print("Done with predict")
            print(preds[0].compute())

            client.cancel(dX)
            client.cancel(dy)
            print("Done with del")


def main2(X, y):
    params = {
        'tree_method': 'gpu_hist',
        'n_estimators': 2,
        'objective': 'binary:logistic',
        'predictor': 'gpu_predictor',  # doesn't matter
    }

    model = xgb.XGBClassifier(**params)

    model.fit(X, y)
    print("Done with fit")
    X_inflated = pd.concat([X for i in range(0, 10)])
    preds = model.predict(X_inflated)
    print("Done with predict")
    print(preds[0])


if __name__ == '__main__':
    colnames = ['label'] + ['feature-%02d' % i for i in range(1, 29)]
    df = pd.read_csv('/home/jon/Downloads/HIGGS5M.csv', names=colnames)

    y = df['label']
    X = df[df.columns.difference(['label'])]
    X = X.astype(np.float32)
    print('X.shape', X.shape)
    print('X.dtypes', X.dtypes)

    main2(X, y)
    # main1(X, y)

```

Based upon a script @teju85 wrote (but just using 5M of Higgs), no loop (no need here), and inflate the predicted X so can easily see if using GPUs.

Then one can run `watch -n 0.1 nvidia-smi` in some terminal.  One can easily see the blip of the short fit (only 2 trees).  If one makes it more trees, the usage is clear.

However, during predict, there is no usage at all.  Maybe there is like 1-2% usage, I cannot tell for sure.

I'm pretty sure predict uses some GPU, because main2() runs out of memory for duplication of 10X:

```
(base) jon@pseudotensor:~/h2oai.fullcondatest$ python checkdaskpredict.py 
X.shape (5000000, 28)
Done with fit
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: out of memory
Aborted (core dumped)
```

Is this slow GPU predict normal?  I especially notice for bigger data like airlines (117M x 14 after dropping some leaky columns), even basic parameters like 50-200 trees, the predict always takes twice as long as fit in dask fits.  But problem seems to be low-0 GPU usage for non-dask too.

In past, I think gpu_predictor had been improved to be quite fast compared to cpu_predictor, but it seems no longer true.

So 2 issues:

1) Why is GPU prediction so slow and using so little GPU?  Are no cores used and so usage looks low?  But why is fit so much faster than predict always?  At least 2X faster for fit than predict.  That makes no sense to me.

2) Why GPU OOM for predict when data should fit and model is small?  Here above 5M (rows) x 28 (cols) x 10 (dups) x 4 (float32) = 5GB.  The GPU has 7GB at time.  Even if doesn't fit, why does predict try to fill GPU up?  xgboost should batch the predictions to avoid GPU OOM.

**Comment by teju85** [comment] 2020-11-19 02:09
Disclaimer: not necessarily a direct answer to your questions and also probably a shameless plug!

Have you tried using [`cuml.ForestInference`](https://docs.rapids.ai/api/cuml/stable/api.html?highlight=fil#forest-inferencing)? Atleast as of cuML v0.16, it supports inferring on xgboost models too.

**Comment by hcho3** [comment] 2020-11-19 02:13
+1 to cuML FIL. It's super well optimized for batch prediction.

As for the original question: the primary goal of `gpu_predictor` in XGBoost is to keep the data on the GPU memory, so that we don't have to move data across the PCIe channel when training with `gpu_hist`. Efficiency of `gpu_predictor` may have some room for improvement.

**Comment by pseudotensor** [comment] 2020-11-19 02:16
> Disclaimer: not necessarily a direct answer to your questions and also probably a shameless plug!
> 
> Have you tried using [`cuml.ForestInference`](https://docs.rapids.ai/api/cuml/stable/api.html?highlight=fil#forest-inferencing)? Atleast as of cuML v0.16, it supports inferring on xgboost models too.

Yes, I saw, it's good idea to try, thanks.

**Comment by trivialfis** [comment] 2020-11-19 04:06
Yeah FIL is more efficient than the predict function in xgboost.  But to answer the questions raised here:

> Why is GPU prediction so slow and using so little GPU? Are no cores used and so usage looks low?

Let me take a look.  Since you are running the skl interface, I suspect that's due to the overhead in:
- Construct a new DaskDMatrix.
- Iterate through each partition during prediction.

> Why GPU OOM for predict when data should fit and model is small? 

Might be due to the overhead in DMatrix.  That's where the inplace predict comes in.

> xgboost should batch the predictions to avoid GPU OOM.

Ideally xgboost should be able to batch everything from memory and disk and network.  We are not there yet.

**Comment by trivialfis** [comment] 2020-11-19 04:44
Duplicated with https://github.com/dmlc/xgboost/issues/5729 .

**Comment by pseudotensor** [comment] 2020-11-19 06:23
It's not a duplicate, it's slow without dask as well.  I gave repro for both cases, that's all.

**Comment by pseudotensor** [comment] 2020-11-19 06:34
Regarding dask, it's a bit confusing why I see things like:
```
2020-11-14 18:38:59,052 C: 12% D:2.9TB   M:91.1GB  NODE:SERVER      27053  DEBUG  | -------------- rabit say hello ------------------
2020-11-18 15:41:49,189 C:  9% D:68.6GB  M:105.2GB                  32601  INFO   | Training on tcp://172.16.2.210:38847
2020-11-18 15:41:49,194 C:  9% D:68.6GB  M:105.2GB                  32601  INFO   | Training on tcp://172.16.4.18:46187
2020-11-18 15:41:49,195 C:  9% D:68.6GB  M:105.2GB                  32601  INFO   | Training on tcp://172.16.2.210:45093
2020-11-18 15:41:49,196 C:  9% D:68.6GB  M:105.2GB                  32601  INFO   | Training on tcp://172.16.4.18:42895
2020-11-18 15:43:47,300 C: 10% D:68.6GB  M:106.0GB                  32601  INFO   | Predicting on 0
2020-11-18 15:45:23,176 C: 11% D:68.6GB  M:106.0GB                  32601  INFO   | Predicting on 1
2020-11-18 15:47:01,742 C: 11% D:68.6GB  M:106.1GB                  32601  INFO   | Predicting on 2
2020-11-18 15:48:23,561 C:  9% D:68.6GB  M:105.1GB                  32601  INFO   | Predicting on 3
2020-11-18 15:49:36,927 C:  8% D:68.6GB  M:105.2GB                  32601  INFO   | Get shape on 0
2020-11-18 15:49:36,932 C:  8% D:68.6GB  M:105.2GB                  32601  INFO   | Get shape on 1
2020-11-18 15:49:37,027 C:  8% D:68.6GB  M:105.2GB                  32601  INFO   | Get shape on 2
2020-11-18 15:49:37,028 C:  8% D:68.6GB  M:105.2GB                  32601  INFO   | Get shape on 3
2020-11-14 19:50:52,442 C: 18% D:2.9TB   M:91.0GB  NODE:SERVER      5896   DEBUG  | --------------- rabit say bye ------------------
```

It's odd first of all that it's printing out these things.  Also odd that it seems like it's going through serially over workers do do the predictions, unlike training.

**Comment by trivialfis** [comment] 2020-11-19 07:11
> It's odd first of all that it's printing out these things at INFO level (apart from rabit thing)

It's either debug or info.

> I'm guessing something is leading to the async to not be async.

That's possible.  Need deeper look.

**Comment by pseudotensor** [comment] 2020-11-19 08:20
On logger, I'm just saying should be LOGGER.debug for the "Predicting on" and "Get shape on".

But of course the serial behavior is more serious.

**Comment by trivialfis** [comment] 2020-11-19 22:04
For single node case, the difference seems pronounced on master branch:

```
GPU Predict::Duration 0.556403398513794
GPU Inplace Predict::Duration 0.4413480758666992
CPU Predict::Duration 42.32740092277527
```
``` python
def main():
    # By default dask dataframe uses pandas as data handling backend
    dask_df = cudf.read_csv(fname, header=None, names=colnames)
    y = dask_df['label']
    X = dask_df[dask_df.columns.difference(['label'])]
    print('Creating DMatrix')
    dtrain = xgb.DMatrix(X, y)

    if os.path.exists('model.json'):
        booster = xgb.Booster(model_file='model.json')
    else:
        booster = xgb.train({'tree_method': 'gpu_hist'}, dtrain, num_boost_round=100)
        booster.save_model('model.json')

    predictions = booster.set_param({'predictor': 'gpu_predictor'})
    start = time()
    predictions = booster.predict(dtrain)
    end = time()
    print('GPU Predict::Duration', end - start)

    start = time()
    predictions = booster.inplace_predict(X)
    end = time()
    print('GPU Inplace Predict::Duration', end - start)

    booster = booster.copy()    # remove prediction cache
    start = time()
    predictions = booster.set_param({'predictor': 'cpu_predictor'})
    predictions = booster.predict(dtrain)
    end = time()

    print('CPU Predict::Duration', end - start)
    return booster, predictions
```

**Comment by pseudotensor** [comment] 2020-11-19 22:11
Ya, I wasn't arguing that CPU prediction is faster.  I wasn't ever comparing to CPU.  I was only comparing fit and predict regarding 2 things:

1) very low GPU usage during predict.  I'm guessing it's maybe just because cores are not used, and usage by NVML only tracks core usage not memory usage.

2) The time for fit and predict is comparable, but one would have thought fit should always take much longer one would think.    What is your fit time for the above?

**Comment by trivialfis** [comment] 2020-11-19 22:19
Made a small mistake.  Updated the numbers.

**Comment by pseudotensor** [comment] 2020-11-19 22:45
Ok, how about usage issues?  Do you see high usage?

At least if you are seeing train slower than predict, maybe master has improvements.

**Comment by RAMitchell** [comment] 2020-11-19 22:46
The sklearn interface would be expected to be much slower right? As we have to do format conversion.

**Comment by trivialfis** [comment] 2020-11-19 23:01
Since he's comparing train and predict.  If predict is indeed slower than train then something is wrong, specific interface should have nothing to do with it. (feel free to correct).

**Comment by trivialfis** [comment] 2020-11-20 06:31
Running on master branch, here are a few items:

Things that are expected:
- The "# doesn't matter` comment in the provided sample is caused by xgboost choosing `gpu_predictor` by default when using `gpu_hist` as training method.
- Using the `X_inflated` as input, the prediction time is about 2.5 seconds, while training is about 2.9 on rtx8000.  Please note that `X_inflated` is 10 times larger and there are only 2 trees.  So the performance seems reasonable to me.

Unexpected:
- I tried to compare the speed using scikit-learn interface, and found that the `predict` function doesn't use parameters set after `fit`.  Will submit a fix for this one.

**Comment by pseudotensor** [comment] 2020-11-20 10:17
Ok for me the "doesn't matter" didn't matter, higgs 5M case with example shown.

Yes, of course, I explained the X_inflated specifically and discussed this was just to show a long enough period that shows nvidia-smi that the GPU usage is 1%.

**Comment by pseudotensor** [comment] 2020-11-20 22:41
I think it's ok to close issue as-is, if you don't think the very low GPU usage is issue, I'm sure it's eating memory bandwidth that's just not shown.  And master times seem to show comparable fit/predict.

**Comment by trivialfis** [comment] 2020-11-24 00:55
Thanks for submitting the issue.

**Closed by trivialfis** 2020-11-24 00:55 UTC
