### ISSUE TITLE
Error: Invalid cast, from Null to Array, when opening a JSON model in Java 

### ISSUE THREAD

**Issue by datavisornicolacorradi** [dmlc/xgboost#6936] opened 2021-05-03 18:44 UTC
XGBoost version - 1.3.1
java version - 1.8.0_281

- train and save a model in python (v 1.3.3) as json file. The file is a valid json, and can be re-loaded in python. 
- load the model in java `XGBoost.loadModel(PATH);`
error:

```
Exception in thread "main" ml.dmlc.xgboost4j.java.XGBoostError: [08:42:54] /Users/nanzhu/code/xgboost/include/xgboost/json.h:65: Invalid cast, from Null to Array
Stack trace:
  [bt] (0) 1   libxgboost4j2452377860476975627.dyl 0x000000010e8db26e dmlc::LogMessageFatal::~LogMessageFatal() + 110
  [bt] (1) 2   libxgboost4j2452377860476975627.dyl 0x000000010e91ce10 xgboost::JsonArray const* xgboost::Cast<xgboost::JsonArray const, xgboost::Value>(xgboost::Value*) + 624
  [bt] (2) 3   libxgboost4j2452377860476975627.dyl 0x000000010e9d8026 xgboost::RegTree::LoadModel(xgboost::Json const&) + 1414
  [bt] (3) 4   libxgboost4j2452377860476975627.dyl 0x000000010e971fec xgboost::gbm::GBTreeModel::LoadModel(xgboost::Json const&) + 572
  [bt] (4) 5   libxgboost4j2452377860476975627.dyl 0x000000010e962e07 xgboost::gbm::GBTree::LoadModel(xgboost::Json const&) + 375
  [bt] (5) 6   libxgboost4j2452377860476975627.dyl 0x000000010e974352 xgboost::LearnerIO::LoadModel(xgboost::Json const&) + 1426
  [bt] (6) 7   libxgboost4j2452377860476975627.dyl 0x000000010e8e1d53 XGBoosterLoadModel + 1187
  [bt] (7) 8   libxgboost4j2452377860476975627.dyl 0x000000010e8d9620 Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterLoadModel + 48
  [bt] (8) 9   ???                                 0x0000000112c77667 0x0 + 4610029159


	at ml.dmlc.xgboost4j.java.XGBoostJNI.checkCall(XGBoostJNI.java:48)
	at ml.dmlc.xgboost4j.java.Booster.loadModel(Booster.java:66)
	at ml.dmlc.xgboost4j.java.XGBoost.loadModel(XGBoost.java:45)
	at com.datavisor.xgboostbenchmark.BenchmarkLoop.main(BenchmarkLoop.java:97)
```

**Comment by trivialfis** [comment] 2021-05-06 11:06
Could you please share how did you train the model?  I can't reproduce your error.

**Comment by trivialfis** [comment] 2021-09-14 04:46
Closing as stalled.

**Closed by trivialfis** 2021-09-14 04:46 UTC
Labels: status: need update
