### ISSUE TITLE
Spark Version

### ISSUE THREAD

**Issue by rkarimi** [dmlc/xgboost#2891] opened 2017-11-21 11:52 UTC
xgboost does not support spark 2.2, perhaps because of <spark.version>2.1.0</spark.version> in below:

https://github.com/dmlc/xgboost/blob/master/jvm-packages/pom.xml

It would be great to upgrade or make it flexible for compile.
Currently using xgboost based on Spark 2.1 results in trainRDD working, but trainDataFrame not working.

**Comment by superbobry** [comment] 2017-11-21 16:38
We are actually marking Spark as a provided dependency in the ongoing ->SBT migration. Probably, we should do it in `master` ahead of the merge.

**Comment by ebernhardson** [comment] 2017-12-05 18:35
I would prefer this to be flexible (2.1 or 2.2). The problem is spark 2.2 needs a newer jvm than spark 2.1 and that upgrade does not happen as fast as one might hope in many production clusters.

**Comment by spaszek** [comment] 2018-01-30 14:53
Is it possible to use XGBoost with Spark 2.2? Should I compile jars the usual way(with pom.xml set to proper Spark and S version - by proper I mean as if I was using Spark 2.1) and then just add jars to Livy/spark-shell?

**Comment by superbobry** [comment] 2018-02-04 21:55
For now, you'd have to bump the Spark version in the POM and the compile/assemble the JARs. After #3093 is merged, you could just assemble the JARs and run with any binary compatible Spark version, e.g. the currently unreleased 2.2.2.

**Closed** 2018-02-05 18:06 UTC
