### ISSUE TITLE
mac xgboost4j clang error

### ISSUE THREAD

**Issue by hzliang** [dmlc/xgboost#2616] opened 2017-08-19 04:23 UTC
I install xgboost on mac, python is ok, but when compile xgboost4j I get the follow error, anybody has good suggest?

[  1%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/config.cc.o
[  3%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/data.cc.o
In file included from /Users/huzuoliang/xgboost/dmlc-core/src/data.cc:12:
In file included from /Users/huzuoliang/xgboost/dmlc-core/src/data/disk_row_iter.h:19:
In file included from /Users/huzuoliang/xgboost/dmlc-core/src/data/./libsvm_parser.h:13:
In file included from /Users/huzuoliang/xgboost/dmlc-core/src/data/./text_parser.h:11:
/Users/huzuoliang/xgboost/dmlc-core/include/dmlc/omp.h:13:9: warning: Warning: OpenMP is not available, project will be compiled into single-thread code. Use OpenMP-enabled compiler to get benefit of multi-threading. [-W#pragma-messages]
#pragma message("Warning: OpenMP is not available, "                    \
        ^
1 warning generated.
[  5%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/io.cc.o
[  7%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/recordio.cc.o
[  9%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/io/line_split.cc.o
[ 11%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/io/recordio_split.cc.o
[ 12%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/io/input_split_base.cc.o
[ 14%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/io/local_filesys.cc.o
[ 16%] Linking CXX static library libdmlccore.a
[ 16%] Built target dmlccore
Scanning dependencies of target objxgboost
[ 18%] Building CXX object CMakeFiles/objxgboost.dir/src/c_api/c_api.cc.o
clang: error: no such file or directory: 'NOTFOUND'
make[2]: *** [CMakeFiles/objxgboost.dir/src/c_api/c_api.cc.o] Error 1
make[1]: *** [CMakeFiles/objxgboost.dir/all] Error 2
make: *** [all] Error 2
building Java wrapper
cd ..
mkdir -p build
cd build
cmake .. -DUSE_OPENMP:BOOL=OFF -DUSE_HDFS:BOOL=OFF -DUSE_AZURE:BOOL=OFF -DUSE_S3:BOOL=OFF -DPLUGIN_UPDATER_GPU:BOOL=OFF -DJVM_BINDINGS:BOOL=ON
cmake --build . --config Release
Traceback (most recent call last):
  File "create_jni.py", line 89, in <module>
    run("cmake --build . --config Release")
  File "create_jni.py", line 51, in run
    subprocess.check_call(command, shell=True, **kwargs)
  File "/Users/huzuoliang/app/Anaconda/anaconda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cmake --build . --config Release' returned non-zero exit status 2.
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:804)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:751)
        at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:313)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] xgboost-jvm ........................................ SUCCESS [  2.472 s]
[INFO] xgboost4j .......................................... FAILURE [ 15.745 s]
[INFO] xgboost4j-spark .................................... SKIPPED
[INFO] xgboost4j-flink .................................... SKIPPED
[INFO] xgboost4j-example .................................. SKIPPED

**Comment by superbobry** [comment] 2017-08-21 08:48
Duplicate of #2596.

**Comment by CodingCat** [comment] 2017-08-21 15:20
du

**Closed by CodingCat** 2017-08-21 15:20 UTC
