### ISSUE TITLE
[python-package] unable to assign DMatrix._feature_names via XGBClassifier.predict_proba

### ISSUE THREAD

**Issue by brentertainer** [dmlc/xgboost#4717] opened 2019-07-30 04:01 UTC
This issue was brought to my attention from [this question on StackOverflow](https://stackoverflow.com/questions/57262708/plot-partial-dependency-with-model-built-from-pandas-data-frame).

The gist of the problem is that an XGBClassifier can store and remember feature names when it is trained; however, `sklearn` does not supply such a mechanism from its [`plot_partial_dependence`](https://scikit-learn.org/stable/modules/generated/sklearn.inspection.plot_partial_dependence.html#sklearn.inspection.plot_partial_dependence) function. Feature names cannot be passed nor can feature validation be (organically) disabled, so `Booster._validate_features` automatically fails.

Here is a minimal reproducible example.
```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from xgboost import XGBClassifier
from sklearn.inspection import plot_partial_dependence

X_train = pd.DataFrame(data=np.random.normal(size=(100, 2)))
X_train.columns = ['a', 'b']
y_train = pd.Series(data=np.random.choice([0, 1], size=100))

clf = XGBClassifier()
clf.fit(X_train, y_train)

# get current keyword argument default values
#tmpdefaults = XGBClassifier.predict_proba.__defaults__
# change keyword argument default values
#XGBClassifier.predict_proba.__defaults__ = (None, False)

# plot (passing feature_names here has no effect)
plot_partial_dependence(estimator=clf, X=X_train, features=[0, 1], feature_names=X_train.columns.tolist())
plt.show()

# reset keyword argument default values to original
#XGBClassifier.predict_proba.__defaults = tmpdefaults
```

This results in the following error:
```
Traceback (most recent call last):
  File "tmp.py", line 19, in <module>
    plot_partial_dependence(estimator=clf, X=X_train, features=[0, 1], feature_names=X_train.columns.tolist())
  File "/home/brent/.local/lib/python3.7/site-packages/sklearn/inspection/partial_dependence.py", line 561, in plot_partial_dependence
    for fxs in features)
  File "/home/brent/.local/lib/python3.7/site-packages/joblib/parallel.py", line 921, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/brent/.local/lib/python3.7/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/brent/.local/lib/python3.7/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/brent/.local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/home/brent/.local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/home/brent/.local/lib/python3.7/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/brent/.local/lib/python3.7/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/brent/.local/lib/python3.7/site-packages/sklearn/inspection/partial_dependence.py", line 352, in partial_dependence
    response_method)
  File "/home/brent/.local/lib/python3.7/site-packages/sklearn/inspection/partial_dependence.py", line 152, in _partial_dependence_brute
    predictions = prediction_method(X_eval)
  File "/home/brent/.local/lib/python3.7/site-packages/xgboost/sklearn.py", line 834, in predict_proba
    validate_features=validate_features)
  File "/home/brent/.local/lib/python3.7/site-packages/xgboost/core.py", line 1284, in predict
    self._validate_features(data)
  File "/home/brent/.local/lib/python3.7/site-packages/xgboost/core.py", line 1691, in _validate_features
    data.feature_names))
ValueError: feature_names mismatch: ['a', 'b'] ['f0', 'f1']
expected a, b in input data
training data did not have the following fields: f0, f1
```

In the code example above, if the commented lines are allowed to run (thereby disabling feature validation), the plot is generated without issue but without certainty that the features passed to `plot_partial_dependence` line up with those used to train the model.

Alternatively, we could have set `X_train.columns = ['f0', 'f1']`, prior to training, but that is not generally a reasonable ask.

**Comment by trivialfis** [comment] 2020-04-15 21:01
It seems this is fixed by scikit learn.  I went all the way back to XGBoost 0.82 still couldn't reproduce the issue.

**Comment by trivialfis** [comment] 2020-04-15 21:02
Feel free to re-open if  I'm wrong.

**Closed by trivialfis** 2020-04-15 21:02 UTC
Labels: type: bug
