### ISSUE TITLE
!what(): xgboost/src/tree/updater_histmaker.cc:307: fv=3, hist.last=2 

### ISSUE THREAD

**Issue by dreamsuifeng** [dmlc/xgboost#3804] opened 2018-10-17 15:08 UTC
[--error info--]
xgboost/src/tree/updater_histmaker.cc:303: fv=3, hist.size=2
xgboost/src/tree/updater_histmaker.cc:305: hist[0]=0.999999
xgboost/src/tree/updater_histmaker.cc:305: hist[1]=2
terminate called after throwing an instance of 'dmlc::Error'
what(): xgboost/src/tree/updater_histmaker.cc:307: fv=3, hist.last=2 
[--environment--]
xgboost4j-spark 0.8
spark 2.2
scala
[--data--]
my data size is 3million *(300+)

my code get the error, it seems that errors happened when computing histogram.
I try to understand the fv param, but I can't.
I wan to know what conditions the code will exe.
are there my data some nan value or inf？
![image](https://user-images.githubusercontent.com/5406209/47096356-977ccf80-d261-11e8-8ec7-6ec38d081f6a.png)

**Comment by hcho3** [comment] 2018-10-17 17:04
@dreamsuifeng It looks like a bug I encountered in the past. Can you download sample4.libsvm.zip from https://github.com/dmlc/xgboost/issues/3402 and run it? See if you get the same error.

**Comment by dreamsuifeng** [comment] 2018-10-18 08:55
@hcho3 Thanks~. I think I met the same bug, the latest release 8.0 branch have fix the bug?
So, can I rebuild the xgboost4j-spark from latest release 8.0 branch  to resolve it?

**Comment by hcho3** [comment] 2018-10-18 13:17
Yes

**Comment by hcho3** [comment] 2018-10-22 23:49
Any updates on this?

**Comment by dreamsuifeng** [comment] 2018-10-25 08:14
> Any updates on this?
I have resolved this problem

**Comment by zhaokaihuang** [comment] 2019-01-19 11:10
> > Any updates on this?
> > I have resolved this problem

@dreamsuifeng @hcho3  Hi, could you help to share how to solve the problem? I'm already using xgboost4j-spark of version 0.8 and checking there is no NaN or inf in my data. I think I met the same error as following:
[06:28:02] /xgboost/src/tree/updater_histmaker.cc:305: hist[63]=inf
[06:28:02] /xgboost/src/tree/updater_histmaker.cc:305: hist[64]=inf
terminate called after throwing an instance of 'dmlc::Error'
  what():  [06:28:02] /xgboost/src/tree/updater_histmaker.cc:307: fv=inf, hist.last=inf

**Comment by zhaokaihuang** [comment] 2019-01-20 09:34
Hi @CodingCat, do you have any ideas to this problem. Many thanks to your help.

**Comment by trivialfis** [comment] 2019-02-16 15:26
@zhaokaihuang Could you make a reproducible example?

**Comment by hcho3** [comment] 2019-03-08 01:36
@zhaokaihuang Closing this issue for now. Feel free to try the latest version (0.82). If you experienceany bug, feel free to open a new issue. Thanks!

**Closed by hcho3** 2019-03-08 01:36 UTC
