### ISSUE TITLE
Incorrect way throw tree

### ISSUE THREAD

**Issue by softitova** [dmlc/xgboost#3536] opened 2018-07-31 05:25 UTC
* I have a model, with a first tree dump for one case 
```
161:[f48<0.0019642] yes=269,no=270,missing=270
								269:leaf=-0.0588805
								270:leaf=-0.120722
```

* I have feature f48 value ***0.00017065995780200002***
But I'm going into 270 leaf in the xgboost

> What can affect on this? (I have sorted sparse features in train and test data)

**Comment by hcho3** [comment] 2018-07-31 05:36
Closing this as duplicate of https://discuss.xgboost.ai/t/incorrect-way-throw-tree/110. Let's keep the issue tracker for bug reports.

**Closed by hcho3** 2018-07-31 05:36 UTC
