### ISSUE TITLE
Training gets stuck and dumping model crashes

### ISSUE THREAD

**Issue by yannclaes** [dmlc/xgboost#7534] opened 2021-12-23 10:02 UTC
Hello,

I am trying to train an XGBoostRegressor (using the sklearn wrappers) for a given problem, with a custom objective function. Training starts correctly as the log starts displaying information about the tree growing procedure. However, it gets stuck after a certain time (a certain number of rounds) and I am not able to figure out why.

To be clear here is an example of the log:

> [11:23:26] DEBUG: /private/var/folders/p7/5z1vzvf979z_4229133pyj800000gn/T/pip-install-5csor64l/xgboost_f54291a5282e44bda2bc887c27db68bb/build/temp.macosx-10.14.6-arm64-3.8/xgboost/src/gbm/gbtree.cc:155: Using tree method: 2
> 
> [11:23:26] INFO: /private/var/folders/p7/5z1vzvf979z_4229133pyj800000gn/T/pip-install-5csor64l/xgboost_f54291a5282e44bda2bc887c27db68bb/build/temp.macosx-10.14.6-arm64-3.8/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 0 extra nodes, 0 pruned nodes, max_depth=0
> 
> [11:24:36] INFO: /private/var/folders/p7/5z1vzvf979z_4229133pyj800000gn/T/pip-install-5csor64l/xgboost_f54291a5282e44bda2bc887c27db68bb/build/temp.macosx-10.14.6-arm64-3.8/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 0 extra nodes, 0 pruned nodes, max_depth=0
>
> ...
>
> [12:01:21] INFO: /private/var/folders/p7/5z1vzvf979z_4229133pyj800000gn/T/pip-install-5csor64l/xgboost_f54291a5282e44bda2bc887c27db68bb/build/temp.macosx-10.14.6-arm64-3.8/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 2 extra nodes, 0 pruned nodes, max_depth=1

and it gets stuck after this iteration. For debugging purpose, I have set max_depth=1, n_estimators=100, and have not set any value for n_jobs, as I thought it could be the cause of the problem. My dataset has 100k records of 18 features each, which does not appear dramatically large. I let it run for hours but training just doesn't want to finish, nothing else happens after the last line of the log, and my model is not saved. I executed the same code on a cluster and it did finish there, although it crashed for some unknown pickle reason.

To add something about the pickle error received on the cluster, it tells me
> _pickle.PicklingError: Can't pickle <function norm_objective_wrapper.<locals>.norm_objective at 0x14661a0ce950>: it's not found as __main__.norm_objective_wrapper.<locals>.norm_objective

when I try to joblib.dump() my model. I guess it can't have anything to do with multi-processing (as was the case for other people) since I'm not taking any advantage of parallelism (and basically using a single cpu for debugging purpose).

Any tip would be appreciated, thanks!

**Comment by trivialfis** [comment] 2021-12-24 00:18
Could you please share a reproducible example that I can run?

**Comment by yannclaes** [comment] 2021-12-24 13:52
I'm working on it! I've tried a very simple example with random tensors and only 10 estimators, which worked very well. I thus decided to move back to my working problem, and try with only 10 estimators, which also worked fine.

Then, I decided that it was time I moved back to the initial configuration (2 XGBRegressors with 100 estimators each), thinking that it would go fine. The first model finished training (and to save it, I decided to move to the best.save_model function, saving it as a .json, which also worked fine although it told me the objective was not saved; which I think is not a big deal) and the second one got stuck after 70 estimators, for a total of 2h10min, which starts to make me think the problem comes from my terminal..

I'll come back to you later today or tomorrow with a complete reproducible example, once I'm sure I indeed have a (clean) one. If it can be of any help, here are the versions of the libraries I'm relying on:
> torch: 1.10.0
> joblib: 1.1.0
> XGBoost: 1.5.1

Thanks for the quick follow-up, and happy holidays ;-)

**Comment by trivialfis** [comment] 2021-12-25 02:31
I tried to print the time in `norm_objective` using `time.time()`:

```
norm_objective begin: 1640399279.571754
norm_objective duration: 47.110312700271606
norm_objective begin: 1640399326.910346
norm_objective duration: 51.263638734817505
norm_objective begin: 1640399378.3853962
...
```

Could you please check your torch autograd script?  It seems the majority of the time is being spent in there.

**Comment by trivialfis** [comment] 2021-12-25 04:49
Other than the efficiency of the obj function, one cannot pickle a local function:
```
_pickle.PicklingError: Can't pickle <function norm_objective_wrapper.<locals>.norm_objective at 0x7ff41d9b0550>: it's not found as __main__.norm_objective_wrapper.<locals>.norm_objective
```

**Comment by yannclaes** [comment] 2021-12-26 17:10
> I tried to print the time in `norm_objective` using `time.time()`:
> 
> ```
> norm_objective begin: 1640399279.571754
> norm_objective duration: 47.110312700271606
> norm_objective begin: 1640399326.910346
> norm_objective duration: 51.263638734817505
> norm_objective begin: 1640399378.3853962
> ...
> ```
> 
> Could you please check your torch autograd script? It seems the majority of the time is being spent in there.

Not sure what you mean about checking my torch autograd script? I'm just calling ```torch.autograd.grad()```, which you can find [here](https://pytorch.org/docs/stable/_modules/torch/autograd.html#grad). I understand it might be an efficiency problem (maybe there's a cleaner way to proceed for hessian computation), but I don't see why it would eventually get stuck there.

Thanks for the pickle tip. I don't see how I could work around this issue by still using ```joblib.dump()```, as I don't see another way of writing my objective (except with global variables?)

**Comment by trivialfis** [comment] 2021-12-27 01:09
> Not sure what you mean about checking my torch autograd script? I'm just calling torch.autograd.grad(), 

I don't know where did it get stuck, as you see I can proceed the training until the pickle error.  So I suspect that it's the custom objective running for too long so it looks like being stuck.  Would you great if you can verify that by timing it.

> Thanks for the pickle tip. I don't see how I could work around this issue by still using

Use callable class, or simply save the state by yourself.  For the former, you can look up the `__call__` special method.  For the latter, you can use XGBRegressor.save_model in combination with your own script that saves the states.  We actually don't recommend the use of pickle since its format is not portable between XGBoost versions and Python versions.

**Comment by yannclaes** [comment] 2021-12-27 08:36
Thanks a lot! I'll work on those and come back to you with the (hopefully) final answer.

**Comment by trivialfis** [comment] 2022-02-20 19:00
Hi, any update?

**Comment by trivialfis** [comment] 2022-03-25 11:46
Closing as stalled.

**Closed by trivialfis** 2022-03-25 11:46 UTC
Labels: status: need update
