### ISSUE TITLE
[jvm-packages] XGBoostModel training failed 

### ISSUE THREAD

**Issue by chengaofeng1** [dmlc/xgboost#4440] opened 2019-05-05 11:34 UTC
I am able to run binary classification with xgboost4j-spark on small amount of data. Keeping everything the same, as I increase the data and columns, I get XGBoostModel training failed error. I'm looking for some help in figure out if i'm missing something or how can I debug this issue.

2019-05-05 19:30:10,778 WARN  storage.BlockManagerMasterEndpoint: No more replicas available for rdd_3709_0 !
2019-05-05 19:30:10,794 WARN  storage.BlockManagerMasterEndpoint: No more replicas available for rdd_3709_3 !
2019-05-05 19:30:10,796 WARN  storage.BlockManagerMasterEndpoint: No more replicas available for rdd_14_1 !
2019-05-05 19:30:10,798 WARN  storage.BlockManagerMasterEndpoint: No more replicas available for rdd_14_5 !
2019-05-05 19:30:10,800 WARN  storage.BlockManagerMasterEndpoint: No more replicas available for rdd_14_3 !
2019-05-05 19:30:10,802 WARN  storage.BlockManagerMasterEndpoint: No more replicas available for rdd_4209_3 !
2019-05-05 19:30:10,804 WARN  storage.BlockManagerMasterEndpoint: No more replicas available for rdd_4209_0 !
2019-05-05 19:30:10,806 WARN  storage.BlockManagerMasterEndpoint: No more replicas available for rdd_4236_3 !
2019-05-05 19:30:10,808 WARN  storage.BlockManagerMasterEndpoint: No more replicas available for rdd_3715_3 !
2019-05-05 19:30:10,810 WARN  storage.BlockManagerMasterEndpoint: No more replicas available for rdd_4236_0 !
2019-05-05 19:30:10,812 WARN  storage.BlockManagerMasterEndpoint: No more replicas available for rdd_3715_0 !
2019-05-05 19:30:10,814 WARN  storage.BlockManagerMasterEndpoint: No more replicas available for rdd_3646_5 !
2019-05-05 19:30:10,816 WARN  storage.BlockManagerMasterEndpoint: No more replicas available for rdd_3646_1 !
2019-05-05 19:30:10,818 WARN  storage.BlockManagerMasterEndpoint: No more replicas available for rdd_3646_3 !
2019-05-05 19:30:11,006 WARN  yarn.YarnAllocator: Container marked as failed: container_e18_1546851184537_22938_01_000002 on host: hslave5. Exit status: 134. Diagnostics: Exception from container-launch.
Container id: container_e18_1546851184537_22938_01_000002
Exit code: 134
Stack trace: ExitCodeException exitCode=134: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:604)
	at org.apache.hadoop.util.Shell.run(Shell.java:507)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:789)
	at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:399)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

Shell output: main : command provided 1
main : run as user is dingxiang
main : requested yarn user is dingxiang
Writing to tmp file /mydata_ext/cdh/data/yarn/nm/nmPrivate/application_1546851184537_22938/container_e18_1546851184537_22938_01_000002/container_e18_1546851184537_22938_01_000002.pid.tmp

Container exited with a non-zero exit code 134

2019-05-05 19:30:11,014 WARN  cluster.YarnSchedulerBackend$YarnSchedulerEndpoint: Container marked as failed: container_e18_1546851184537_22938_01_000002 on host: hslave5. Exit status: 134. Diagnostics: Exception from container-launch.
Container id: container_e18_1546851184537_22938_01_000002
Exit code: 134
Stack trace: ExitCodeException exitCode=134: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:604)
	at org.apache.hadoop.util.Shell.run(Shell.java:507)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:789)
	at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:399)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

Shell output: main : command provided 1
main : run as user is dingxiang
main : requested yarn user is dingxiang
Writing to tmp file /mydata_ext/cdh/data/yarn/nm/nmPrivate/application_1546851184537_22938/container_e18_1546851184537_22938_01_000002/container_e18_1546851184537_22938_01_000002.pid.tmp

Container exited with a non-zero exit code 134

2019-05-05 19:30:11,016 ERROR cluster.YarnClusterScheduler: Lost executor 1 on hslave5: Container marked as failed: container_e18_1546851184537_22938_01_000002 on host: hslave5. Exit status: 134. Diagnostics: Exception from container-launch.
Container id: container_e18_1546851184537_22938_01_000002
Exit code: 134
Stack trace: ExitCodeException exitCode=134: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:604)
	at org.apache.hadoop.util.Shell.run(Shell.java:507)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:789)
	at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:399)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

Shell output: main : command provided 1
main : run as user is dingxiang
main : requested yarn user is dingxiang
Writing to tmp file /mydata_ext/cdh/data/yarn/nm/nmPrivate/application_1546851184537_22938/container_e18_1546851184537_22938_01_000002/container_e18_1546851184537_22938_01_000002.pid.tmp

Container exited with a non-zero exit code 134

2019-05-05 19:30:11,023 WARN  scheduler.TaskSetManager: Lost task 0.0 in stage 2827.0 (TID 5752, hslave5, executor 1): ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason: Container marked as failed: container_e18_1546851184537_22938_01_000002 on host: hslave5. Exit status: 134. Diagnostics: Exception from container-launch.
Container id: container_e18_1546851184537_22938_01_000002
Exit code: 134
Stack trace: ExitCodeException exitCode=134: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:604)
	at org.apache.hadoop.util.Shell.run(Shell.java:507)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:789)
	at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:399)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

Shell output: main : command provided 1
main : run as user is dingxiang
main : requested yarn user is dingxiang
Writing to tmp file /mydata_ext/cdh/data/yarn/nm/nmPrivate/application_1546851184537_22938/container_e18_1546851184537_22938_01_000002/container_e18_1546851184537_22938_01_000002.pid.tmp

Container exited with a non-zero exit code 134

2019-05-05 19:30:11,030 ERROR util.Utils: uncaught error in thread SparkListenerBus, stopping SparkContext
java.lang.InterruptedException: ExecutorLost during XGBoost Training: ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason: Container marked as failed: container_e18_1546851184537_22938_01_000002 on host: hslave5. Exit status: 134. Diagnostics: Exception from container-launch.
Container id: container_e18_1546851184537_22938_01_000002
Exit code: 134
Stack trace: ExitCodeException exitCode=134: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:604)
	at org.apache.hadoop.util.Shell.run(Shell.java:507)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:789)
	at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:399)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

Shell output: main : command provided 1
main : run as user is dingxiang
main : requested yarn user is dingxiang
Writing to tmp file /mydata_ext/cdh/data/yarn/nm/nmPrivate/application_1546851184537_22938/container_e18_1546851184537_22938_01_000002/container_e18_1546851184537_22938_01_000002.pid.tmp

Container exited with a non-zero exit code 134

	at org.apache.spark.TaskFailedListener.onTaskEnd(SparkParallelismTracker.scala:116)
	at org.apache.spark.scheduler.SparkListenerBus$class.doPostEvent(SparkListenerBus.scala:45)
	at org.apache.spark.scheduler.LiveListenerBus.doPostEvent(LiveListenerBus.scala:36)
	at org.apache.spark.scheduler.LiveListenerBus.doPostEvent(LiveListenerBus.scala:36)
	at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:63)
	at org.apache.spark.scheduler.LiveListenerBus.postToAll(LiveListenerBus.scala:36)
	at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(LiveListenerBus.scala:94)
	at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(LiveListenerBus.scala:79)
	at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(LiveListenerBus.scala:79)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1.apply$mcV$sp(LiveListenerBus.scala:78)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1279)
	at org.apache.spark.scheduler.LiveListenerBus$$anon$1.run(LiveListenerBus.scala:77)
2019-05-05 19:30:11,047 ERROR util.Utils: throw uncaught fatal error in thread SparkListenerBus
java.lang.InterruptedException: ExecutorLost during XGBoost Training: ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason: Container marked as failed: container_e18_1546851184537_22938_01_000002 on host: hslave5. Exit status: 134. Diagnostics: Exception from container-launch.
Container id: container_e18_1546851184537_22938_01_000002
Exit code: 134
Stack trace: ExitCodeException exitCode=134: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:604)
	at org.apache.hadoop.util.Shell.run(Shell.java:507)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:789)
	at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:399)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

Shell output: main : command provided 1
main : run as user is dingxiang
main : requested yarn user is dingxiang
Writing to tmp file /mydata_ext/cdh/data/yarn/nm/nmPrivate/application_1546851184537_22938/container_e18_1546851184537_22938_01_000002/container_e18_1546851184537_22938_01_000002.pid.tmp

Container exited with a non-zero exit code 134

	at org.apache.spark.TaskFailedListener.onTaskEnd(SparkParallelismTracker.scala:116)
	at org.apache.spark.scheduler.SparkListenerBus$class.doPostEvent(SparkListenerBus.scala:45)
	at org.apache.spark.scheduler.LiveListenerBus.doPostEvent(LiveListenerBus.scala:36)
	at org.apache.spark.scheduler.LiveListenerBus.doPostEvent(LiveListenerBus.scala:36)
	at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:63)
	at org.apache.spark.scheduler.LiveListenerBus.postToAll(LiveListenerBus.scala:36)
	at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(LiveListenerBus.scala:94)
	at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(LiveListenerBus.scala:79)
	at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(LiveListenerBus.scala:79)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1.apply$mcV$sp(LiveListenerBus.scala:78)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1279)
	at org.apache.spark.scheduler.LiveListenerBus$$anon$1.run(LiveListenerBus.scala:77)
2019-05-05 19:30:11,144 ERROR java.RabitTracker: Uncaught exception thrown by worker:
org.apache.spark.SparkException: Job 984 cancelled because SparkContext was shut down
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$cleanUpAfterSchedulerStop$1.apply(DAGScheduler.scala:820)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$cleanUpAfterSchedulerStop$1.apply(DAGScheduler.scala:818)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
	at org.apache.spark.scheduler.DAGScheduler.cleanUpAfterSchedulerStop(DAGScheduler.scala:818)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onStop(DAGScheduler.scala:1750)
	at org.apache.spark.util.EventLoop.stop(EventLoop.scala:83)
	at org.apache.spark.scheduler.DAGScheduler.stop(DAGScheduler.scala:1669)
	at org.apache.spark.SparkContext$$anonfun$stop$8.apply$mcV$sp(SparkContext.scala:1928)
	at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1317)
	at org.apache.spark.SparkContext.stop(SparkContext.scala:1927)
	at org.apache.spark.SparkContext$$anon$3.run(SparkContext.scala:1872)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2029)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2050)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2069)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2094)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:926)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:924)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:924)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4$$anon$1.run(XGBoost.scala:232)
2019-05-05 19:30:16,162 INFO  spark.SparkTask: 9420:GBXM分类, 运行失败
2019-05-05 19:30:16,164 ERROR spark.SparkTask: Run spark all graph exception: 
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$postTrackerReturnProcessing(XGBoost.scala:282)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:239)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:221)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:220)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:204)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:59)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:123)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:87)
	at com.dx.aip.ailib.spark.SparkTask.runNode(SparkTask.java:270)
	at com.dx.aip.ailib.spark.SparkTask.downwardRun(SparkTask.java:155)
	at com.dx.aip.ailib.spark.SparkTask.downwardRun(SparkTask.java:176)
	at com.dx.aip.ailib.spark.SparkTask.downwardRun(SparkTask.java:176)
	at com.dx.aip.ailib.spark.SparkTask.downwardRun(SparkTask.java:176)
	at com.dx.aip.ailib.spark.SparkTask.run(SparkTask.java:143)
	at com.dx.aip.ailib.spark.SparkTask.main(SparkTask.java:388)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:635)

**Comment by chengaofeng1** [comment] 2019-05-06 03:43
I have checked the spark ui and found the code that caused the error, 

![11_36_46__05_06_2019](https://user-images.githubusercontent.com/38199448/57205851-08b08400-6ff4-11e9-969d-2a957278b567.jpg)
![11_05_20__05_06_2019](https://user-images.githubusercontent.com/38199448/57205866-28e04300-6ff4-11e9-857c-c5a0c962a0b3.jpg)

but I still don't know how to  solve it, who can help me?

**Comment by CodingCat** [comment] 2019-05-06 16:18
can you upload the logs from the failed executors?

**Comment by Neel28** [comment] 2019-05-24 21:45
Facing the same issue. Cannot find any failed executors from Spark UI. Any suggestion? Thanks!

**Comment by dengCunbin** [comment] 2019-05-27 08:51
Facing the same issue.Who can help me?

**Comment by dengCunbin** [comment] 2019-05-27 08:52
> I have checked the spark ui and found the code that caused the error,
> 
> ![11_36_46__05_06_2019](https://user-images.githubusercontent.com/38199448/57205851-08b08400-6ff4-11e9-969d-2a957278b567.jpg)
> ![11_05_20__05_06_2019](https://user-images.githubusercontent.com/38199448/57205866-28e04300-6ff4-11e9-857c-c5a0c962a0b3.jpg)
> 
> but I still don't know how to solve it, who can help me?

Have you solved it?

**Comment by CodingCat** [comment] 2019-08-04 21:16
these are only driver side logs, can you check what is happening in your executors?

**Comment by nkr-jgr** [comment] 2019-08-09 11:14
_I am getting following error log.... having the same issue.. while increasing the training data xgboost training fails.'_

19/08/09 11:06:47 ERROR Uncaught throwable from user code: ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$postTrackerReturnProcessing(XGBoost.scala:582)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$2.apply(XGBoost.scala:459)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$2.apply(XGBoost.scala:435)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:434)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:194)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:44)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:82)
	at org.apache.spark.ml.Pipeline$$anonfun$fit$2.apply(Pipeline.scala:153)
	at org.apache.spark.ml.Pipeline$$anonfun$fit$2.apply(Pipeline.scala:149)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableViewLike$Transformed$class.foreach(IterableViewLike.scala:44)
	at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.scala:37)
	at org.apache.spark.ml.Pipeline.fit(Pipeline.scala:149)
	at line2fe24e04182f485ebc05990925758f0c54.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-576475677673557:90)
	at line2fe24e04182f485ebc05990925758f0c54.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-576475677673557:202)
	at line2fe24e04182f485ebc05990925758f0c54.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-576475677673557:204)
	at line2fe24e04182f485ebc05990925758f0c54.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-576475677673557:206)
	at line2fe24e04182f485ebc05990925758f0c54.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-576475677673557:208)
	at line2fe24e04182f485ebc05990925758f0c54.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-576475677673557:210)
	at line2fe24e04182f485ebc05990925758f0c54.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-576475677673557:212)
	at line2fe24e04182f485ebc05990925758f0c54.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-576475677673557:214)
	at line2fe24e04182f485ebc05990925758f0c54.$read$$iw$$iw$$iw$$iw.<init>(command-576475677673557:216)
	at line2fe24e04182f485ebc05990925758f0c54.$read$$iw$$iw$$iw.<init>(command-576475677673557:218)
	at line2fe24e04182f485ebc05990925758f0c54.$read$$iw$$iw.<init>(command-576475677673557:220)
	at line2fe24e04182f485ebc05990925758f0c54.$read$$iw.<init>(command-576475677673557:222)
	at line2fe24e04182f485ebc05990925758f0c54.$read.<init>(command-576475677673557:224)
	at line2fe24e04182f485ebc05990925758f0c54.$read$.<init>(command-576475677673557:228)
	at line2fe24e04182f485ebc05990925758f0c54.$read$.<clinit>(command-576475677673557)
	at line2fe24e04182f485ebc05990925758f0c54.$eval$.$print$lzycompute(<notebook>:7)
	at line2fe24e04182f485ebc05990925758f0c54.$eval$.$print(<notebook>:6)
	at line2fe24e04182f485ebc05990925758f0c54.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:215)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply$mcV$sp(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:679)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:632)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:368)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:345)
	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:238)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:233)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:48)
	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:271)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:48)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:345)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at scala.util.Try$.apply(Try.scala:192)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:639)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:485)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:597)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:390)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:337)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:219)
	at java.lang.Thread.run(Thread.java:748)

**Comment by trivialfis** [comment] 2022-04-16 04:58
Closing due to stalled.  If the issue persists in the latest XGBoost please open a new issue with a reproducible example that we can help debug.

**Closed by trivialfis** 2022-04-16 04:58 UTC
