### ISSUE TITLE
[jvm-packages] xgboost4j-spark 0.82 stuck at foreachPartition at XGBoost.scala:397

### ISSUE THREAD

**Issue by laura779** [dmlc/xgboost#5013] opened 2019-11-05 11:43 UTC
I met this issue many times. it sometimes almost hang for more than 1 hour. 
 There are about 58061308 samples , and each sample has 60 feature columns.
 
spark conf：SPARK 2.2.1
master = yarn-cluster
driver-memory = 8G
executor-memory = 12G
executor-cores = 1
num-executors = 1000
spark.yarn.executor.memoryOverhead = 2048

and params of xgboostRegression are set as below:

 val xgbParam = Map(
      "num_round"->500,
      "eta" -> 0.1f,
      "missing" -> -999,
      "max_depth" -> 5,
      "objective" -> "rank:pairwise",
      "booster"->"gbtree",
      "minimize_evaluation_metrics" ->false,
      "num_workers"->200,
      "min_child_weight"->5,
      "silent"->1,
      "subsample" -> 0.8,
      "seed"->1l,
      "reg_alpha"->1,
      "reg_lambda"->1,
      "timeout_request_workers"->90000L)

but I got this:
<img width="1586" alt="DX-20191105@2x" src="https://user-images.githubusercontent.com/24602230/68205128-715cd580-0004-11ea-8277-c50b9c22aedc.png">
Thanks

**Comment by chenqin** [comment] 2019-11-06 05:37
Hi @laura779 can you help paste driver log. It's possible one of worker dead and cause entire job stuck. Can you try latest master and set "rabit_timeout" to 30 in your case.

![image](https://user-images.githubusercontent.com/1184534/68271038-467a7d80-0014-11ea-8143-d1bd111d13ee.png)

**Comment by laura779** [comment] 2019-11-06 13:35
thank you @chenqin , but my spark version is 2.2.0 and  for some reason I can't update. The latest master require higher version of spark. 
driver log is too long to paste, and i look the syslog, something like below:
<img width="1220" alt="2" src="https://user-images.githubusercontent.com/24602230/68302543-3a0e2780-00dd-11ea-8365-cd3f0ccb1707.png">
<img width="1486" alt="1" src="https://user-images.githubusercontent.com/24602230/68302584-514d1500-00dd-11ea-94f5-803921e658e7.png">

**Comment by chenqin** [comment] 2019-11-07 00:37
can we have log from executor 408 pasted here as well? (got killed by driver host: zw02-data-hdp-dn0622.gh.sankuai.com)

**Comment by laura779** [comment] 2019-11-07 06:28
syslog of executor 408:

19/11/05 23:03:48 INFO main CoarseGrainedExecutorBackend: resourceId: None
19/11/05 23:03:48 INFO main CoarseGrainedExecutorBackend: Started daemon with process name: 33419@zw02-data-hdp-dn0622.gh.sankuai.com
19/11/05 23:03:48 INFO main SignalUtils: Registered signal handler for TERM
19/11/05 23:03:48 INFO main SignalUtils: Registered signal handler for HUP
19/11/05 23:03:48 INFO main SignalUtils: Registered signal handler for INT
19/11/05 23:03:49 INFO main SecurityManager: Changing view acls to: hadoop-ns-mobile
19/11/05 23:03:49 INFO main SecurityManager: Changing modify acls to: hadoop-ns-mobile
19/11/05 23:03:49 INFO main SecurityManager: Changing view acls groups to: 
19/11/05 23:03:49 INFO main SecurityManager: Changing modify acls groups to: 
19/11/05 23:03:49 INFO main SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(hadoop-ns-mobile); groups with view permissions: Set(); users  with modify permissions: Set(hadoop-ns-mobile); groups with modify permissions: Set()
19/11/05 23:03:49 INFO netty-rpc-connection-0 TransportClientFactory: Successfully created connection to /10.132.133.9:18405 after 81 ms (0 ms spent in bootstraps)
19/11/05 23:03:49 INFO main SecurityManager: Changing view acls to: hadoop-ns-mobile
19/11/05 23:03:49 INFO main SecurityManager: Changing modify acls to: hadoop-ns-mobile
19/11/05 23:03:49 INFO main SecurityManager: Changing view acls groups to: 
19/11/05 23:03:49 INFO main SecurityManager: Changing modify acls groups to: 
19/11/05 23:03:49 INFO main SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(hadoop-ns-mobile); groups with view permissions: Set(); users  with modify permissions: Set(hadoop-ns-mobile); groups with modify permissions: Set()
19/11/05 23:03:50 INFO netty-rpc-connection-0 TransportClientFactory: Successfully created connection to /10.132.133.9:18405 after 1 ms (0 ms spent in bootstraps)
19/11/05 23:03:50 INFO main DiskBlockManager: Created local directory at /data2/hadoop/yarn/nm-local-dir/usercache/hadoop-ns-mobile/appcache/application_1565870337664_34700660/blockmgr-42a99bdb-4298-4dc8-a923-475cc21008ec
19/11/05 23:03:50 INFO main DiskBlockManager: Created local directory at /data3/hadoop/yarn/nm-local-dir/usercache/hadoop-ns-mobile/appcache/application_1565870337664_34700660/blockmgr-fd40d125-9270-437f-bb5b-7f183da31ec3
19/11/05 23:03:50 INFO main DiskBlockManager: Created local directory at /data4/hadoop/yarn/nm-local-dir/usercache/hadoop-ns-mobile/appcache/application_1565870337664_34700660/blockmgr-9f2488b0-45d2-40d5-b4db-f888eed8871c
19/11/05 23:03:50 INFO main DiskBlockManager: Created local directory at /data5/hadoop/yarn/nm-local-dir/usercache/hadoop-ns-mobile/appcache/application_1565870337664_34700660/blockmgr-802726c8-40ab-47de-8d03-021440af4e88
19/11/05 23:03:50 INFO main DiskBlockManager: Created local directory at /data6/hadoop/yarn/nm-local-dir/usercache/hadoop-ns-mobile/appcache/application_1565870337664_34700660/blockmgr-1888a847-7a3f-4349-9ead-7b7c6b8f9859
19/11/05 23:03:50 INFO main DiskBlockManager: Created local directory at /data7/hadoop/yarn/nm-local-dir/usercache/hadoop-ns-mobile/appcache/application_1565870337664_34700660/blockmgr-9b81b570-6838-459e-8b3b-12b1d0ad8f5e
19/11/05 23:03:50 INFO main DiskBlockManager: Created local directory at /data8/hadoop/yarn/nm-local-dir/usercache/hadoop-ns-mobile/appcache/application_1565870337664_34700660/blockmgr-f8607387-3abe-4f0b-a94e-d77375081aec
19/11/05 23:03:50 INFO main DiskBlockManager: Created local directory at /data9/hadoop/yarn/nm-local-dir/usercache/hadoop-ns-mobile/appcache/application_1565870337664_34700660/blockmgr-eea6b969-2c27-4c64-ab30-9cd7a64fe915
19/11/05 23:03:50 INFO main DiskBlockManager: Created local directory at /data10/hadoop/yarn/nm-local-dir/usercache/hadoop-ns-mobile/appcache/application_1565870337664_34700660/blockmgr-3f5c766f-8312-4a58-aadc-510d98a0f9e7
19/11/05 23:03:50 INFO main DiskBlockManager: Created local directory at /data11/hadoop/yarn/nm-local-dir/usercache/hadoop-ns-mobile/appcache/application_1565870337664_34700660/blockmgr-4337ad3d-1aee-486a-9131-0adeea7ebfec
19/11/05 23:03:50 INFO main DiskBlockManager: Created local directory at /data12/hadoop/yarn/nm-local-dir/usercache/hadoop-ns-mobile/appcache/application_1565870337664_34700660/blockmgr-97a2b447-37bd-4945-b5f2-33d4624df8a4
19/11/05 23:03:50 INFO main MemoryStore: MemoryStore started with capacity 3.1 GB
19/11/05 23:03:50 INFO main MtKafkaSink: MtKafkaSink Start. reportPeriod=60 reportUnit=SECONDS reportTimeoutSeconds=60
19/11/05 23:03:50 INFO dispatcher-event-loop-1 CoarseGrainedExecutorBackend: Connecting to driver: spark://CoarseGrainedScheduler@10.132.133.9:18405
19/11/05 23:03:50 INFO dispatcher-event-loop-3 CoarseGrainedExecutorBackend: Successfully registered with driver
19/11/05 23:03:50 INFO dispatcher-event-loop-3 Executor: Starting executor ID 408 on host zw02-data-hdp-dn0622.gh.sankuai.com
19/11/05 23:03:50 INFO dispatcher-event-loop-3 MemoryUsageSource: MemoryUsageSample Start. samplePeriod=5
19/11/05 23:03:50 INFO dispatcher-event-loop-3 Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 34580.
19/11/05 23:03:50 INFO dispatcher-event-loop-3 NettyBlockTransferService: Server created on zw02-data-hdp-dn0622.gh.sankuai.com:34580
19/11/05 23:03:50 INFO dispatcher-event-loop-3 BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
19/11/05 23:03:50 INFO dispatcher-event-loop-3 BlockManagerMaster: Registering BlockManager BlockManagerId(408, zw02-data-hdp-dn0622.gh.sankuai.com, 34580, None)
19/11/05 23:03:50 INFO dispatcher-event-loop-3 BlockManagerMaster: Registered BlockManager BlockManagerId(408, zw02-data-hdp-dn0622.gh.sankuai.com, 34580, None)
19/11/05 23:03:50 INFO dispatcher-event-loop-3 BlockManager: external shuffle service port = 7337
19/11/05 23:03:50 INFO dispatcher-event-loop-3 BlockManager: Registering executor with local external shuffle service.
19/11/05 23:03:50 INFO dispatcher-event-loop-3 TransportClientFactory: Successfully created connection to zw02-data-hdp-dn0622.gh.sankuai.com/10.132.8.18:7337 after 1 ms (0 ms spent in bootstraps)
19/11/05 23:03:50 INFO dispatcher-event-loop-3 BlockManager: Initialized BlockManager: BlockManagerId(408, zw02-data-hdp-dn0622.gh.sankuai.com, 34580, None)
19/11/05 23:03:50 INFO dispatcher-event-loop-3 CoarseGrainedExecutorBackend: Got assigned task 439
19/11/05 23:03:50 INFO Executor task launch worker for task 439 Executor: Running task 439.0 in stage 0.0 (TID 439)
19/11/05 23:03:50 INFO Executor task launch worker for task 439 TorrentBroadcast: Started reading broadcast variable 3
19/11/05 23:03:50 INFO Executor task launch worker for task 439 TransportClientFactory: Successfully created connection to zw02-data-hdp-dn7966.mt/10.133.65.17:47350 after 1 ms (0 ms spent in bootstraps)
19/11/05 23:03:50 INFO Executor task launch worker for task 439 MemoryStore: Block broadcast_3_piece0 stored as bytes in memory (estimated size 11.5 KB, free 3.1 GB)
19/11/05 23:03:50 INFO Executor task launch worker for task 439 TorrentBroadcast: Reading broadcast variable 3 took 134 ms
19/11/05 23:03:51 INFO Executor task launch worker for task 439 MemoryStore: Block broadcast_3 stored as values in memory (estimated size 26.5 KB, free 3.1 GB)
19/11/05 23:03:51 INFO Executor task launch worker for task 439 HadoopRDD: Input split: [Lorg.apache.hadoop.mapred.InputSplit;@7c4f4912
19/11/05 23:03:51 INFO Executor task launch worker for task 439 TorrentBroadcast: Started reading broadcast variable 0
19/11/05 23:03:51 INFO Executor task launch worker for task 439 TransportClientFactory: Successfully created connection to zw02-data-hdp-dn0622.gh.sankuai.com/10.132.8.18:49295 after 1 ms (0 ms spent in bootstraps)
19/11/05 23:03:51 INFO Executor task launch worker for task 439 MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 39.0 KB, free 3.1 GB)
19/11/05 23:03:51 INFO Executor task launch worker for task 439 TorrentBroadcast: Reading broadcast variable 0 took 82 ms
19/11/05 23:03:51 INFO Executor task launch worker for task 439 MemoryStore: Block broadcast_0 stored as values in memory (estimated size 640.4 KB, free 3.1 GB)
19/11/05 23:03:53 INFO Executor task launch worker for task 439 OrcRawRecordMerger: min key = null, max key = null
19/11/05 23:03:53 INFO Executor task launch worker for task 439 ReaderImpl: Reading ORC rows from ************/part-00439-89e44024-5717-45cb-969d-2670d63de61f-c000.snappy.orc with {include: [true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, true], offset: 0, length: 9223372036854775807}
19/11/05 23:03:54 INFO Executor task launch worker for task 439 CodeGenerator: Code generated in 238.058819 ms
19/11/05 23:03:54 INFO Executor task launch worker for task 439 CodeGenerator: Code generated in 39.737367 ms
19/11/05 23:03:54 INFO Executor task launch worker for task 439 CodeGenerator: Code generated in 25.34497 ms
19/11/05 23:04:04 INFO Executor task launch worker for task 439 Executor: Finished task 439.0 in stage 0.0 (TID 439). 4164 bytes result sent to driver
19/11/05 23:04:04 INFO dispatcher-event-loop-6 CoarseGrainedExecutorBackend: Got assigned task 1496
19/11/05 23:04:04 INFO Executor task launch worker for task 1496 Executor: Running task 1496.0 in stage 0.0 (TID 1496)
19/11/05 23:04:04 INFO Executor task launch worker for task 1496 HadoopRDD: Input split: [Lorg.apache.hadoop.mapred.InputSplit;@2e546d79
19/11/05 23:04:04 INFO Executor task launch worker for task 1496 OrcRawRecordMerger: min key = null, max key = null
19/11/05 23:04:04 INFO Executor task launch worker for task 1496 ReaderImpl: Reading ORC rows from *********/part-01496-89e44024-5717-45cb-969d-2670d63de61f-c000.snappy.orc with {include: [true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, true], offset: 0, length: 9223372036854775807}
19/11/05 23:04:13 INFO Executor task launch worker for task 1496 Executor: Finished task 1496.0 in stage 0.0 (TID 1496). 3257 bytes result sent to driver
19/11/05 23:04:13 INFO dispatcher-event-loop-7 CoarseGrainedExecutorBackend: Got assigned task 2416
19/11/05 23:04:13 INFO Executor task launch worker for task 2416 Executor: Running task 765.0 in stage 1.0 (TID 2416)
19/11/05 23:04:13 INFO Executor task launch worker for task 2416 TorrentBroadcast: Started reading broadcast variable 2
19/11/05 23:04:13 INFO Executor task launch worker for task 2416 TransportClientFactory: Successfully created connection to zw02-data-hdp-dn1159.gh.sankuai.com/10.132.52.3:19088 after 1 ms (0 ms spent in bootstraps)
19/11/05 23:04:13 INFO Executor task launch worker for task 2416 MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 11.5 KB, free 3.1 GB)
19/11/05 23:04:13 INFO Executor task launch worker for task 2416 TorrentBroadcast: Reading broadcast variable 2 took 12 ms
19/11/05 23:04:13 INFO Executor task launch worker for task 2416 MemoryStore: Block broadcast_2 stored as values in memory (estimated size 26.5 KB, free 3.1 GB)
19/11/05 23:04:13 INFO Executor task launch worker for task 2416 HadoopRDD: Input split: [Lorg.apache.hadoop.mapred.InputSplit;@3c3a63bc
19/11/05 23:04:13 INFO Executor task launch worker for task 2416 OrcRawRecordMerger: min key = null, max key = null
19/11/05 23:04:13 INFO Executor task launch worker for task 2416 ReaderImpl: Reading ORC rows from *********/part-00765-89e44024-5717-45cb-969d-2670d63de61f-c000.snappy.orc with {include: [true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, true], offset: 0, length: 9223372036854775807}
19/11/05 23:04:21 INFO Executor task launch worker for task 2416 Executor: Finished task 765.0 in stage 1.0 (TID 2416). 4015 bytes result sent to driver
19/11/05 23:04:21 INFO dispatcher-event-loop-8 CoarseGrainedExecutorBackend: Got assigned task 3335
19/11/05 23:04:21 INFO Executor task launch worker for task 3335 Executor: Running task 33.0 in stage 3.0 (TID 3335)
19/11/05 23:04:21 INFO Executor task launch worker for task 3335 TorrentBroadcast: Started reading broadcast variable 1
19/11/05 23:04:21 INFO Executor task launch worker for task 3335 TransportClientFactory: Successfully created connection to zw02-data-hdp-dn3718.gh.sankuai.com/10.132.131.18:13795 after 1 ms (0 ms spent in bootstraps)
19/11/05 23:04:21 INFO Executor task launch worker for task 3335 MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 11.1 KB, free 3.1 GB)
19/11/05 23:04:21 INFO Executor task launch worker for task 3335 TorrentBroadcast: Reading broadcast variable 1 took 11 ms
19/11/05 23:04:21 INFO Executor task launch worker for task 3335 MemoryStore: Block broadcast_1 stored as values in memory (estimated size 25.9 KB, free 3.1 GB)
19/11/05 23:04:21 INFO Executor task launch worker for task 3335 HadoopRDD: Input split: [Lorg.apache.hadoop.mapred.InputSplit;@cb0120e
19/11/05 23:04:21 INFO Executor task launch worker for task 3335 OrcRawRecordMerger: min key = null, max key = null
19/11/05 23:04:21 INFO Executor task launch worker for task 3335 ReaderImpl: Reading ORC rows from ***********/part-00033-89e44024-5717-45cb-969d-2670d63de61f-c000.snappy.orc with {include: [true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, true], offset: 0, length: 9223372036854775807}
19/11/05 23:04:33 INFO Executor task launch worker for task 3335 Executor: Finished task 33.0 in stage 3.0 (TID 3335). 4015 bytes result sent to driver
19/11/05 23:04:33 INFO dispatcher-event-loop-9 CoarseGrainedExecutorBackend: Got assigned task 4539
19/11/05 23:04:33 INFO Executor task launch worker for task 4539 Executor: Running task 1237.0 in stage 3.0 (TID 4539)
19/11/05 23:04:33 INFO Executor task launch worker for task 4539 HadoopRDD: Input split: [Lorg.apache.hadoop.mapred.InputSplit;@1907d098
19/11/05 23:04:33 INFO Executor task launch worker for task 4539 OrcRawRecordMerger: min key = null, max key = null
19/11/05 23:04:33 INFO Executor task launch worker for task 4539 ReaderImpl: Reading ORC rows from **********/part-01237-89e44024-5717-45cb-969d-2670d63de61f-c000.snappy.orc with {include: [true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, true], offset: 0, length: 9223372036854775807}
19/11/05 23:04:44 INFO Executor task launch worker for task 4539 Executor: Finished task 1237.0 in stage 3.0 (TID 4539). 3257 bytes result sent to driver
19/11/05 23:04:51 INFO dispatcher-event-loop-10 CoarseGrainedExecutorBackend: Got assigned task 5816
19/11/05 23:04:51 INFO Executor task launch worker for task 5816 Executor: Running task 863.0 in stage 2.0 (TID 5816)
19/11/05 23:04:51 INFO Executor task launch worker for task 5816 MapOutputTrackerWorker: Updating epoch to 2 and clearing cache
19/11/05 23:04:51 INFO Executor task launch worker for task 5816 TorrentBroadcast: Started reading broadcast variable 4
19/11/05 23:04:51 INFO Executor task launch worker for task 5816 MemoryStore: Block broadcast_4_piece0 stored as bytes in memory (estimated size 2.3 KB, free 3.1 GB)
19/11/05 23:04:51 INFO Executor task launch worker for task 5816 TorrentBroadcast: Reading broadcast variable 4 took 157 ms
19/11/05 23:04:51 INFO Executor task launch worker for task 5816 MemoryStore: Block broadcast_4 stored as values in memory (estimated size 3.8 KB, free 3.1 GB)
19/11/05 23:04:51 INFO Executor task launch worker for task 5816 MapOutputTrackerWorker: Don't have map outputs for shuffle 6, fetching them
19/11/05 23:04:51 INFO Executor task launch worker for task 5816 MapOutputTrackerWorker: Doing the fetch; tracker endpoint = NettyRpcEndpointRef(spark://MapOutputTracker@10.132.133.9:18405)
19/11/05 23:04:51 INFO Executor task launch worker for task 5816 MapOutputTrackerWorker: Got the output locations
19/11/05 23:04:51 INFO Executor task launch worker for task 5816 ShuffleBlockFetcherIterator: Getting 1 non-empty blocks including 0 local blocks and 1 remote blocks
19/11/05 23:04:51 INFO Executor task launch worker for task 5816 TransportClientFactory: Successfully created connection to zw02-data-hdp-dn7689.gh.sankuai.com/10.133.12.2:7337 after 2 ms (0 ms spent in bootstraps)
19/11/05 23:04:51 INFO Executor task launch worker for task 5816 ShuffleBlockFetcherIterator: Started 1 remote fetches in 21 ms
19/11/05 23:04:52 INFO Executor task launch worker for task 5816 Executor: Finished task 863.0 in stage 2.0 (TID 5816). 3930 bytes result sent to driver
19/11/05 23:04:59 INFO dispatcher-event-loop-11 CoarseGrainedExecutorBackend: Got assigned task 6621
19/11/05 23:04:59 INFO Executor task launch worker for task 6621 Executor: Running task 17.0 in stage 4.0 (TID 6621)
19/11/05 23:04:59 INFO Executor task launch worker for task 6621 MapOutputTrackerWorker: Updating epoch to 3 and clearing cache
19/11/05 23:04:59 INFO Executor task launch worker for task 6621 TorrentBroadcast: Started reading broadcast variable 5
19/11/05 23:04:59 INFO Executor task launch worker for task 6621 TransportClientFactory: Successfully created connection to /10.132.133.9:40480 after 1 ms (0 ms spent in bootstraps)
19/11/05 23:04:59 INFO Executor task launch worker for task 6621 MemoryStore: Block broadcast_5_piece0 stored as bytes in memory (estimated size 2.8 KB, free 3.1 GB)
19/11/05 23:04:59 INFO Executor task launch worker for task 6621 TorrentBroadcast: Reading broadcast variable 5 took 71 ms
19/11/05 23:04:59 INFO Executor task launch worker for task 6621 MemoryStore: Block broadcast_5 stored as values in memory (estimated size 5.3 KB, free 3.1 GB)
19/11/05 23:05:00 INFO Executor task launch worker for task 6621 MapOutputTrackerWorker: Don't have map outputs for shuffle 5, fetching them
19/11/05 23:05:00 INFO Executor task launch worker for task 6621 MapOutputTrackerWorker: Doing the fetch; tracker endpoint = NettyRpcEndpointRef(spark://MapOutputTracker@10.132.133.9:18405)
19/11/05 23:05:00 INFO Executor task launch worker for task 6621 MapOutputTrackerWorker: Got the output locations
19/11/05 23:05:00 INFO Executor task launch worker for task 6621 ShuffleBlockFetcherIterator: Getting 1 non-empty blocks including 0 local blocks and 1 remote blocks
19/11/05 23:05:00 INFO Executor task launch worker for task 6621 TransportClientFactory: Successfully created connection to zw02-data-hdp-dn9830.gh.sankuai.com/10.133.56.16:7337 after 2 ms (0 ms spent in bootstraps)
19/11/05 23:05:00 INFO Executor task launch worker for task 6621 ShuffleBlockFetcherIterator: Started 1 remote fetches in 4 ms
19/11/05 23:05:00 INFO Executor task launch worker for task 6621 MapOutputTrackerWorker: Don't have map outputs for shuffle 0, fetching them
19/11/05 23:05:00 INFO Executor task launch worker for task 6621 MapOutputTrackerWorker: Doing the fetch; tracker endpoint = NettyRpcEndpointRef(spark://MapOutputTracker@10.132.133.9:18405)
19/11/05 23:05:00 INFO Executor task launch worker for task 6621 MapOutputTrackerWorker: Got the output locations
19/11/05 23:05:00 INFO Executor task launch worker for task 6621 ShuffleBlockFetcherIterator: Getting 1 non-empty blocks including 0 local blocks and 1 remote blocks
19/11/05 23:05:00 INFO Executor task launch worker for task 6621 TransportClientFactory: Successfully created connection to zw02-data-hdp-dn3467.gh.sankuai.com/10.132.122.37:7337 after 11 ms (0 ms spent in bootstraps)
19/11/05 23:05:00 INFO Executor task launch worker for task 6621 ShuffleBlockFetcherIterator: Started 1 remote fetches in 23 ms
19/11/05 23:05:01 INFO Executor task launch worker for task 6621 Executor: Finished task 17.0 in stage 4.0 (TID 6621). 3930 bytes result sent to driver
19/11/05 23:05:05 INFO dispatcher-event-loop-13 CoarseGrainedExecutorBackend: Got assigned task 8563
19/11/05 23:05:05 INFO Executor task launch worker for task 8563 Executor: Running task 308.0 in stage 5.0 (TID 8563)
19/11/05 23:05:05 INFO Executor task launch worker for task 8563 MapOutputTrackerWorker: Updating epoch to 5 and clearing cache
19/11/05 23:05:05 INFO Executor task launch worker for task 8563 TorrentBroadcast: Started reading broadcast variable 6
19/11/05 23:05:05 INFO Executor task launch worker for task 8563 TransportClientFactory: Successfully created connection to zw02-data-hdp-dn1380.gh.sankuai.com/10.132.50.36:38199 after 3 ms (0 ms spent in bootstraps)
19/11/05 23:05:05 INFO Executor task launch worker for task 8563 MemoryStore: Block broadcast_6_piece0 stored as bytes in memory (estimated size 7.6 KB, free 3.1 GB)
19/11/05 23:05:05 INFO Executor task launch worker for task 8563 TorrentBroadcast: Reading broadcast variable 6 took 91 ms
19/11/05 23:05:05 INFO Executor task launch worker for task 8563 MemoryStore: Block broadcast_6 stored as values in memory (estimated size 20.0 KB, free 3.1 GB)
19/11/05 23:05:05 INFO Executor task launch worker for task 8563 MapOutputTrackerWorker: Don't have map outputs for shuffle 2, fetching them
19/11/05 23:05:05 INFO Executor task launch worker for task 8563 MapOutputTrackerWorker: Doing the fetch; tracker endpoint = NettyRpcEndpointRef(spark://MapOutputTracker@10.132.133.9:18405)
19/11/05 23:05:05 INFO Executor task launch worker for task 8563 MapOutputTrackerWorker: Got the output locations
19/11/05 23:05:05 INFO Executor task launch worker for task 8563 ShuffleBlockFetcherIterator: Getting 1 non-empty blocks including 0 local blocks and 1 remote blocks
19/11/05 23:05:05 INFO Executor task launch worker for task 8563 TransportClientFactory: Successfully created connection to zw02-data-hdp-dn3554.gh.sankuai.com/10.132.125.11:7337 after 5 ms (0 ms spent in bootstraps)
19/11/05 23:05:05 INFO Executor task launch worker for task 8563 ShuffleBlockFetcherIterator: Started 1 remote fetches in 8 ms
19/11/05 23:05:05 INFO Executor task launch worker for task 8563 MapOutputTrackerWorker: Don't have map outputs for shuffle 3, fetching them
19/11/05 23:05:05 INFO Executor task launch worker for task 8563 MapOutputTrackerWorker: Doing the fetch; tracker endpoint = NettyRpcEndpointRef(spark://MapOutputTracker@10.132.133.9:18405)
19/11/05 23:05:05 INFO Executor task launch worker for task 8563 MapOutputTrackerWorker: Got the output locations
19/11/05 23:05:05 INFO Executor task launch worker for task 8563 ShuffleBlockFetcherIterator: Getting 1 non-empty blocks including 0 local blocks and 1 remote blocks
19/11/05 23:05:05 INFO Executor task launch worker for task 8563 TransportClientFactory: Successfully created connection to zw02-data-hdp-dn5525.gh.sankuai.com/10.132.156.21:7337 after 10 ms (0 ms spent in bootstraps)
19/11/05 23:05:05 INFO Executor task launch worker for task 8563 ShuffleBlockFetcherIterator: Started 1 remote fetches in 12 ms
19/11/05 23:05:08 INFO Executor task launch worker for task 8563 CodeGenerator: Code generated in 95.343949 ms
19/11/05 23:05:08 INFO Executor task launch worker for task 8563 Executor: Finished task 308.0 in stage 5.0 (TID 8563). 2926 bytes result sent to driver
19/11/05 23:06:11 ERROR SIGTERM handler CoarseGrainedExecutorBackend: RECEIVED SIGNAL TERM
19/11/05 23:06:11 INFO Thread-6 DiskBlockManager: Shutdown hook called
19/11/05 23:06:11 INFO Thread-6 ShutdownHookManager: Shutdown hook called

**Comment by chenqin** [comment] 2019-11-07 19:29
humm, this may not be the root cause of failure->stuck. Can you upload full log zip to and share a link for us to look into?

**Comment by dubeyrahul** [comment] 2020-01-16 08:09
Hi @laura779, how did you represent the training data for distributed learning to rank (pairwise) for xgboost?
I am trying to understand how to specify groupID for pairwise learning to rank problem. Any help would be appreciated!

**Comment by marvinxu-free** [comment] 2020-05-22 16:18
i have met this problem too, driver log show error like this:
```
java.io.IOException: Server returned HTTP response code: 500 for URL: http://novel-read-wxhpcli-2.wxxdc:4040/api/v1/applications/application_1589120307951_1019763/executors
```
seems nothing to do with my program, and my spark version is 2.3.0, xgboost version is 0.82.

[my issue](https://github.com/dmlc/xgboost/issues/5697)

**Comment by zmitchn** [comment] 2021-11-13 07:56
Is there any progress on this issue? I've met the same question here

**Comment by trivialfis** [comment] 2024-05-17 07:10
Closing due to stalled. Feel free to open a new issue if there's a reproducer.

**Closed by trivialfis** 2024-05-17 07:10 UTC
