### ISSUE TITLE
Non zero cache_id error

### ISSUE THREAD

**Issue by jeswcollins** [dmlc/xgboost#7740] opened 2022-03-21 16:21 UTC
In one environment, I can load an xgboost model from json fine and predict with it.

When moving this model to another environment, and predicting, I get an error that appears in the current version to be the following line, due to a >0 cache_id:

https://github.com/dmlc/xgboost/blob/cd558231123113d1fd7a99ff0a6cc4ef1c528c33/src/c_api/c_api.cc?msclkid=ffc5a076a93011ecae1011be44fe7735#L829

Why is cache_id non-zero? And how can I ensure it is zero in a new environment?

**Comment by trivialfis** [comment] 2022-03-21 16:49
Could you please share how to reproduce it?

**Comment by trivialfis** [comment] 2022-03-21 16:55
Using the Python interface, this is where the `cache_id` being set: https://github.com/dmlc/xgboost/blob/4d81c741e91c7660648f02d77b61ede33cef8c8d/python-package/xgboost/core.py#L2038 

If you are using the C interface directly, then I need to look at your code.  Also, could you please share your environment?

**Comment by jeswcollins** [comment] 2022-03-21 17:20
I'm using python, not the C interface directly. 

I've observed the error on 1.5.0 and 1.5.2.

I will try to see if I can find a way to reproduce the error that I can share and more info on the environment. 

Unless cache_id was set differently in prior versions, I don't see how it could be >0 in this model.

**Comment by trivialfis** [comment] 2022-03-21 18:19
Thank you.

> Was cache_id set differently in prior versions? How could it be >0 in this model?

No.  It's a placeholder and has been set to 0 since it was introduced.

**Comment by trivialfis** [comment] 2022-10-10 05:35
Closing as stalled.

**Closed by trivialfis** 2022-10-10 05:35 UTC
Labels: status: need update
