### ISSUE TITLE
xgboost model metadata is not correctly saved with xgb.save

### ISSUE THREAD

**Issue by andysw90** [dmlc/xgboost#8358] opened 2022-10-18 14:54 UTC
When a model is saved to file, the model configuration is not correctly saved. The example below shows how a model with `max_depth = 2` does not retain that information on save and reload. 

```
library(jsonlite)
library(xgboost)

data(agaricus.train, package='xgboost')

train <- agaricus.train

bst <- xgboost(data = train$data, label = train$label, 
               max_depth = 2,
               eta = 1, nthread = 2, nrounds = 2, objective = "binary:logistic")
xgb.save(bst,"tmp.model")
bst_from_file <- xgb.load("tmp.model")

get_depth <- function(bst_in){
  bst_in <- xgb.Booster.complete(bst_in)
  config_string <- xgb.config(bst_in)
  config_list <-  fromJSON(config_string)
  depth <- config_list$learner$gradient_booster$updater$grow_colmaker$train_param$max_depth
  return(depth)
}
get_depth(bst)           # Pre-save depth
get_depth(bst_from_file) # Post-save depth
```

**Comment by trivialfis** [comment] 2022-10-18 16:02
Hi, this is by design, we don't want to save training hyper-parameters in the model. See https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html for details.

**Comment by andysw90** [comment] 2022-10-18 16:17
Noted, thank you. Dumping the config as json is useful. Would it be sensible to strip metadata fields from the info saved in the config of the model on file? At the moment is seems to just be populated with the default values, might make more sense for it to be NULL?

**Comment by trivialfis** [comment] 2022-10-18 16:48
> might make more sense for it to be NULL

I agree. It's somehow a convention that library developers (me included, guilty as charged) like to tie the hyper-parameters of the training algorithm to the resulting booster. If I were to have another go at designing a new ml library, I might prefer a more functional style API and make a clear separation between the training algorithm and its resulting model.

For now, I don't think we can change xgboost to detect whether the parameter is specified by the user or by default without significant code bloat.

**Comment by trivialfis** [comment] 2022-10-20 11:32
Will close this now as it's expected behavior.

**Closed by trivialfis** 2022-10-20 11:32 UTC
