### ISSUE TITLE
How to accelerate the speed of CPP API XGBoosterPredict?

### ISSUE THREAD

**Issue by guotong1988** [dmlc/xgboost#3512] opened 2018-07-26 10:45 UTC
### Training params:

```
XGBoosterSetParam(h_booster, "booster", "gbtree");
XGBoosterSetParam(h_booster, "objective", "binary:logistic");
XGBoosterSetParam(h_booster, "max_depth", "5");
XGBoosterSetParam(h_booster, "eta", "0.1");
XGBoosterSetParam(h_booster, "silent", "1");
XGBoosterSetParam(h_booster, "min_child_weight", "1");
XGBoosterSetParam(h_booster, "subsample", "0.5");
XGBoosterSetParam(h_booster, "colsample_bytree", "1");
XGBoosterSetParam(h_booster, "num_parallel_tree", "1");
```

### The code for prediction is:
```
long t1 = clock();
XGBoosterPredict(h_booster, h_test, 0, 0, &out_len, &f);
long t2 = clock();
printf("xgboost predict costs time %f ms\n",(float(t2-t1)*1000)/CLOCKS_PER_SEC);
```
### My CPU info is:

`cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c`
```
72  Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
```

### My memory info is:
`free`
```
              total        used        free      shared  buff/cache   available
Mem:      131616920      935520    63548288       31804    67133112   130023444
Swap:       4194300       51036     4143264
```

**Comment by hcho3** [comment] 2018-07-26 15:16
Closing this as duplicate of https://discuss.xgboost.ai/t/cpp-api-xgboosterpredict-cost-too-much-time/97.

**Closed by hcho3** 2018-07-26 15:16 UTC

**Comment by RAMitchell** [comment] 2018-07-27 01:13
This may in fact be a bug. I made some changes to the prediction API in order to deal with failures from statically allocated cuda memory in HostDeviceVector in #3467.

**Comment by guotong1988** [comment] 2018-07-27 01:15
@RAMitchell What is your speed now？

**Comment by RAMitchell** [comment] 2018-07-27 01:16
Not sure I understand your question.

Can you confirm exactly which version of xgboost you are using (e.g. the commit hash). I would like to know if it works correctly before this was merged.

**Comment by guotong1988** [comment] 2018-07-27 01:18
`git log`
```
commit 01aff45f26beef711813752fc93a860a6050d5d4
Author: Tianqi Chen <tqchen@users.noreply.github.com>
Date:   Wed Jul 4 13:09:32 2018 -0700

    Update README.md
```

**Comment by RAMitchell** [comment] 2018-07-27 01:21
This commit is older than #3467 so it can't be related to that.

**Comment by guotong1988** [comment] 2018-07-27 03:01
**Is it a bug? I use python API to predict 2000 data in 20 ms.**

```
def get_time_stamp():
    ct = time.time()
    local_time = time.localtime(ct)
    data_head = time.strftime("%Y-%m-%d %H:%M:%S", local_time)
    data_secs = (ct - int(ct)) * 1000
    time_stamp = "%s.%03d" % (data_head, data_secs)
    return time_stamp
import time
print(get_time_stamp())
begin_time = int(time.time()*1000)
valid_predict = xgb_trained_model.predict(valid_xgb)
print(int(time.time()*1000)-begin_time)
print(get_time_stamp())

```

**Comment by guotong1988** [comment] 2018-07-27 03:29
Sorry, the time print of my Cpp code is wrong.
