### ISSUE TITLE
Validation of the RECORD file failed in Poetry (1.8.3)

### ISSUE THREAD

**Issue by SMAntony** [dmlc/xgboost#10672] opened 2024-08-02 10:46 UTC
I got this warning when I was trying to install `autoviz` package. What is wrong? Will XGBoost still work? When using pip there is no such warning.

**Warning:**
Warning: Validation of the RECORD file of xgboost-1.6.2-py3-none-win_amd64.whl failed. Please report to the maintainers of that package so they can fix their build process.

**Environment Info:**
Python: 3.12.2
Poetry: 1.8.3

**Comment by trivialfis** [comment] 2024-08-02 12:16
XGBoost 1.6.2 is a really old version, could you please try the latest? I believe a related issue was fixed in https://github.com/dmlc/xgboost/issues/8987#issuecomment-1487875849 .

**Comment by trivialfis** [comment] 2024-08-05 19:42
Tested adding xgboost 2.1.1 to a poetry project. Feel free to reopen if the issue is reproducible with the latest xgboost.

**Closed by trivialfis** 2024-08-05 19:42 UTC
Labels: status: need update
