### ISSUE TITLE
xgboost model fit error in python 

### ISSUE THREAD

**Issue by oldwan2** [dmlc/xgboost#10594] opened 2024-07-16 14:37 UTC
When I use the following code in python:
import xgboost as xgb
import pandas as pd
import numpy as np
import matplotlib. pyplot as plt
plt.style.use('seaborn-v0_8')
import shap
from sklearn. model_selection import train_test_split

my_random_state = 50

data = pd. read_csv('G:/Input for model.csv')

cols = [
'Aspect', 'Aspect_cv', 'Slope_cv', 'Elevation_cv',
'Forest height', 'Root depth', 'Tree density',
'Drought intensity', 'Available water capacity',
'Soil clay', 'Soil sand', 'Precipitation',
'Native plant species richness'
]

x_all = data[cols].values
y_all = data['y'].values
x_train, x_test, y_train, y_test = train_test_split(x_all, y_all,test_size=0.3, random_state=my_random_state)

model = xgb. XGBRegressor(max_depth=4, learning_rate=0.05, n_estimators=150)

model. fit(x_train, y_train)
Error occurs
![Snipaste](https://github.com/user-attachments/assets/02589542-a8c2-4028-bdf5-15be871f548e)
I have reinstalled the xgboost package and python several times, but it still doesn't work, what can I do?

**Comment by trivialfis** [comment] 2024-07-16 15:16
Hi, could you please share how you install XGBoost?

**Comment by oldwan2** [comment] 2024-07-17 00:55
> Hi, could you please share how you install XGBoost?

![Snipaste2](https://github.com/user-attachments/assets/21e4ad53-fac8-424e-a194-babc0d44e21a)
thks for u reply,I use the windows powershell to install it.

**Comment by trivialfis** [comment] 2024-07-17 10:05
@hcho3 Have you seen this on Windows before?

**Comment by trivialfis** [comment] 2024-08-16 11:50
Closing due to unable to reproduce.

**Closed by trivialfis** 2024-08-16 11:50 UTC
Labels: status: need update
